In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=MORTGAGE30US"
mortgage = pd.read_csv(url, parse_dates=['observation_date'])
mortgage.columns = ['date', 'rate_30yr_fixed']

In [4]:
# Making a unified listing df
listing_dfs = []

for year in [2024, 2026]:
    for month in range(1, 13):
        fname = f"CRMLSListing{year}{month:02d}.csv"
        try:
            df = pd.read_csv(fname,parse_dates=['CloseDate'])
            df['Year'] = year
            df['Month'] = month
            listing_dfs.append(df)
        except FileNotFoundError:
            # Skip months that don't exist yet
            continue

# If you want one big DataFrame:
all_listings_df = pd.concat(listing_dfs, ignore_index=True)

In [5]:
all_listings_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524321 entries, 0 to 524320
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             522294 non-null  float64
 1   ListingKey                    524321 non-null  int64
 2   ListAgentEmail                418402 non-null  str
 3   CloseDate                     132185 non-null  datetime64[us]
 4   ClosePrice                    116133 non-null  float64
 5   ListAgentFirstName            521135 non-null  str
 6   ListAgentLastName             524286 non-null  str
 7   Latitude                      417027 non-null  float64
 8   Longitude                     417566 non-null  float64
 9   UnparsedAddress               522906 non-null  str
 10  PropertyType                  524321 non-null  str
 11  LivingArea                    457927 non-null  float64
 12  ListPrice                     523023 non-null  float64
 13  DaysOnMarket                  524321 non-null  int64
 14  ListOfficeName                524321 non-null  str
 15  BuyerOfficeName               124977 non-null  str
 16  CoListOfficeName              104105 non-null  str
 17  ListAgentFullName             524204 non-null  str
 18  CoListAgentFirstName          103546 non-null  str
 19  CoListAgentLastName           103841 non-null  str
 20  BuyerAgentMlsId               126178 non-null  str
 21  BuyerAgentFirstName           125939 non-null  str
 22  BuyerAgentLastName            126486 non-null  str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       152223 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             524321 non-null  int64
 27  MLSAreaMajor                  465133 non-null  str
 28  TaxAnnualAmount               3902 non-null    float64
 29  CountyOrParish                524320 non-null  str
 30  PropertyType.1                524321 non-null  str
 31  MlsStatus                     524321 non-null  str
 32  ElementarySchool              49722 non-null   str
 33  ListAgentFirstName.1          521135 non-null  str
 34  AttachedGarageYN              346249 non-null  object
 35  ParkingTotal                  491219 non-null  float64
 36  BuilderName                   17636 non-null   str
 37  PropertySubType               459512 non-null  str
 38  LotSizeAcres                  472856 non-null  float64
 39  SubdivisionName               174159 non-null  str
 40  BuyerOfficeAOR                119372 non-null  str
 41  YearBuilt                     481448 non-null  float64
 42  DaysOnMarket.1                524321 non-null  int64
 43  BuyerAgencyCompensationType   123538 non-null  str
 44  StreetNumberNumeric           521932 non-null  float64
 45  LivingArea.1                  457927 non-null  float64
 46  ListingId                     524321 non-null  str
 47  BathroomsTotalInteger         480167 non-null  float64
 48  City                          523654 non-null  str
 49  BuyerAgencyCompensation       123519 non-null  float64
 50  TaxYear                       553 non-null     float64
 51  BuildingAreaTotal             84174 non-null   float64
 52  BedroomsTotal                 459855 non-null  float64
 53  ContractStatusChangeDate      519637 non-null  str
 54  Longitude.1                   417566 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         9868 non-null    str
 57  PurchaseContractDate          213679 non-null  str
 58  ListingContractDate           524321 non-null  str
 59  BelowGradeFinishedArea        2002 non-null    float64
 60  BusinessType                  3843 non-null    str
 61  Latitude.1                    417027 non-null  float64
 62  ListPrice.1                   523023 non-null  float64
 63  StateOrProvince               524271 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          49810 non-null   str
 66  FireplaceYN                   447796 non-null  object
 67  Stories                       384847 non-null  float64
 68  HighSchool                    65226 non-null   str
 69  Levels                        420096 non-null  str
 70  ListAgentLastName.1           524286 non-null  str
 71  CloseDate.1                   132185 non-null  str
 72  LotSizeDimensions             29685 non-null   str
 73  LotSizeArea                   475226 non-null  float64
 74  MainLevelBedrooms             240796 non-null  float64
 75  NewConstructionYN             453924 non-null  object
 76  GarageSpaces                  424883 non-null  float64
 77  HighSchoolDistrict            316573 non-null  str
 78  PostalCode                    524171 non-null  str
 79  BuyerOfficeName.1             124977 non-null  str
 80  AssociationFee                354913 non-null  float64
 81  LotSizeSquareFeet             474556 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             522906 non-null  str
 84  Year                          524321 non-null  int64
 85  Month                         524321 non-null  int64
dtypes: datetime64[us](1), float64(32), int64(6), object(3), str(44)
memory usage: 344.0+ MB

In [6]:
print("Preview of Concatenated Listing DataFrame")
display(all_listings_df.tail())

print("---------/--------")
print("All columns in DataFrame\n")
print(all_listings_df.columns)
print("---------/--------")
print("Description of DataFrame\n")
print(all_listings_df.describe)

Preview of Concatenated Listing DataFrame

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month
524316,1375000.0,1151355330,NaN,NaT,NaN,Athir,Markos,32.811131,-116.946359,1161 N Anza Street,...,NaN,NaN,92021,NaN,0.0,222156.0,NaN,1161 N Anza Street,2026,4
524317,985000.0,1149517845,NaN,NaT,NaN,Aisa,Tu,33.645255,-117.358172,33115 Evergreen Sreet,...,3.0,Lake Elsinore Unified,92530,NaN,0.0,14810.0,NaN,33115 Evergreen Sreet,2026,4
524318,450000.0,1147219386,NaN,NaT,NaN,Nathaly,Vera,32.746368,-116.984283,9860 Dale Avenue D2,...,0.0,Other,91977,NaN,510.0,91040.4,NaN,9860 Dale Avenue D2,2026,4
524319,249000.0,1145273331,NaN,NaT,NaN,Bill,Church,33.229747,-117.127269,Little Canyon Lane,...,NaN,NaN,92026,NaN,210.0,37897.0,NaN,Little Canyon Lane,2026,4
524320,1056400.0,1144232364,NaN,2026-02-05,965200.0,John,Osborne,33.637915,-114.575821,9165 Intake Boulevard,...,NaN,NaN,92225,SimpliHOM,NaN,3445160.0,NaN,9165 Intake Boulevard,2026,4

---------/--------
All columns in DataFrame

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1', 'Year', 'Month'],
      dtype='str')
---------/--------
Description of DataFrame

<bound method NDFrame.describe of         OriginalListPrice  ListingKey                        ListAgentEmail  \
0                 90000.0  1075010398                miriamlara03@gmail.com
1               1500000.0  1074974457                  janelle@judsonre.com
2               1340000.0  1074973329                    haleh360@Gmail.com
3               2500000.0  1074954552  Reneechen@yourhomesoldguaranteed.com
4               3150000.0  1074936537                      anader@dppre.com
...                   ...         ...                                   ...
524316          1375000.0  1151355330                                   NaN
524317           985000.0  1149517845                                   NaN
524318           450000.0  1147219386                                   NaN
524319           249000.0  1145273331                                   NaN
524320          1056400.0  1144232364                                   NaN

        CloseDate  ClosePrice ListAgentFirstName ListAgentLastName   Latitude  \
0             NaT         NaN             Miriam              Lara  34.097939
1             NaT         NaN            Janelle            Judson  33.121241
2             NaT         NaN              Haleh       Dowlatshahi  34.052207
3             NaT         NaN              Renee              Chen  33.496363
4             NaT         NaN           Margaret             Nader  34.119345
...           ...         ...                ...               ...        ...
524316        NaT         NaN              Athir            Markos  32.811131
524317        NaT         NaN               Aisa                Tu  33.645255
524318        NaT         NaN            Nathaly              Vera  32.746368
524319        NaT         NaN               Bill            Church  33.229747
524320 2026-02-05    965200.0               John           Osborne  33.637915

         Longitude                UnparsedAddress  ... GarageSpaces  \
0      -117.909653                1045 N Azusa 61  ...          2.0
1      -117.081614                            NaN  ...          NaN
2      -118.408445  2220 Avenue Of The Stars 2704  ...          NaN
3      -117.691677                   16 Palisades  ...          3.0
4      -118.111254              1615 Waverly Road  ...          2.0
...            ...                            ...  ...          ...
524316 -116.946359             1161 N Anza Street  ...          NaN
524317 -117.358172          33115 Evergreen Sreet  ...          3.0
524318 -116.984283            9860 Dale Avenue D2  ...          0.0
524319 -117.127269             Little Canyon Lane  ...          NaN
524320 -114.575821          9165 Intake Boulevard  ...          NaN

           HighSchoolDistrict  PostalCode  BuyerOfficeName.1 AssociationFee  \
0       Covina Valley Unified       91722                NaN            0.0
1                         NaN       92025                NaN            0.0
2                         NaN       90067                NaN         2105.0
3          Capistrano Unified       92677                NaN          254.0
4                         NaN       91108                NaN            NaN
...                       ...         ...                ...            ...
524316                    NaN       92021                NaN            0.0
524317  Lake Elsinore Unified       92530                NaN            0.0
524318                  Other       91977                NaN          510.0
524319                    NaN       92026                NaN          210.0
524320                    NaN       92225          SimpliHOM            NaN

       LotSizeSquareFeet MiddleOrJuniorSchoolDistrict  \
0                    NaN                          NaN
1                    NaN                          NaN
2               177861.0                          NaN
3                 5300.0                          NaN
4                 9404.0                          NaN
...                  ...                          ...
524316          222156.0                          NaN
524317           14810.0                          NaN
524318           91040.4                          NaN
524319           37897.0                          NaN
524320         3445160.0                          NaN

                    UnparsedAddress.1  Year Month
0                     1045 N Azusa 61  2024     1
1                                 NaN  2024     1
2       2220 Avenue Of The Stars 2704  2024     1
3                        16 Palisades  2024     1
4                   1615 Waverly Road  2024     1
...                               ...   ...   ...
524316             1161 N Anza Street  2026     4
524317          33115 Evergreen Sreet  2026     4
524318            9860 Dale Avenue D2  2026     4
524319             Little Canyon Lane  2026     4
524320          9165 Intake Boulevard  2026     4

[524321 rows x 86 columns]>

In [7]:
cleaned_listings=all_listings_df[all_listings_df['PropertyType']=='Residential']
cleaned_listings.info()
display(cleaned_listings.head())

<class 'pandas.DataFrame'>
Index: 334336 entries, 2 to 524318
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             333883 non-null  float64
 1   ListingKey                    334336 non-null  int64
 2   ListAgentEmail                264550 non-null  str
 3   CloseDate                     84281 non-null   datetime64[us]
 4   ClosePrice                    69923 non-null   float64
 5   ListAgentFirstName            331657 non-null  str
 6   ListAgentLastName             334320 non-null  str
 7   Latitude                      256213 non-null  float64
 8   Longitude                     256213 non-null  float64
 9   UnparsedAddress               333850 non-null  str
 10  PropertyType                  334336 non-null  str
 11  LivingArea                    334002 non-null  float64
 12  ListPrice                     334336 non-null  float64
 13  DaysOnMarket                  334336 non-null  int64
 14  ListOfficeName                334336 non-null  str
 15  BuyerOfficeName               78101 non-null   str
 16  CoListOfficeName              74375 non-null   str
 17  ListAgentFullName             334303 non-null  str
 18  CoListAgentFirstName          74012 non-null   str
 19  CoListAgentLastName           74255 non-null   str
 20  BuyerAgentMlsId               79478 non-null   str
 21  BuyerAgentFirstName           79097 non-null   str
 22  BuyerAgentLastName            79522 non-null   str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       142937 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             334336 non-null  int64
 27  MLSAreaMajor                  289572 non-null  str
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                334336 non-null  str
 30  PropertyType.1                334336 non-null  str
 31  MlsStatus                     334336 non-null  str
 32  ElementarySchool              40639 non-null   str
 33  ListAgentFirstName.1          331657 non-null  str
 34  AttachedGarageYN              276245 non-null  object
 35  ParkingTotal                  334320 non-null  float64
 36  BuilderName                   15196 non-null   str
 37  PropertySubType               333597 non-null  str
 38  LotSizeAcres                  305826 non-null  float64
 39  SubdivisionName               122363 non-null  str
 40  BuyerOfficeAOR                73320 non-null   str
 41  YearBuilt                     333751 non-null  float64
 42  DaysOnMarket.1                334336 non-null  int64
 43  BuyerAgencyCompensationType   79013 non-null   str
 44  StreetNumberNumeric           333742 non-null  float64
 45  LivingArea.1                  334002 non-null  float64
 46  ListingId                     334336 non-null  str
 47  BathroomsTotalInteger         334298 non-null  float64
 48  City                          333942 non-null  str
 49  BuyerAgencyCompensation       78993 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             29628 non-null   float64
 52  BedroomsTotal                 334265 non-null  float64
 53  ContractStatusChangeDate      330199 non-null  str
 54  Longitude.1                   256213 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         7137 non-null    str
 57  PurchaseContractDate          157238 non-null  str
 58  ListingContractDate           334336 non-null  str
 59  BelowGradeFinishedArea        1780 non-null    float64
 60  BusinessType                  0 non-null       str
 61  Latitude.1                    256213 non-null  float64
 62  ListPrice.1                   334336 non-null  float64
 63  StateOrProvince               334292 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          40725 non-null   str
 66  FireplaceYN                   333996 non-null  object
 67  Stories                       273943 non-null  float64
 68  HighSchool                    53153 non-null   str
 69  Levels                        296356 non-null  str
 70  ListAgentLastName.1           334320 non-null  str
 71  CloseDate.1                   84281 non-null   str
 72  LotSizeDimensions             17372 non-null   str
 73  LotSizeArea                   306368 non-null  float64
 74  MainLevelBedrooms             181274 non-null  float64
 75  NewConstructionYN             311801 non-null  object
 76  GarageSpaces                  316063 non-null  float64
 77  HighSchoolDistrict            234748 non-null  str
 78  PostalCode                    334330 non-null  str
 79  BuyerOfficeName.1             78101 non-null   str
 80  AssociationFee                253581 non-null  float64
 81  LotSizeSquareFeet             306274 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             333850 non-null  str
 84  Year                          334336 non-null  int64
 85  Month                         334336 non-null  int64
dtypes: datetime64[us](1), float64(32), int64(6), object(3), str(44)
memory usage: 221.9+ MB

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month
2,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,NaN,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,3.0,Capistrano Unified,92677,NaN,254.00,5300.0,NaN,16 Palisades,2024,1
4,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024,1
5,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,4.0,Walnut Valley Unified,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road,2024,1
6,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,2.0,Newport Mesa Unified,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront,2024,1

In [8]:
before_r_list = all_listings_df.shape[0]
after_r_list = cleaned_listings.shape[0]

print(f"Row count before Residential filter: {before_r_list} rows")
print(f"Row count after Residential filter: {after_r_list} rows")
row_change = before_r_list - after_r_list
print(f"{row_change} rows were dropped after filtering for 'Residential' property only.")

Row count before Residential filter: 524321 rows
Row count after Residential filter: 334336 rows
189985 rows were dropped after filtering for 'Residential' property only.

In [9]:
cleaned_listings.to_csv("cleaned_listings.csv",index=True,encoding="utf-8-sig")

In [10]:
sold_dfs = []

for year in [2024, 2026]:
    for month in range(1, 13):
        fname = f"CRMLSSold{year}{month:02d}.csv"
        try:
            df = pd.read_csv(fname)
            df['Year'] = year
            df['Month'] = month
            sold_dfs.append(df)
        except FileNotFoundError:
            # Skip months that don't exist yet
            continue

# If you want one big DataFrame:
all_sold_df = pd.concat(sold_dfs, ignore_index=True)

/var/folders/lb/w22468fj03vf0vnvwqj9nf840000gn/T/ipykernel_4695/825790866.py:7: DtypeWarning: Columns (0: WaterfrontYN, 1: ElementarySchool, 2: BuilderName, 3: CoBuyerAgentFirstName, 4: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fname)
/var/folders/lb/w22468fj03vf0vnvwqj9nf840000gn/T/ipykernel_4695/825790866.py:7: DtypeWarning: Columns (0: WaterfrontYN, 1: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fname)

In [11]:
all_sold_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 351993 entries, 0 to 351992
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 278777 non-null  str
 1   ListAgentAOR                  284044 non-null  str
 2   Flooring                      206893 non-null  str
 3   ViewYN                        316945 non-null  object
 4   WaterfrontYN                  189 non-null     object
 5   BasementYN                    5783 non-null    object
 6   PoolPrivateYN                 304813 non-null  object
 7   OriginalListPrice             350996 non-null  float64
 8   ListingKey                    351993 non-null  int64
 9   ListAgentEmail                288535 non-null  str
 10  CloseDate                     351993 non-null  str
 11  ClosePrice                    351990 non-null  float64
 12  ListAgentFirstName            349757 non-null  str
 13  ListAgentLastName             351965 non-null  str
 14  Latitude                      332790 non-null  float64
 15  Longitude                     332957 non-null  float64
 16  UnparsedAddress               351428 non-null  str
 17  PropertyType                  351993 non-null  str
 18  LivingArea                    327578 non-null  float64
 19  ListPrice                     351496 non-null  float64
 20  DaysOnMarket                  351993 non-null  int64
 21  ListOfficeName                351993 non-null  str
 22  BuyerOfficeName               346993 non-null  str
 23  CoListOfficeName              71951 non-null   str
 24  ListAgentFullName             351908 non-null  str
 25  CoListAgentFirstName          71613 non-null   str
 26  CoListAgentLastName           71766 non-null   str
 27  BuyerAgentMlsId               351037 non-null  str
 28  BuyerAgentFirstName           350303 non-null  str
 29  BuyerAgentLastName            351809 non-null  str
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       104808 non-null  str
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             351993 non-null  int64
 34  MLSAreaMajor                  313319 non-null  str
 35  TaxAnnualAmount               1637 non-null    float64
 36  CountyOrParish                351993 non-null  str
 37  MlsStatus                     351993 non-null  str
 38  ElementarySchool              40195 non-null   str
 39  AttachedGarageYN              256189 non-null  object
 40  ParkingTotal                  340702 non-null  float64
 41  BuilderName                   13374 non-null   str
 42  PropertySubType               324850 non-null  str
 43  LotSizeAcres                  316723 non-null  float64
 44  SubdivisionName               123845 non-null  str
 45  BuyerOfficeAOR                336199 non-null  str
 46  YearBuilt                     337403 non-null  float64
 47  StreetNumberNumeric           351059 non-null  float64
 48  ListingId                     351993 non-null  str
 49  BathroomsTotalInteger         335914 non-null  float64
 50  City                          351684 non-null  str
 51  TaxYear                       211 non-null     float64
 52  BuildingAreaTotal             44419 non-null   float64
 53  BedroomsTotal                 328843 non-null  float64
 54  ContractStatusChangeDate      351281 non-null  str
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         28483 non-null   str
 57  PurchaseContractDate          344905 non-null  str
 58  ListingContractDate           351942 non-null  str
 59  BelowGradeFinishedArea        1448 non-null    float64
 60  BusinessType                  992 non-null     str
 61  StateOrProvince               351993 non-null  str
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          40485 non-null   str
 64  FireplaceYN                   321234 non-null  object
 65  Stories                       277799 non-null  float64
 66  HighSchool                    52517 non-null   str
 67  Levels                        299550 non-null  str
 68  LotSizeDimensions             17983 non-null   str
 69  LotSizeArea                   317882 non-null  float64
 70  MainLevelBedrooms             184395 non-null  float64
 71  NewConstructionYN             310366 non-null  object
 72  GarageSpaces                  307986 non-null  float64
 73  HighSchoolDistrict            236206 non-null  str
 74  PostalCode                    351886 non-null  object
 75  AssociationFee                242110 non-null  float64
 76  LotSizeSquareFeet             317615 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         80991 non-null   str
 79  OriginatingSystemSubName      80991 non-null   str
 80  Year                          351993 non-null  int64
 81  Month                         351993 non-null  int64
 82  BuyerAgencyCompensationType   67747 non-null   str
 83  BuyerAgencyCompensation       67780 non-null   float64
 84  latfilled                     77055 non-null   object
 85  lonfilled                     77055 non-null   object
dtypes: float64(28), int64(5), object(10), str(43)
memory usage: 231.0+ MB

In [12]:
print("Preview of Concatenated Sold DataFrame")
display(all_sold_df.head())

print("---------/--------")
print("All columns in DataFrame\n")
print(all_sold_df.columns)
print("---------/--------")
print("Description of DataFrame\n")
print(all_sold_df.describe)

before_shape = all_sold_df.shape

Preview of Concatenated Sold DataFrame

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,NaN,NaN,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,52320.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,217364.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,217800.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,108883.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN

---------/--------
All columns in DataFrame

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName', 'Year', 'Month',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='str')
---------/--------
Description of DataFrame

<bound method NDFrame.describe of                    BuyerAgentAOR              ListAgentAOR          Flooring  \
0                    Mlslistings               Mlslistings  Carpet,Tile,Wood
1                     HighDesert                HighDesert               NaN
2                   OrangeCounty              OrangeCounty               NaN
3                  InlandValleys             InlandValleys               NaN
4       SouthwestRiversideCounty  SouthwestRiversideCounty               NaN
...                          ...                       ...               ...
351988         SierraNorthValley         SierraNorthValley               NaN
351989  SouthwestRiversideCounty             InlandValleys               NaN
351990                     Mrmls                 Southland               NaN
351991              OrangeCounty                HighDesert               NaN
351992              CitrusValley              CitrusValley               NaN

       ViewYN WaterfrontYN BasementYN PoolPrivateYN  OriginalListPrice  \
0        True          NaN        NaN         False           499000.0
1         NaN          NaN        NaN           NaN                0.0
2        True          NaN        NaN           NaN            75000.0
3        True          NaN        NaN           NaN           199000.0
4        True          NaN        NaN           NaN            19500.0
...       ...          ...        ...           ...                ...
351988   True          NaN        NaN           NaN           200000.0
351989   True          NaN        NaN           NaN            97500.0
351990   True          NaN        NaN           NaN            15999.0
351991   True          NaN        NaN           NaN          6000000.0
351992  False          NaN        NaN         False                NaN

        ListingKey              ListAgentEmail  ... LotSizeSquareFeet  \
0        551985747       jwachter@cbnorcal.com  ...               NaN
1        535486633  eabrown@lee-associates.com  ...           52320.0
2        529986282             Joe@9WINWIN.com  ...          217364.0
3        529618166    carolthefinder@yahoo.com  ...          217800.0
4        522614340      jtavisola@tavisola.com  ...          108883.0
...            ...                         ...  ...               ...
351988  1014741959                         NaN  ...          910839.6
351989  1002540286                         NaN  ...          522720.0
351990   482785043                         NaN  ...           20009.0
351991   446619807                         NaN  ...          122839.0
351992   431883449                         NaN  ...           21780.0

        MiddleOrJuniorSchoolDistrict OriginatingSystemName  \
0                                NaN                 CRMLS
1                                NaN                 CRMLS
2                                NaN                 CRMLS
3                                NaN                 CRMLS
4                                NaN                 CRMLS
...                              ...                   ...
351988                           NaN                 CRMLS
351989                           NaN                 CRMLS
351990                           NaN                 CRMLS
351991                           NaN                 CRMLS
351992                           NaN                 CRMLS

       OriginatingSystemSubName  Year  Month BuyerAgencyCompensationType  \
0                    CRMLS_MLSL  2024      1                         NaN
1                     CRMLS_CRM  2024      1                         NaN
2                     CRMLS_CRM  2024      1                         NaN
3                     CRMLS_CRM  2024      1                         NaN
4                     CRMLS_CRM  2024      1                         NaN
...                         ...   ...    ...                         ...
351988                CRMLS_CRM  2026      4                         NaN
351989                CRMLS_CRM  2026      4                         NaN
351990                CRMLS_CRM  2026      4                         NaN
351991                CRMLS_CRM  2026      4                         NaN
351992                CRMLS_CRM  2026      4                         NaN

       BuyerAgencyCompensation  latfilled  lonfilled
0                          NaN        NaN        NaN
1                          NaN        NaN        NaN
2                          NaN        NaN        NaN
3                          NaN        NaN        NaN
4                          NaN        NaN        NaN
...                        ...        ...        ...
351988                     NaN        NaN        NaN
351989                     NaN        NaN        NaN
351990                     NaN        NaN        NaN
351991                     NaN        NaN        NaN
351992                     NaN        NaN        NaN

[351993 rows x 86 columns]>

In [13]:
prop_type = all_sold_df['PropertyType'].unique()
print(f"Unique Property Types: {prop_type}")

Unique Property Types: <StringArray>
[        'Residential',     'CommercialLease',                'Land',
    'ResidentialLease',  'ManufacturedInPark',   'ResidentialIncome',
      'CommercialSale', 'BusinessOpportunity']
Length: 8, dtype: str

In [14]:
residential_sold_df=all_sold_df[all_sold_df['PropertyType']=='Residential']
residential_sold_df.info()
display(residential_sold_df.tail())

after_shape = residential_sold_df.shape

<class 'pandas.DataFrame'>
Index: 238304 entries, 0 to 351974
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 187730 non-null  str
 1   ListAgentAOR                  192138 non-null  str
 2   Flooring                      152584 non-null  str
 3   ViewYN                        218173 non-null  object
 4   WaterfrontYN                  143 non-null     object
 5   BasementYN                    4608 non-null    object
 6   PoolPrivateYN                 215080 non-null  object
 7   OriginalListPrice             237864 non-null  float64
 8   ListingKey                    238304 non-null  int64
 9   ListAgentEmail                196025 non-null  str
 10  CloseDate                     238304 non-null  str
 11  ClosePrice                    238302 non-null  float64
 12  ListAgentFirstName            236350 non-null  str
 13  ListAgentLastName             238289 non-null  str
 14  Latitude                      222389 non-null  float64
 15  Longitude                     222389 non-null  float64
 16  UnparsedAddress               238072 non-null  str
 17  PropertyType                  238304 non-null  str
 18  LivingArea                    238173 non-null  float64
 19  ListPrice                     238304 non-null  float64
 20  DaysOnMarket                  238304 non-null  int64
 21  ListOfficeName                238304 non-null  str
 22  BuyerOfficeName               233801 non-null  str
 23  CoListOfficeName              54077 non-null   str
 24  ListAgentFullName             238261 non-null  str
 25  CoListAgentFirstName          53815 non-null   str
 26  CoListAgentLastName           53959 non-null   str
 27  BuyerAgentMlsId               238018 non-null  str
 28  BuyerAgentFirstName           237035 non-null  str
 29  BuyerAgentLastName            238203 non-null  str
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       99363 non-null   str
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             238304 non-null  int64
 34  MLSAreaMajor                  206783 non-null  str
 35  TaxAnnualAmount               0 non-null       float64
 36  CountyOrParish                238304 non-null  str
 37  MlsStatus                     238304 non-null  str
 38  ElementarySchool              32542 non-null   str
 39  AttachedGarageYN              202651 non-null  object
 40  ParkingTotal                  237879 non-null  float64
 41  BuilderName                   11557 non-null   str
 42  PropertySubType               237870 non-null  str
 43  LotSizeAcres                  218268 non-null  float64
 44  SubdivisionName               87861 non-null   str
 45  BuyerOfficeAOR                224867 non-null  str
 46  YearBuilt                     238091 non-null  float64
 47  StreetNumberNumeric           238025 non-null  float64
 48  ListingId                     238304 non-null  str
 49  BathroomsTotalInteger         238261 non-null  float64
 50  City                          238080 non-null  str
 51  TaxYear                       0 non-null       float64
 52  BuildingAreaTotal             16173 non-null   float64
 53  BedroomsTotal                 238297 non-null  float64
 54  ContractStatusChangeDate      237715 non-null  str
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         21536 non-null   str
 57  PurchaseContractDate          238123 non-null  str
 58  ListingContractDate           238303 non-null  str
 59  BelowGradeFinishedArea        1258 non-null    float64
 60  BusinessType                  0 non-null       str
 61  StateOrProvince               238304 non-null  str
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          32787 non-null   str
 64  FireplaceYN                   238128 non-null  object
 65  Stories                       198251 non-null  float64
 66  HighSchool                    42345 non-null   str
 67  Levels                        211809 non-null  str
 68  LotSizeDimensions             11265 non-null   str
 69  LotSizeArea                   218583 non-null  float64
 70  MainLevelBedrooms             136022 non-null  float64
 71  NewConstructionYN             221021 non-null  object
 72  GarageSpaces                  228496 non-null  float64
 73  HighSchoolDistrict            173874 non-null  str
 74  PostalCode                    238304 non-null  object
 75  AssociationFee                182586 non-null  float64
 76  LotSizeSquareFeet             218519 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         53172 non-null   str
 79  OriginatingSystemSubName      53172 non-null   str
 80  Year                          238304 non-null  int64
 81  Month                         238304 non-null  int64
 82  BuyerAgencyCompensationType   46136 non-null   str
 83  BuyerAgencyCompensation       46125 non-null   float64
 84  latfilled                     52908 non-null   object
 85  lonfilled                     52908 non-null   object
dtypes: float64(28), int64(5), object(10), str(43)
memory usage: 158.2+ MB

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
351961,LakeCounty,LakeCounty,NaN,True,NaN,True,False,279000.0,1069708148,NaN,...,10019.0,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN
351963,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,NaN,True,False,449000.0,1067010583,NaN,...,12096.0,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN
351966,SanDiego,TriCounties,Vinyl,True,NaN,NaN,False,1579000.0,1063196193,NaN,...,859874.4,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN
351967,Mrmls,OrangeCounty,NaN,True,NaN,NaN,False,855000.0,1062106215,NaN,...,2733.0,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN
351974,Southland,PacificWest,"Carpet,Vinyl",False,NaN,NaN,False,375000.0,1052387780,NaN,...,23878.0,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN

In [15]:
# Change in rows
print(f"Row count before Residential filter: {before_shape[0]} rows")
print(f"Row count after Residential filter: {after_shape[0]} rows")
row_change = before_shape[0] - after_shape[0]
print(f"{row_change} rows were dropped after filtering for 'Residential' property only.")

Row count before Residential filter: 351993 rows
Row count after Residential filter: 238304 rows
113689 rows were dropped after filtering for 'Residential' property only.

In [16]:
completedness_count = pd.DataFrame(
    residential_sold_df.isnull().sum()
).reset_index()
completedness_count.columns = ["Column Name", "count"]
completedness_count = completedness_count.sort_values(by='count',ascending=False)

display(completedness_count)

completedness_pct = pd.DataFrame(residential_sold_df.isnull().mean()).reset_index()
completedness_pct.columns = ["Column Name","pct"]

                 Column Name   count
32    AboveGradeFinishedArea  238304
35           TaxAnnualAmount  238304
30           FireplacesTotal  238304
51                   TaxYear  238304
55  ElementarySchoolDistrict  238304
..                       ...     ...
81                     Month       0
48                 ListingId       0
37                 MlsStatus       0
36            CountyOrParish       0
17              PropertyType       0

[86 rows x 2 columns]

In [17]:
flagged_columns = completedness_pct[completedness_pct['pct']>=0.9].sort_values(by='pct',ascending=False).reset_index(drop=True)
display(flagged_columns)

lst_flagged = flagged_columns["Column Name"].to_list()
print(lst_flagged)

                     Column Name       pct
0                FireplacesTotal  1.000000
1         AboveGradeFinishedArea  1.000000
2                TaxAnnualAmount  1.000000
3                        TaxYear  1.000000
4       ElementarySchoolDistrict  1.000000
5                   BusinessType  1.000000
6                  CoveredSpaces  1.000000
7   MiddleOrJuniorSchoolDistrict  1.000000
8                   WaterfrontYN  0.999400
9         BelowGradeFinishedArea  0.994721
10                    BasementYN  0.980663
11             LotSizeDimensions  0.952728
12                   BuilderName  0.951503
13             BuildingAreaTotal  0.932133
14         CoBuyerAgentFirstName  0.909628

['FireplacesTotal', 'AboveGradeFinishedArea', 'TaxAnnualAmount', 'TaxYear', 'ElementarySchoolDistrict', 'BusinessType', 'CoveredSpaces', 'MiddleOrJuniorSchoolDistrict', 'WaterfrontYN', 'BelowGradeFinishedArea', 'BasementYN', 'LotSizeDimensions', 'BuilderName', 'BuildingAreaTotal', 'CoBuyerAgentFirstName']

In [18]:
cleaned_sold = residential_sold_df.drop(columns=lst_flagged)

print(f"Number of Columns before filtering out flagged columns: {len(all_sold_df.columns.to_list())} columns.")
print(f"Number of Columns after filtering out flagged columns: {len(cleaned_sold.columns.to_list())} columns.")
print(f"{len(lst_flagged)} columns are removed due to high percentage of missing values.")

Number of Columns before filtering out flagged columns: 86 columns.
Number of Columns after filtering out flagged columns: 71 columns.
15 columns are removed due to high percentage of missing values.

In [19]:
#Summary table for ClosePrice, LivingArea, and DaysOnMarket
cols = ["ClosePrice","LivingArea","DaysOnMarket"]

summary = cleaned_sold[cols].agg([
    "min","max","mean","median",
    lambda x: x.quantile(0.25),
    lambda x: x.quantile(0.75),
    lambda x: x.quantile(0.90),
    lambda x: x.quantile(0.95)
])

summary.index = ["min", "max", "mean", "median", "p25", "p75", "p90", "p95"]

display(summary.T)

,min,max,mean,median,p25,p75,p90,p95
ClosePrice,1.15,796000000.0,1.157467e+06,825000.0,577000.0,1300000.0,2075000.0,2850000.0
LivingArea,0.00,123764.0,1.854871e+03,1636.0,1245.0,2209.0,2959.0,3532.0
DaysOnMarket,-84.00,12430.0,3.396844e+01,16.0,7.0,43.0,85.0,122.0

In [20]:
cleaned_sold.to_csv("cleaned_sold.csv",index=True,encoding="utf-8-sig")

In [21]:
# Combining FRED data
mortgage

#Resample

mortgage['year_month'] = mortgage['date'].dt.to_period('M')

monthly_mortgage = mortgage.groupby('year_month')["rate_30yr_fixed"].mean().reset_index()

display(monthly_mortgage)

    year_month  rate_30yr_fixed
0      1971-04           7.3100
1      1971-05           7.4250
2      1971-06           7.5300
3      1971-07           7.6040
4      1971-08           7.6975
..         ...              ...
657    2026-01           6.1025
658    2026-02           6.0475
659    2026-03           6.1775
660    2026-04           6.3320
661    2026-05           6.3700

[662 rows x 2 columns]

In [22]:
#Re-format date columns for Sold and Listing DFs

cleaned_sold["year_month"] = pd.to_datetime(cleaned_sold["CloseDate"]).dt.to_period("M")

cleaned_listings['year_month'] = pd.to_datetime(cleaned_listings['ListingContractDate']).dt.to_period('M')

In [23]:
sold_w_rates = cleaned_sold.merge(monthly_mortgage,on="year_month",how="left").reset_index(drop=True)

listing_w_rates = cleaned_listings.merge(monthly_mortgage,on="year_month",how="left").reset_index(drop=True)

display(sold_w_rates.head())
display(listing_w_rates.head())

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,CRMLS,CRMLS_SAND,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,CRMLS,CRMLS_SAND,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month,year_month,rate_30yr_fixed
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1,2024-01,6.6425
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,92677,NaN,254.00,5300.0,NaN,16 Palisades,2024,1,2024-01,6.6425
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024,1,2024-01,6.6425
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road,2024,1,2024-01,6.6425
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront,2024,1,2024-01,6.6425

In [24]:
print(sold_w_rates['rate_30yr_fixed'].isnull().sum())
print(listing_w_rates['rate_30yr_fixed'].isnull().sum())

display(sold_w_rates[['CloseDate','year_month','ClosePrice','rate_30yr_fixed']].head())

0
0

    CloseDate year_month  ClosePrice  rate_30yr_fixed
0  2024-01-26    2024-01    240000.0           6.6425
1  2024-01-05    2024-01    815000.0           6.6425
2  2024-01-05    2024-01    810000.0           6.6425
3  2024-01-30    2024-01    858000.0           6.6425
4  2024-01-29    2024-01   1890500.0           6.6425

In [25]:
# Convert file to CSV format
sold_w_rates.to_csv('enriched_sold.csv',index=True,encoding='utf-8-sig')
listing_w_rates.to_csv('enriched_listing.csv',index=True,encoding='utf-8-sig')

In [26]:
# Re-read 'enriched_sold.csv' with correct date format
enriched_sold = pd.read_csv('enriched_sold.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])
enriched_sold.info()

/var/folders/lb/w22468fj03vf0vnvwqj9nf840000gn/T/ipykernel_4695/1178815760.py:2: DtypeWarning: Columns (0: ListAgentAOR, 1: Flooring, 2: CloseDate, 3: Stories, 4: OriginatingSystemSubName, 5: Year, 6: BuyerAgencyCompensation, 7: lonfilled, 8: year_month) have mixed types. Specify dtype option on import or set low_memory=False.
  enriched_sold = pd.read_csv('enriched_sold.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])

<class 'pandas.DataFrame'>
RangeIndex: 238304 entries, 0 to 238303
Data columns (total 73 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   BuyerAgentAOR                187730 non-null  str
 1   ListAgentAOR                 192138 non-null  str
 2   Flooring                     152584 non-null  str
 3   ViewYN                       218173 non-null  object
 4   PoolPrivateYN                215080 non-null  object
 5   OriginalListPrice            237864 non-null  float64
 6   ListingKey                   238304 non-null  int64
 7   ListAgentEmail               196025 non-null  str
 8   CloseDate                    238304 non-null  datetime64[us]
 9   ClosePrice                   238302 non-null  float64
 10  ListAgentFirstName           236350 non-null  str
 11  ListAgentLastName            238289 non-null  str
 12  Latitude                     222389 non-null  float64
 13  Longitude                    222389 non-null  float64
 14  UnparsedAddress              238072 non-null  str
 15  PropertyType                 238304 non-null  str
 16  LivingArea                   238173 non-null  float64
 17  ListPrice                    238304 non-null  float64
 18  DaysOnMarket                 238304 non-null  int64
 19  ListOfficeName               238304 non-null  str
 20  BuyerOfficeName              233801 non-null  str
 21  CoListOfficeName             54077 non-null   str
 22  ListAgentFullName            238261 non-null  str
 23  CoListAgentFirstName         53815 non-null   str
 24  CoListAgentLastName          53959 non-null   str
 25  BuyerAgentMlsId              238018 non-null  str
 26  BuyerAgentFirstName          237035 non-null  str
 27  BuyerAgentLastName           238203 non-null  str
 28  AssociationFeeFrequency      99363 non-null   str
 29  ListingKeyNumeric            238304 non-null  int64
 30  MLSAreaMajor                 206783 non-null  str
 31  CountyOrParish               238304 non-null  str
 32  MlsStatus                    238304 non-null  str
 33  ElementarySchool             32542 non-null   str
 34  AttachedGarageYN             202651 non-null  object
 35  ParkingTotal                 237879 non-null  float64
 36  PropertySubType              237870 non-null  str
 37  LotSizeAcres                 218268 non-null  float64
 38  SubdivisionName              87861 non-null   str
 39  BuyerOfficeAOR               224867 non-null  str
 40  YearBuilt                    238091 non-null  float64
 41  StreetNumberNumeric          238025 non-null  float64
 42  ListingId                    238304 non-null  str
 43  BathroomsTotalInteger        238261 non-null  float64
 44  City                         238080 non-null  str
 45  BedroomsTotal                238297 non-null  float64
 46  ContractStatusChangeDate     237715 non-null  datetime64[us]
 47  PurchaseContractDate         238123 non-null  datetime64[us]
 48  ListingContractDate          238303 non-null  datetime64[us]
 49  StateOrProvince              238304 non-null  str
 50  MiddleOrJuniorSchool         32787 non-null   str
 51  FireplaceYN                  238128 non-null  object
 52  Stories                      198251 non-null  float64
 53  HighSchool                   42345 non-null   str
 54  Levels                       211809 non-null  str
 55  LotSizeArea                  218583 non-null  float64
 56  MainLevelBedrooms            136022 non-null  float64
 57  NewConstructionYN            221021 non-null  object
 58  GarageSpaces                 228496 non-null  float64
 59  HighSchoolDistrict           173874 non-null  str
 60  PostalCode                   238304 non-null  str
 61  AssociationFee               182586 non-null  float64
 62  LotSizeSquareFeet            218519 non-null  float64
 63  OriginatingSystemName        53172 non-null   str
 64  OriginatingSystemSubName     53172 non-null   str
 65  Year                         238304 non-null  int64
 66  Month                        238304 non-null  int64
 67  BuyerAgencyCompensationType  46136 non-null   str
 68  BuyerAgencyCompensation      46125 non-null   float64
 69  latfilled                    52908 non-null   object
 70  lonfilled                    52908 non-null   object
 71  year_month                   238304 non-null  str
 72  rate_30yr_fixed              238304 non-null  float64
dtypes: datetime64[us](4), float64(20), int64(5), object(7), str(37)
memory usage: 132.7+ MB

In [27]:
# Re-read 'enriched_listings.csv' with correct date format
enriched_listing = pd.read_csv('enriched_listing.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])
enriched_listing.info()

/var/folders/lb/w22468fj03vf0vnvwqj9nf840000gn/T/ipykernel_4695/2771643693.py:2: DtypeWarning: Columns (0: CloseDate, 1: StreetNumberNumeric) have mixed types. Specify dtype option on import or set low_memory=False.
  enriched_listing = pd.read_csv('enriched_listing.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])

<class 'pandas.DataFrame'>
RangeIndex: 334336 entries, 0 to 334335
Data columns (total 88 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             333883 non-null  float64
 1   ListingKey                    334336 non-null  int64
 2   ListAgentEmail                264550 non-null  str
 3   CloseDate                     84281 non-null   datetime64[us]
 4   ClosePrice                    69923 non-null   float64
 5   ListAgentFirstName            331657 non-null  str
 6   ListAgentLastName             334320 non-null  str
 7   Latitude                      256213 non-null  float64
 8   Longitude                     256213 non-null  float64
 9   UnparsedAddress               333850 non-null  str
 10  PropertyType                  334336 non-null  str
 11  LivingArea                    334002 non-null  float64
 12  ListPrice                     334336 non-null  float64
 13  DaysOnMarket                  334336 non-null  int64
 14  ListOfficeName                334336 non-null  str
 15  BuyerOfficeName               78101 non-null   str
 16  CoListOfficeName              74375 non-null   str
 17  ListAgentFullName             334303 non-null  str
 18  CoListAgentFirstName          74012 non-null   str
 19  CoListAgentLastName           74255 non-null   str
 20  BuyerAgentMlsId               79478 non-null   str
 21  BuyerAgentFirstName           79097 non-null   str
 22  BuyerAgentLastName            79522 non-null   str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       142937 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             334336 non-null  int64
 27  MLSAreaMajor                  289572 non-null  str
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                334336 non-null  str
 30  PropertyType.1                334336 non-null  str
 31  MlsStatus                     334336 non-null  str
 32  ElementarySchool              40639 non-null   str
 33  ListAgentFirstName.1          331657 non-null  str
 34  AttachedGarageYN              276245 non-null  object
 35  ParkingTotal                  334320 non-null  float64
 36  BuilderName                   15196 non-null   str
 37  PropertySubType               333597 non-null  str
 38  LotSizeAcres                  305826 non-null  float64
 39  SubdivisionName               122363 non-null  str
 40  BuyerOfficeAOR                73320 non-null   str
 41  YearBuilt                     333751 non-null  float64
 42  DaysOnMarket.1                334336 non-null  int64
 43  BuyerAgencyCompensationType   79013 non-null   str
 44  StreetNumberNumeric           333742 non-null  float64
 45  LivingArea.1                  334002 non-null  float64
 46  ListingId                     334336 non-null  str
 47  BathroomsTotalInteger         334298 non-null  float64
 48  City                          333942 non-null  str
 49  BuyerAgencyCompensation       78993 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             29628 non-null   float64
 52  BedroomsTotal                 334265 non-null  float64
 53  ContractStatusChangeDate      330199 non-null  datetime64[us]
 54  Longitude.1                   256213 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         7137 non-null    str
 57  PurchaseContractDate          157238 non-null  datetime64[us]
 58  ListingContractDate           334336 non-null  datetime64[us]
 59  BelowGradeFinishedArea        1780 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    256213 non-null  float64
 62  ListPrice.1                   334336 non-null  float64
 63  StateOrProvince               334292 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          40725 non-null   str
 66  FireplaceYN                   333996 non-null  object
 67  Stories                       273943 non-null  float64
 68  HighSchool                    53153 non-null   str
 69  Levels                        296356 non-null  str
 70  ListAgentLastName.1           334320 non-null  str
 71  CloseDate.1                   84281 non-null   str
 72  LotSizeDimensions             17372 non-null   str
 73  LotSizeArea                   306368 non-null  float64
 74  MainLevelBedrooms             181274 non-null  float64
 75  NewConstructionYN             311801 non-null  object
 76  GarageSpaces                  316063 non-null  float64
 77  HighSchoolDistrict            234748 non-null  str
 78  PostalCode                    334330 non-null  str
 79  BuyerOfficeName.1             78101 non-null   str
 80  AssociationFee                253581 non-null  float64
 81  LotSizeSquareFeet             306274 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             333850 non-null  str
 84  Year                          334336 non-null  int64
 85  Month                         334336 non-null  int64
 86  year_month                    334336 non-null  str
 87  rate_30yr_fixed               334336 non-null  float64
dtypes: datetime64[us](4), float64(34), int64(6), object(3), str(41)
memory usage: 224.5+ MB

In [28]:
# Checking if date follows the correct order

# Check if listing is after close

def list_after_close(listing_date,close_date):
    return listing_date > close_date # True = faulty value, False = correct value

def purchase_after_close(purchase_date,close_date):
    return purchase_date > close_date # True = faulty value, False = correct value


enriched_sold['list_after_close_flag']= enriched_sold.apply(
    lambda row: list_after_close(row['ListingContractDate'],row['CloseDate']),
                axis=1
)

enriched_sold['purchase_after_close_flag']=enriched_sold.apply(
    lambda row: purchase_after_close(row['PurchaseContractDate'],row['CloseDate']),
    axis=1
)

In [29]:
enriched_sold['negative_timeline_flag'] = (
    enriched_sold['list_after_close_flag'] | enriched_sold['purchase_after_close_flag']
)

enriched_sold_postimeline = enriched_sold[enriched_sold['negative_timeline_flag']==False].copy()
print(enriched_sold_postimeline.info())
display(enriched_sold_postimeline.head())

<class 'pandas.DataFrame'>
Index: 238126 entries, 0 to 238303
Data columns (total 76 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   BuyerAgentAOR                187609 non-null  str
 1   ListAgentAOR                 192016 non-null  str
 2   Flooring                     152519 non-null  str
 3   ViewYN                       217995 non-null  object
 4   PoolPrivateYN                215036 non-null  object
 5   OriginalListPrice            237804 non-null  float64
 6   ListingKey                   238126 non-null  int64
 7   ListAgentEmail               195856 non-null  str
 8   CloseDate                    238126 non-null  datetime64[us]
 9   ClosePrice                   238124 non-null  float64
 10  ListAgentFirstName           236189 non-null  str
 11  ListAgentLastName            238111 non-null  str
 12  Latitude                     222275 non-null  float64
 13  Longitude                    222275 non-null  float64
 14  UnparsedAddress              237894 non-null  str
 15  PropertyType                 238126 non-null  str
 16  LivingArea                   237995 non-null  float64
 17  ListPrice                    238126 non-null  float64
 18  DaysOnMarket                 238126 non-null  int64
 19  ListOfficeName               238126 non-null  str
 20  BuyerOfficeName              233636 non-null  str
 21  CoListOfficeName             54041 non-null   str
 22  ListAgentFullName            238083 non-null  str
 23  CoListAgentFirstName         53780 non-null   str
 24  CoListAgentLastName          53924 non-null   str
 25  BuyerAgentMlsId              237841 non-null  str
 26  BuyerAgentFirstName          236869 non-null  str
 27  BuyerAgentLastName           238025 non-null  str
 28  AssociationFeeFrequency      99323 non-null   str
 29  ListingKeyNumeric            238126 non-null  int64
 30  MLSAreaMajor                 206608 non-null  str
 31  CountyOrParish               238126 non-null  str
 32  MlsStatus                    238126 non-null  str
 33  ElementarySchool             32522 non-null   str
 34  AttachedGarageYN             202494 non-null  object
 35  ParkingTotal                 237701 non-null  float64
 36  PropertySubType              237692 non-null  str
 37  LotSizeAcres                 218116 non-null  float64
 38  SubdivisionName              87841 non-null   str
 39  BuyerOfficeAOR               224705 non-null  str
 40  YearBuilt                    237913 non-null  float64
 41  StreetNumberNumeric          237847 non-null  float64
 42  ListingId                    238126 non-null  str
 43  BathroomsTotalInteger        238083 non-null  float64
 44  City                         237904 non-null  str
 45  BedroomsTotal                238119 non-null  float64
 46  ContractStatusChangeDate     237537 non-null  datetime64[us]
 47  PurchaseContractDate         237945 non-null  datetime64[us]
 48  ListingContractDate          238125 non-null  datetime64[us]
 49  StateOrProvince              238126 non-null  str
 50  MiddleOrJuniorSchool         32768 non-null   str
 51  FireplaceYN                  237950 non-null  object
 52  Stories                      198220 non-null  float64
 53  HighSchool                   42327 non-null   str
 54  Levels                       211774 non-null  str
 55  LotSizeArea                  218431 non-null  float64
 56  MainLevelBedrooms            136021 non-null  float64
 57  NewConstructionYN            220846 non-null  object
 58  GarageSpaces                 228328 non-null  float64
 59  HighSchoolDistrict           173731 non-null  str
 60  PostalCode                   238126 non-null  str
 61  AssociationFee               182530 non-null  float64
 62  LotSizeSquareFeet            218367 non-null  float64
 63  OriginatingSystemName        53150 non-null   str
 64  OriginatingSystemSubName     53150 non-null   str
 65  Year                         238126 non-null  int64
 66  Month                        238126 non-null  int64
 67  BuyerAgencyCompensationType  46080 non-null   str
 68  BuyerAgencyCompensation      46069 non-null   float64
 69  latfilled                    52866 non-null   object
 70  lonfilled                    52866 non-null   object
 71  year_month                   238126 non-null  str
 72  rate_30yr_fixed              238126 non-null  float64
 73  list_after_close_flag        238126 non-null  bool
 74  purchase_after_close_flag    238126 non-null  bool
 75  negative_timeline_flag       238126 non-null  bool
dtypes: bool(3), datetime64[us](4), float64(20), int64(5), object(7), str(37)
memory usage: 135.1+ MB
None

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
5,NorthSanLuisObispo,NorthSanLuisObispo,NaN,True,False,2100000.0,1067652762,jenniferarielkennedy@gmail.com,2024-01-02,2100000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False

In [30]:
enriched_listing['list_after_close_flag']= enriched_listing.apply(
    lambda row: list_after_close(row['ListingContractDate'],row['CloseDate']),
                axis=1
)

enriched_listing['purchase_after_close_flag']=enriched_listing.apply(
    lambda row: purchase_after_close(row['PurchaseContractDate'],row['CloseDate']),
    axis=1
)

In [31]:
enriched_listing['negative_timeline_flag'] = (
    enriched_listing['list_after_close_flag'] | enriched_listing['purchase_after_close_flag']
)
enriched_listing_postimeline = enriched_listing[enriched_listing['negative_timeline_flag']==False].copy()
print(enriched_listing_postimeline.info())
display(enriched_listing_postimeline.head())

<class 'pandas.DataFrame'>
Index: 334132 entries, 0 to 334335
Data columns (total 91 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             333807 non-null  float64
 1   ListingKey                    334132 non-null  int64
 2   ListAgentEmail                264355 non-null  str
 3   CloseDate                     84077 non-null   datetime64[us]
 4   ClosePrice                    69731 non-null   float64
 5   ListAgentFirstName            331470 non-null  str
 6   ListAgentLastName             334116 non-null  str
 7   Latitude                      256130 non-null  float64
 8   Longitude                     256130 non-null  float64
 9   UnparsedAddress               333646 non-null  str
 10  PropertyType                  334132 non-null  str
 11  LivingArea                    333799 non-null  float64
 12  ListPrice                     334132 non-null  float64
 13  DaysOnMarket                  334132 non-null  int64
 14  ListOfficeName                334132 non-null  str
 15  BuyerOfficeName               77911 non-null   str
 16  CoListOfficeName              74338 non-null   str
 17  ListAgentFullName             334099 non-null  str
 18  CoListAgentFirstName          73976 non-null   str
 19  CoListAgentLastName           74219 non-null   str
 20  BuyerAgentMlsId               79274 non-null   str
 21  BuyerAgentFirstName           78905 non-null   str
 22  BuyerAgentLastName            79318 non-null   str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       142892 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             334132 non-null  int64
 27  MLSAreaMajor                  289382 non-null  str
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                334132 non-null  str
 30  PropertyType.1                334132 non-null  str
 31  MlsStatus                     334132 non-null  str
 32  ElementarySchool              40617 non-null   str
 33  ListAgentFirstName.1          331470 non-null  str
 34  AttachedGarageYN              276061 non-null  object
 35  ParkingTotal                  334116 non-null  float64
 36  BuilderName                   15196 non-null   str
 37  PropertySubType               333393 non-null  str
 38  LotSizeAcres                  305650 non-null  float64
 39  SubdivisionName               122331 non-null  str
 40  BuyerOfficeAOR                73134 non-null   str
 41  YearBuilt                     333548 non-null  float64
 42  DaysOnMarket.1                334132 non-null  int64
 43  BuyerAgencyCompensationType   78941 non-null   str
 44  StreetNumberNumeric           333538 non-null  float64
 45  LivingArea.1                  333799 non-null  float64
 46  ListingId                     334132 non-null  str
 47  BathroomsTotalInteger         334094 non-null  float64
 48  City                          333740 non-null  str
 49  BuyerAgencyCompensation       78921 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             29615 non-null   float64
 52  BedroomsTotal                 334061 non-null  float64
 53  ContractStatusChangeDate      329995 non-null  datetime64[us]
 54  Longitude.1                   256130 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         7116 non-null    str
 57  PurchaseContractDate          157034 non-null  datetime64[us]
 58  ListingContractDate           334132 non-null  datetime64[us]
 59  BelowGradeFinishedArea        1780 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    256130 non-null  float64
 62  ListPrice.1                   334132 non-null  float64
 63  StateOrProvince               334088 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          40704 non-null   str
 66  FireplaceYN                   333792 non-null  object
 67  Stories                       273901 non-null  float64
 68  HighSchool                    53132 non-null   str
 69  Levels                        296308 non-null  str
 70  ListAgentLastName.1           334116 non-null  str
 71  CloseDate.1                   84077 non-null   str
 72  LotSizeDimensions             17365 non-null   str
 73  LotSizeArea                   306192 non-null  float64
 74  MainLevelBedrooms             181273 non-null  float64
 75  NewConstructionYN             311604 non-null  object
 76  GarageSpaces                  315867 non-null  float64
 77  HighSchoolDistrict            234590 non-null  str
 78  PostalCode                    334126 non-null  str
 79  BuyerOfficeName.1             77911 non-null   str
 80  AssociationFee                253517 non-null  float64
 81  LotSizeSquareFeet             306098 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             333646 non-null  str
 84  Year                          334132 non-null  int64
 85  Month                         334132 non-null  int64
 86  year_month                    334132 non-null  str
 87  rate_30yr_fixed               334132 non-null  float64
 88  list_after_close_flag         334132 non-null  bool
 89  purchase_after_close_flag     334132 non-null  bool
 90  negative_timeline_flag        334132 non-null  bool
dtypes: bool(3), datetime64[us](4), float64(34), int64(6), object(3), str(41)
memory usage: 227.8+ MB
None

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1,2024-01,6.6425,False,False,False
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,5300.0,NaN,16 Palisades,2024,1,2024-01,6.6425,False,False,False
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,9404.0,NaN,1615 Waverly Road,2024,1,2024-01,6.6425,False,False,False
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,58232.0,NaN,2250 Indian Creek Road,2024,1,2024-01,6.6425,False,False,False
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,2250.0,NaN,317 E. Bayfront,2024,1,2024-01,6.6425,False,False,False

In [32]:
# Checking Longtitude & Latitude for valid format
enriched_listing_postimeline['Latitude']=pd.to_numeric(enriched_listing_postimeline['Latitude'],errors='coerce')
enriched_listing_postimeline['Longitude']=pd.to_numeric(enriched_listing_postimeline['Longitude'],errors='coerce')

enriched_sold_postimeline['Latitude']=pd.to_numeric(enriched_sold_postimeline['Latitude'],errors='coerce')
enriched_sold_postimeline['Longitude']=pd.to_numeric(enriched_sold_postimeline['Longitude'],errors='coerce')

def check_coord(longitude,latitude):
    if not pd.isna(longitude) and not pd.isna(latitude):
        if (longitude < 0) and (latitude != 0):
            if (32.5 <= latitude <= 42.0) and (-124.5 <= longitude <= -114.0):
                return True # True = coordinate is valid and pass all checks
    return False
            
enriched_listing_postimeline['correct_coord'] = enriched_listing_postimeline.apply(
    lambda row: check_coord(row['Longitude'],row['Latitude']),
    axis=1
)

enriched_sold_postimeline['correct_coord'] = enriched_sold_postimeline.apply(
    lambda row: check_coord(row['Longitude'],row['Latitude']),
    axis=1
)

In [33]:
print('Correct Coordinates Value Counts for Sold Data\n')
print(enriched_sold_postimeline['correct_coord'].value_counts())
print('\nCorrect Coordinates Value Counts for Listing Data\n')
print(enriched_listing_postimeline['correct_coord'].value_counts())

Correct Coordinates Value Counts for Sold Data

correct_coord
True     222233
False     15893
Name: count, dtype: int64

Correct Coordinates Value Counts for Listing Data

correct_coord
True     255935
False     78197
Name: count, dtype: int64

In [34]:
enriched_sold_v3 = enriched_sold_postimeline[enriched_sold_postimeline['correct_coord']==True]
print(enriched_sold_v3.info())
display(enriched_sold_v3.head())

<class 'pandas.DataFrame'>
Index: 222233 entries, 4 to 238303
Data columns (total 77 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   BuyerAgentAOR                184454 non-null  str
 1   ListAgentAOR                 188782 non-null  str
 2   Flooring                     141418 non-null  str
 3   ViewYN                       206658 non-null  object
 4   PoolPrivateYN                204186 non-null  object
 5   OriginalListPrice            221991 non-null  float64
 6   ListingKey                   222233 non-null  int64
 7   ListAgentEmail               180295 non-null  str
 8   CloseDate                    222233 non-null  datetime64[us]
 9   ClosePrice                   222231 non-null  float64
 10  ListAgentFirstName           220770 non-null  str
 11  ListAgentLastName            222218 non-null  str
 12  Latitude                     222233 non-null  float64
 13  Longitude                    222233 non-null  float64
 14  UnparsedAddress              222092 non-null  str
 15  PropertyType                 222233 non-null  str
 16  LivingArea                   222103 non-null  float64
 17  ListPrice                    222233 non-null  float64
 18  DaysOnMarket                 222233 non-null  int64
 19  ListOfficeName               222233 non-null  str
 20  BuyerOfficeName              218777 non-null  str
 21  CoListOfficeName             50562 non-null   str
 22  ListAgentFullName            222190 non-null  str
 23  CoListAgentFirstName         50375 non-null   str
 24  CoListAgentLastName          50502 non-null   str
 25  BuyerAgentMlsId              221953 non-null  str
 26  BuyerAgentFirstName          221284 non-null  str
 27  BuyerAgentLastName           222138 non-null  str
 28  AssociationFeeFrequency      93007 non-null   str
 29  ListingKeyNumeric            222233 non-null  int64
 30  MLSAreaMajor                 196508 non-null  str
 31  CountyOrParish               222233 non-null  str
 32  MlsStatus                    222233 non-null  str
 33  ElementarySchool             30467 non-null   str
 34  AttachedGarageYN             188855 non-null  object
 35  ParkingTotal                 222232 non-null  float64
 36  PropertySubType              221882 non-null  str
 37  LotSizeAcres                 205059 non-null  float64
 38  SubdivisionName              78848 non-null   str
 39  BuyerOfficeAOR               210661 non-null  str
 40  YearBuilt                    222021 non-null  float64
 41  StreetNumberNumeric          222058 non-null  float64
 42  ListingId                    222233 non-null  str
 43  BathroomsTotalInteger        222190 non-null  float64
 44  City                         222061 non-null  str
 45  BedroomsTotal                222226 non-null  float64
 46  ContractStatusChangeDate     222233 non-null  datetime64[us]
 47  PurchaseContractDate         222052 non-null  datetime64[us]
 48  ListingContractDate          222232 non-null  datetime64[us]
 49  StateOrProvince              222233 non-null  str
 50  MiddleOrJuniorSchool         30830 non-null   str
 51  FireplaceYN                  222057 non-null  object
 52  Stories                      189195 non-null  float64
 53  HighSchool                   40128 non-null   str
 54  Levels                       201924 non-null  str
 55  LotSizeArea                  205374 non-null  float64
 56  MainLevelBedrooms            135927 non-null  float64
 57  NewConstructionYN            204961 non-null  object
 58  GarageSpaces                 212445 non-null  float64
 59  HighSchoolDistrict           166353 non-null  str
 60  PostalCode                   222233 non-null  str
 61  AssociationFee               175703 non-null  float64
 62  LotSizeSquareFeet            205311 non-null  float64
 63  OriginatingSystemName        50091 non-null   str
 64  OriginatingSystemSubName     50091 non-null   str
 65  Year                         222233 non-null  int64
 66  Month                        222233 non-null  int64
 67  BuyerAgencyCompensationType  33421 non-null   str
 68  BuyerAgencyCompensation      33427 non-null   float64
 69  latfilled                    52743 non-null   object
 70  lonfilled                    52743 non-null   object
 71  year_month                   222233 non-null  str
 72  rate_30yr_fixed              222233 non-null  float64
 73  list_after_close_flag        222233 non-null  bool
 74  purchase_after_close_flag    222233 non-null  bool
 75  negative_timeline_flag       222233 non-null  bool
 76  correct_coord                222233 non-null  bool
dtypes: bool(4), datetime64[us](4), float64(20), int64(5), object(7), str(37)
memory usage: 126.3+ MB
None

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag,correct_coord
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
5,NorthSanLuisObispo,NorthSanLuisObispo,NaN,True,False,2100000.0,1067652762,jenniferarielkennedy@gmail.com,2024-01-02,2100000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
6,CoastalMendocino,CoastalMendocino,Tile,True,False,1950000.0,1063453216,kira@mendosir.com,2024-01-22,1950000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
8,PacificSouthwest,PacificSouthwest,"Stone,Wood",True,False,1550000.0,1061822266,MaxSellsSanDiego@gmail.com,2024-01-31,1485000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
9,PasadenaFoothills,PasadenaFoothills,Wood,True,False,999000.0,1061617422,kerry.kimble@theagencyre.com,2024-01-30,1130000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True

In [35]:
enriched_listing_v3 = enriched_listing_postimeline[enriched_listing_postimeline['correct_coord']==True]
print(enriched_listing_v3.info())
display(enriched_listing_v3.head())

<class 'pandas.DataFrame'>
Index: 255935 entries, 0 to 334335
Data columns (total 92 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             255740 non-null  float64
 1   ListingKey                    255935 non-null  int64
 2   ListAgentEmail                186953 non-null  str
 3   CloseDate                     61528 non-null   datetime64[us]
 4   ClosePrice                    54581 non-null   float64
 5   ListAgentFirstName            254628 non-null  str
 6   ListAgentLastName             255922 non-null  str
 7   Latitude                      255935 non-null  float64
 8   Longitude                     255935 non-null  float64
 9   UnparsedAddress               255611 non-null  str
 10  PropertyType                  255935 non-null  str
 11  LivingArea                    255625 non-null  float64
 12  ListPrice                     255935 non-null  float64
 13  DaysOnMarket                  255935 non-null  int64
 14  ListOfficeName                255935 non-null  str
 15  BuyerOfficeName               58425 non-null   str
 16  CoListOfficeName              58253 non-null   str
 17  ListAgentFullName             255902 non-null  str
 18  CoListAgentFirstName          58036 non-null   str
 19  CoListAgentLastName           58227 non-null   str
 20  BuyerAgentMlsId               58901 non-null   str
 21  BuyerAgentFirstName           58787 non-null   str
 22  BuyerAgentLastName            58940 non-null   str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       111536 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             255935 non-null  int64
 27  MLSAreaMajor                  232063 non-null  str
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                255935 non-null  str
 30  PropertyType.1                255935 non-null  str
 31  MlsStatus                     255935 non-null  str
 32  ElementarySchool              29688 non-null   str
 33  ListAgentFirstName.1          254628 non-null  str
 34  AttachedGarageYN              208237 non-null  object
 35  ParkingTotal                  255933 non-null  float64
 36  BuilderName                   11725 non-null   str
 37  PropertySubType               255480 non-null  str
 38  LotSizeAcres                  237204 non-null  float64
 39  SubdivisionName               85882 non-null   str
 40  BuyerOfficeAOR                54989 non-null   str
 41  YearBuilt                     255378 non-null  float64
 42  DaysOnMarket.1                255935 non-null  int64
 43  BuyerAgencyCompensationType   57008 non-null   str
 44  StreetNumberNumeric           255567 non-null  float64
 45  LivingArea.1                  255625 non-null  float64
 46  ListingId                     255935 non-null  str
 47  BathroomsTotalInteger         255901 non-null  float64
 48  City                          255759 non-null  str
 49  BuyerAgencyCompensation       57018 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             29575 non-null   float64
 52  BedroomsTotal                 255866 non-null  float64
 53  ContractStatusChangeDate      251997 non-null  datetime64[us]
 54  Longitude.1                   255935 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         5801 non-null    str
 57  PurchaseContractDate          118662 non-null  datetime64[us]
 58  ListingContractDate           255935 non-null  datetime64[us]
 59  BelowGradeFinishedArea        1519 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    255935 non-null  float64
 62  ListPrice.1                   255935 non-null  float64
 63  StateOrProvince               255935 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          29989 non-null   str
 66  FireplaceYN                   255609 non-null  object
 67  Stories                       218162 non-null  float64
 68  HighSchool                    39782 non-null   str
 69  Levels                        235914 non-null  str
 70  ListAgentLastName.1           255922 non-null  str
 71  CloseDate.1                   61528 non-null   str
 72  LotSizeDimensions             16460 non-null   str
 73  LotSizeArea                   237731 non-null  float64
 74  MainLevelBedrooms             151537 non-null  float64
 75  NewConstructionYN             233450 non-null  object
 76  GarageSpaces                  237753 non-null  float64
 77  HighSchoolDistrict            182908 non-null  str
 78  PostalCode                    255933 non-null  str
 79  BuyerOfficeName.1             58425 non-null   str
 80  AssociationFee                202818 non-null  float64
 81  LotSizeSquareFeet             237649 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             255611 non-null  str
 84  Year                          255935 non-null  int64
 85  Month                         255935 non-null  int64
 86  year_month                    255935 non-null  str
 87  rate_30yr_fixed               255935 non-null  float64
 88  list_after_close_flag         255935 non-null  bool
 89  purchase_after_close_flag     255935 non-null  bool
 90  negative_timeline_flag        255935 non-null  bool
 91  correct_coord                 255935 non-null  bool
dtypes: bool(4), datetime64[us](4), float64(34), int64(6), object(3), str(41)
memory usage: 174.8+ MB
None

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag,correct_coord
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,2220 Avenue Of The Stars 2704,2024,1,2024-01,6.6425,False,False,False,True
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,NaN,16 Palisades,2024,1,2024-01,6.6425,False,False,False,True
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,1615 Waverly Road,2024,1,2024-01,6.6425,False,False,False,True
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,NaN,2250 Indian Creek Road,2024,1,2024-01,6.6425,False,False,False,True
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,NaN,317 E. Bayfront,2024,1,2024-01,6.6425,False,False,False,True

In [36]:
# Find the difference in rows after checking for date and coordinates

sold_r_change = len(enriched_sold)-len(enriched_sold_v3)

listing_r_change = len(enriched_listing)-len(enriched_listing_v3)

print(f'After checking for correct timeline and coordinates, {sold_r_change} rows are removed for Sold data')
print(f'After checking for correct timeline and coordinates, {listing_r_change} rows are removed for Listing data')

After checking for correct timeline and coordinates, 16071 rows are removed for Sold data
After checking for correct timeline and coordinates, 78401 rows are removed for Listing data

In [37]:
enriched_sold_v3.to_csv('enriched_sold_v3.csv',index=True,encoding='utf-8-sig')
enriched_listing_v3.to_csv('enriched_listing_v3.csv',index=True,encoding='utf-8-sig')

# Week 6- Feature Engineering and Market Metrics

In [38]:
# Price Ratio
enriched_sold_v4 = enriched_sold_v3.copy()
enriched_sold_v4['price_ratio']=enriched_sold_v3['ClosePrice']/enriched_sold_v3['OriginalListPrice']

#Price per SqFt
enriched_sold_v4['ppsf']=enriched_sold_v3['ClosePrice']/enriched_sold_v3['LivingArea']

#Time Series
enriched_sold_v4['yrmo'] = (
    enriched_sold_v3['CloseDate'].dt.year * 100
    + enriched_sold_v3['CloseDate'].dt.month
)

#Listing duration
enriched_sold_v4['listing_duration']=enriched_sold_v3['PurchaseContractDate']-enriched_sold_v3['ListingContractDate']

#Close Duration
enriched_sold_v4['close_duration']=enriched_sold_v3['CloseDate']-enriched_sold_v3['PurchaseContractDate']

In [39]:
# Price Ratio
enriched_listing_v4 = enriched_listing_v3.copy()
enriched_listing_v4['price_ratio']=enriched_listing_v4['ClosePrice']/enriched_listing_v4['OriginalListPrice']

#Price per SqFt
enriched_listing_v4['ppsf']=enriched_listing_v4['ClosePrice']/enriched_listing_v4['LivingArea']

#Time Series
enriched_listing_v4['yrmo'] = (
    enriched_listing_v4['CloseDate'].dt.year * 100
    + enriched_listing_v4['CloseDate'].dt.month
)

#Listing duration
enriched_listing_v4['listing_duration']=enriched_listing_v4['PurchaseContractDate']-enriched_listing_v4['ListingContractDate']

#Close Duration
enriched_listing_v4['close_duration']=enriched_listing_v4['CloseDate']-enriched_listing_v4['PurchaseContractDate']

In [56]:
# Descriptive stats table 

prop_type_df = enriched_sold_v4.groupby(['PropertyType','PropertySubType']).agg(
        n_sales=("ClosePrice", "size"),
        avg_close_price=("ClosePrice", "mean"),
        avg_price_ratio=("price_ratio", "mean"),
        avg_ppsf=("ppsf", "mean"),
        avg_days_on_market=("DaysOnMarket", "mean"),
        avg_listing_duration=("listing_duration","mean"),
        avg_close_duration=("close_duration","mean")
).dropna().reset_index().transpose().T
prop_type_df

,PropertyType,PropertySubType,n_sales,avg_close_price,avg_price_ratio,avg_ppsf,avg_days_on_market,avg_listing_duration,avg_close_duration
0,Residential,BoatSlip,42,200557.142857,0.905821,2041.478261,60.714286,62 days 02:17:08.571428,21 days 22:17:08.571428
1,Residential,Cabin,231,250736.666667,0.912031,902.907584,76.207792,85 days 17:52:12.467532,39 days 06:07:47.532467
2,Residential,CoOwnership,9,461611.0,111.976896,400.293984,55.444444,67 days 08:00:00,62 days 10:40:00
3,Residential,Condominium,36629,806133.549224,30.46748,inf,37.964209,45 days 11:18:52.305673,30 days 10:58:09.114214
4,Residential,DeededParking,2,512500.0,1.021667,704.328687,37.0,38 days 00:00:00,13 days 12:00:00
5,Residential,Duplex,1233,1230216.563666,0.980272,634.856329,42.119221,54 days 22:00:52.554744,39 days 08:11:40.729927
6,Residential,Farm,6,1946500.0,1.058935,923.646116,17.0,17 days 00:00:00,100 days 08:00:00
7,Residential,Loft,17,703399.346471,1.002695,557.504921,41.470588,47 days 22:35:17.647058,32 days 04:14:07.058823
8,Residential,ManufacturedHome,15,275533.333333,0.921118,204.254817,67.866667,75 days 08:00:00,41 days 12:48:00
9,Residential,ManufacturedOnLand,2936,351522.846778,0.958806,inf,52.36376,63 days 08:58:31.716621,41 days 04:49:22.397820
10,Residential,MixedUse,110,869909.009091,0.881918,492.127385,84.172727,94 days 19:38:10.909090,46 days 15:29:27.272727
11,Residential,MobileHome,37,484310.810811,0.881507,inf,79.702703,88 days 15:34:03.243243,14 days 05:11:21.081081
12,Residential,OwnYourOwn,27,357722.222222,0.927128,inf,77.407407,85 days 03:33:20,29 days 00:53:20
13,Residential,Quadruplex,76,1453294.578947,0.922858,426.564909,54.802632,81 days 17:03:09.473684,44 days 12:18:56.842105
14,Residential,SingleFamilyResidence,166419,1249487.539466,42.726797,inf,33.671744,41 days 19:09:43.351975,31 days 18:26:40.028865
15,Residential,StockCooperative,950,388254.466316,1.979357,401.586423,38.376842,48 days 14:48:15.157894,46 days 17:42:34.105263
16,Residential,Studio,4,321997.5,0.945494,678.654784,55.25,91 days 06:00:00,48 days 12:00:00
17,Residential,Timeshare,10,358100.0,0.946744,138.235799,66.4,66 days 21:36:00,32 days 02:24:00
18,Residential,Townhouse,12948,982387.239521,1.157463,635.680656,29.555839,36 days 05:36:12.687224,30 days 21:20:51.194064
19,Residential,Triplex,181,1397320.98895,1.101223,657.260998,49.464088,61 days 09:24:51.712707,38 days 22:32:29.171270

In [60]:
county_or_parish_df = enriched_sold_v4.groupby(['CountyOrParish','MLSAreaMajor']).agg(
        n_sales=("ClosePrice", "size"),
        avg_close_price=("ClosePrice", "mean"),
        avg_price_ratio=("price_ratio", "mean"),
        avg_ppsf=("ppsf", "mean"),
        avg_days_on_market=("DaysOnMarket", "mean"),
        avg_listing_duration=("listing_duration","mean"),
        avg_close_duration=("close_duration","mean")
).dropna().reset_index().transpose().T
county_or_parish_df

,CountyOrParish,MLSAreaMajor,n_sales,avg_close_price,avg_price_ratio,avg_ppsf,avg_days_on_market,avg_listing_duration,avg_close_duration
0,Alameda,699 - Not Defined,953,1282925.801679,1.035061,787.155199,24.251836,25 days 14:53:00.692549,30 days 05:14:17.502623
1,Alameda,BERK - Berkeley,2,786499.5,1.13568,683.90894,35.5,64 days 12:00:00,27 days 00:00:00
2,Amador,699 - Not Defined,3,301666.666667,0.87048,149.641577,87.0,87 days 08:00:00,8 days 00:00:00
3,Butte,699 - Not Defined,34,445526.470588,0.953001,256.602232,73.147059,81 days 15:31:45.882352,37 days 09:52:56.470588
4,Butte,PARA - Paradise,34,390979.117647,0.953863,255.734831,61.529412,72 days 02:07:03.529411,33 days 05:38:49.411764
...,...,...,...,...,...,...,...,...,...
1158,Ventura,VTU - Ventura,133,802018.571429,0.978712,635.653061,34.744361,48 days 09:12:10.827067,33 days 06:18:56.842105
1159,Ventura,WV - Westlake Village,417,2138028.06235,0.989896,691.488119,54.2494,57 days 20:53:04.615384,24 days 00:38:04.615384
1160,Ventura,WW - Wagon Wheel,1,729600.0,0.938996,342.374472,15.0,20 days 00:00:00,14 days 00:00:00
1161,Yolo,699 - Not Defined,8,495125.0,1.032216,322.810306,46.0,55 days 09:00:00,38 days 00:00:00
1162,Yuba,699 - Not Defined,4,376000.0,0.921455,333.856248,95.5,96 days 06:00:00,41 days 18:00:00

In [61]:
lprop_type_df = enriched_listing_v4.groupby(['ListOfficeName','BuyerOfficeName']).agg(
        n_sales=("ClosePrice", "size"),
        avg_close_price=("ClosePrice", "mean"),
        avg_price_ratio=("price_ratio", "mean"),
        avg_ppsf=("ppsf", "mean"),
        avg_days_on_market=("DaysOnMarket", "mean"),
        avg_listing_duration=("listing_duration","mean"),
        avg_close_duration=("close_duration","mean")
).dropna().reset_index().transpose().T
prop_type_df

,CountyOrParish,MLSAreaMajor,n_sales,avg_close_price,avg_price_ratio,avg_ppsf,avg_days_on_market,avg_listing_duration,avg_close_duration
0,Alameda,699 - Not Defined,953,1282925.801679,1.035061,787.155199,24.251836,25 days 14:53:00.692549,30 days 05:14:17.502623
1,Alameda,BERK - Berkeley,2,786499.5,1.13568,683.90894,35.5,64 days 12:00:00,27 days 00:00:00
2,Amador,699 - Not Defined,3,301666.666667,0.87048,149.641577,87.0,87 days 08:00:00,8 days 00:00:00
3,Butte,699 - Not Defined,34,445526.470588,0.953001,256.602232,73.147059,81 days 15:31:45.882352,37 days 09:52:56.470588
4,Butte,PARA - Paradise,34,390979.117647,0.953863,255.734831,61.529412,72 days 02:07:03.529411,33 days 05:38:49.411764
...,...,...,...,...,...,...,...,...,...
1158,Ventura,VTU - Ventura,133,802018.571429,0.978712,635.653061,34.744361,48 days 09:12:10.827067,33 days 06:18:56.842105
1159,Ventura,WV - Westlake Village,417,2138028.06235,0.989896,691.488119,54.2494,57 days 20:53:04.615384,24 days 00:38:04.615384
1160,Ventura,WW - Wagon Wheel,1,729600.0,0.938996,342.374472,15.0,20 days 00:00:00,14 days 00:00:00
1161,Yolo,699 - Not Defined,8,495125.0,1.032216,322.810306,46.0,55 days 09:00:00,38 days 00:00:00
1162,Yuba,699 - Not Defined,4,376000.0,0.921455,333.856248,95.5,96 days 06:00:00,41 days 18:00:00

In [62]:
lcounty_or_parish_df = enriched_listing_v4.groupby(['CountyOrParish','MLSAreaMajor']).agg(
        n_sales=("ClosePrice", "size"),
        avg_close_price=("ClosePrice", "mean"),
        avg_price_ratio=("price_ratio", "mean"),
        avg_ppsf=("ppsf", "mean"),
        avg_days_on_market=("DaysOnMarket", "mean"),
        avg_listing_duration=("listing_duration","mean"),
        avg_close_duration=("close_duration","mean")
).dropna().reset_index().transpose().T
lcounty_or_parish_df

,CountyOrParish,MLSAreaMajor,n_sales,avg_close_price,avg_price_ratio,avg_ppsf,avg_days_on_market,avg_listing_duration,avg_close_duration
0,Alameda,699 - Not Defined,976,1364406.098592,1.05724,798.82592,21.305328,13 days 11:42:16.912751,25 days 11:48:40.449438
1,Alameda,BERK - Berkeley,4,782999.0,1.304998,758.719961,33.5,22 days 00:00:00,38 days 00:00:00
2,Butte,699 - Not Defined,52,498333.333333,0.988969,259.872712,18.211538,27 days 19:12:00,22 days 08:00:00
3,Butte,PARA - Paradise,50,436500.0,0.995178,280.667117,15.0,21 days 17:36:00,32 days 05:20:00
4,Colusa,699 - Not Defined,5,348500.0,1.004323,325.700935,22.2,5 days 12:00:00,20 days 00:00:00
...,...,...,...,...,...,...,...,...,...
982,Ventura,VC55 - Fillmore,137,811797.15625,1.01419,479.092254,21.963504,21 days 21:44:09.056603,27 days 16:30:00
983,Ventura,VC57 - Piru,62,680000.0,1.004962,460.906205,15.83871,26 days 14:40:00,28 days 16:00:00
984,Ventura,VTU - Ventura,162,780272.884615,0.991772,631.764768,17.975309,19 days 15:41:32.307692,25 days 11:04:36.923076
985,Ventura,WV - Westlake Village,570,2171081.929688,0.994266,705.263222,18.050877,19 days 05:30:36.734693,18 days 19:30:00
986,Yolo,699 - Not Defined,5,503333.333333,1.161068,348.053773,11.2,23 days 00:00:00,22 days 08:00:00

# Week 7- Outlier Detection and Data Quality

In [44]:
def flagging_outlier(df,column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return (df[column] < lower) | (df[column] > upper)

In [ ]:
enriched_sold_v5 = enriched_sold_v4.copy()
enriched_sold_v5 = enriched_sold_v5[
    (enriched_sold_v5['ClosePrice'] > 0) &
    (enriched_sold_v5['LivingArea'] > 0) &
    (enriched_sold_v5['DaysOnMarket'] > 0)
]

In [66]:
enriched_listing_v5 = enriched_listing_v4.copy()
enriched_listing_v5 = enriched_listing_v5[
    (enriched_listing_v5['ClosePrice'] > 0) &
    (enriched_listing_v5['LivingArea'] > 0) &
    (enriched_listing_v5['DaysOnMarket'] > 0)
]

In [46]:
enriched_sold_v6 = enriched_sold_v5.copy()
enriched_sold_v6['price_outlier']=flagging_outlier(enriched_sold_v5,'ClosePrice')
enriched_sold_v6['area_outlier']=flagging_outlier(enriched_sold_v5,'LivingArea')
enriched_sold_v6['daysonmarket_outlier']=flagging_outlier(enriched_sold_v5,'DaysOnMarket')

In [67]:
enriched_listing_v6 = enriched_sold_v5.copy()
enriched_listing_v6['price_outlier']=flagging_outlier(enriched_listing_v6,'ClosePrice')
enriched_listing_v6['area_outlier']=flagging_outlier(enriched_listing_v6,'LivingArea')
enriched_listing_v6['daysonmarket_outlier']=flagging_outlier(enriched_listing_v6,'DaysOnMarket')

In [68]:
enriched_sold_v6.reset_index(drop=True).head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,negative_timeline_flag,correct_coord,price_ratio,ppsf,yrmo,listing_duration,close_duration,price_outlier,area_outlier,daysonmarket_outlier
0,PasadenaFoothills,PasadenaFoothills,Wood,True,False,999000.0,1061617422,kerry.kimble@theagencyre.com,2024-01-30,1130000.0,...,False,True,1.131131,529.026217,202401,1 days,17 days,False,False,False
1,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,True,False,1050000.0,1060223286,aliciao@kw.com,2024-01-16,1060000.0,...,False,True,1.009524,552.947314,202401,34 days,6 days,False,False,False
2,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,False,650000.0,1059869734,thinkjamesyou@gmail.com,2024-01-31,650000.0,...,False,True,1.000000,464.285714,202401,6 days,1 days,False,False,False
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,"Carpet,Tile,Wood",False,NaN,10750000.0,1059617256,jonathan@resnickandnash.com,2024-01-31,9635000.0,...,False,True,0.896279,1780.961183,202401,25 days,50 days,True,True,False
4,Southland,Southland,NaN,False,False,900000.0,1059560972,julian@getrealvalley.com,2024-01-31,762000.0,...,False,True,0.846667,485.350318,202401,1 days,0 days,False,False,False

In [69]:
enriched_listing_v6.reset_index(drop=True).head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,negative_timeline_flag,correct_coord,price_ratio,ppsf,yrmo,listing_duration,close_duration,price_outlier,area_outlier,daysonmarket_outlier
0,PasadenaFoothills,PasadenaFoothills,Wood,True,False,999000.0,1061617422,kerry.kimble@theagencyre.com,2024-01-30,1130000.0,...,False,True,1.131131,529.026217,202401,1 days,17 days,False,False,False
1,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,True,False,1050000.0,1060223286,aliciao@kw.com,2024-01-16,1060000.0,...,False,True,1.009524,552.947314,202401,34 days,6 days,False,False,False
2,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,False,650000.0,1059869734,thinkjamesyou@gmail.com,2024-01-31,650000.0,...,False,True,1.000000,464.285714,202401,6 days,1 days,False,False,False
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,"Carpet,Tile,Wood",False,NaN,10750000.0,1059617256,jonathan@resnickandnash.com,2024-01-31,9635000.0,...,False,True,0.896279,1780.961183,202401,25 days,50 days,True,True,False
4,Southland,Southland,NaN,False,False,900000.0,1059560972,julian@getrealvalley.com,2024-01-31,762000.0,...,False,True,0.846667,485.350318,202401,1 days,0 days,False,False,False

In [48]:
enriched_sold_v7 = enriched_sold_v6[
    (enriched_sold_v6['price_outlier']==False)
    &(enriched_sold_v6['area_outlier']==False)
    &(enriched_sold_v6['daysonmarket_outlier']==False)
].copy()

print(enriched_sold_v7['daysonmarket_outlier'].value_counts())

daysonmarket_outlier
False    180457
Name: count, dtype: int64

In [70]:
enriched_listing_v7 = enriched_listing_v6[
    (enriched_sold_v6['price_outlier']==False)
    &(enriched_sold_v6['area_outlier']==False)
    &(enriched_sold_v6['daysonmarket_outlier']==False)
].copy()

print(enriched_listing_v7['daysonmarket_outlier'].value_counts())

daysonmarket_outlier
False    180457
Name: count, dtype: int64

In [71]:
before_summary = enriched_sold_v6[['ClosePrice','LivingArea','DaysOnMarket']].describe()
before_summary

         ClosePrice     LivingArea   DaysOnMarket
count  2.131310e+05  213131.000000  213131.000000
mean   1.126628e+06    1855.488966      35.995332
std    3.433612e+06    1002.282894      54.798142
min    1.150000e+00       1.000000       1.000000
25%    5.692820e+05    1248.000000       8.000000
50%    8.100000e+05    1640.000000      18.000000
75%    1.270000e+06    2209.000000      46.000000
max    7.960000e+08  123764.000000   12430.000000

In [72]:
after_summary = enriched_sold_v7[['ClosePrice','LivingArea','DaysOnMarket']].describe()
after_summary

         ClosePrice     LivingArea   DaysOnMarket
count  1.804570e+05  180457.000000  180457.000000
mean   8.825035e+05    1671.535502      25.419806
std    4.467786e+05     622.734099      23.835742
min    1.150000e+00       1.000000       1.000000
25%    5.559900e+05    1213.000000       8.000000
50%    7.750000e+05    1567.000000      16.000000
75%    1.125000e+06    2030.000000      37.000000
max    2.321000e+06    3650.000000     103.000000

In [74]:
lbefore_summary = enriched_listing_v6[['ClosePrice','LivingArea','DaysOnMarket']].describe()
lbefore_summary

         ClosePrice     LivingArea   DaysOnMarket
count  2.131310e+05  213131.000000  213131.000000
mean   1.126628e+06    1855.488966      35.995332
std    3.433612e+06    1002.282894      54.798142
min    1.150000e+00       1.000000       1.000000
25%    5.692820e+05    1248.000000       8.000000
50%    8.100000e+05    1640.000000      18.000000
75%    1.270000e+06    2209.000000      46.000000
max    7.960000e+08  123764.000000   12430.000000

In [75]:
lafter_summary = enriched_listing_v7[['ClosePrice','LivingArea','DaysOnMarket']].describe()
lafter_summary

         ClosePrice     LivingArea   DaysOnMarket
count  1.804570e+05  180457.000000  180457.000000
mean   8.825035e+05    1671.535502      25.419806
std    4.467786e+05     622.734099      23.835742
min    1.150000e+00       1.000000       1.000000
25%    5.559900e+05    1213.000000       8.000000
50%    7.750000e+05    1567.000000      16.000000
75%    1.125000e+06    2030.000000      37.000000
max    2.321000e+06    3650.000000     103.000000

In [77]:
#Change in number of values 

print(f'Difference in rows after filtering out outliers for sold dataset: {len(enriched_sold_v6)-len(enriched_sold_v7)} rows.')
print(f'Difference in rows after filtering out outliers for listing dataset: {len(enriched_listing_v6)-len(enriched_listing_v7)} rows.')

Difference in rows after filtering out outliers for sold dataset: 32674 rows.
Difference in rows after filtering out outliers for listing dataset: 32674 rows.

In [76]:
enriched_sold_v7.to_csv('completed_sold.csv',index=True,encoding='utf-8-sig')

In [78]:
enriched_listing_v7.to_csv('completed_listing.csv',index=True,encoding='utf-8-sig')

In [53]:
enriched_sold_v5['correct_coord'].value_counts()

correct_coord
True    213131
Name: count, dtype: int64

In [54]:
print(enriched_sold_v5.columns)

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'PoolPrivateYN',
       'OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'AssociationFeeFrequency', 'ListingKeyNumeric',
       'MLSAreaMajor', 'CountyOrParish', 'MlsStatus', 'ElementarySchool',
       'AttachedGarageYN', 'ParkingTotal', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BedroomsTotal',
       'ContractStatusChangeDate', 'PurchaseContractDate',
       'ListingContractDate', 'StateOrProvince', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'LotSizeArea',
       'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces',
       'HighSchoolDistrict', 'PostalCode', 'AssociationFee',
       'LotSizeSquareFeet', 'OriginatingSystemName',
       'OriginatingSystemSubName', 'Year', 'Month',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled', 'year_month', 'rate_30yr_fixed', 'list_after_close_flag',
       'purchase_after_close_flag', 'negative_timeline_flag', 'correct_coord',
       'price_ratio', 'ppsf', 'yrmo', 'listing_duration', 'close_duration'],
      dtype='str')

In [55]:
enriched_listing_v3['PropertyType'].value_counts()

PropertyType
Residential    255935
Name: count, dtype: int64