In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [65]:
url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=MORTGAGE30US"
mortgage = pd.read_csv(url, parse_dates=['observation_date'])
mortgage.columns = ['date', 'rate_30yr_fixed']

In [66]:
# Making a unified listing df
listing_dfs = []

for year in range(2024,2027):
    for month in range(1, 13):
        fname = f"CRMLSListing{year}{month:02d}.csv"
        try:
            df = pd.read_csv(fname,parse_dates=['CloseDate'])
            df['Year'] = year
            df['Month'] = month
            listing_dfs.append(df)
        except FileNotFoundError:
            # Skip months that don't exist yet
            continue

# If you want one big DataFrame:
all_listings_df = pd.concat(listing_dfs, ignore_index=True)

In [67]:
all_listings_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 887636 entries, 0 to 887635
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             884189 non-null  float64
 1   ListingKey                    887636 non-null  int64
 2   ListAgentEmail                780379 non-null  str
 3   CloseDate                     280180 non-null  datetime64[us]
 4   ClosePrice                    257107 non-null  float64
 5   ListAgentFirstName            882467 non-null  str
 6   ListAgentLastName             887560 non-null  str
 7   Latitude                      775343 non-null  float64
 8   Longitude                     776065 non-null  float64
 9   UnparsedAddress               885364 non-null  str
 10  PropertyType                  887636 non-null  str
 11  LivingArea                    777273 non-null  float64
 12  ListPrice                     885421 non-null  float64
 13  DaysOnMarket                  887636 non-null  int64
 14  ListOfficeName                887636 non-null  str
 15  BuyerOfficeName               269492 non-null  str
 16  CoListOfficeName              178467 non-null  str
 17  ListAgentFullName             887393 non-null  str
 18  CoListAgentFirstName          177717 non-null  str
 19  CoListAgentLastName           178219 non-null  str
 20  BuyerAgentMlsId               271239 non-null  str
 21  BuyerAgentFirstName           271105 non-null  str
 22  BuyerAgentLastName            272080 non-null  str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       257053 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             887636 non-null  int64
 27  MLSAreaMajor                  787297 non-null  str
 28  TaxAnnualAmount               6273 non-null    float64
 29  CountyOrParish                887635 non-null  str
 30  PropertyType.1                887636 non-null  str
 31  MlsStatus                     887636 non-null  str
 32  ElementarySchool              82740 non-null   str
 33  ListAgentFirstName.1          882467 non-null  str
 34  AttachedGarageYN              585747 non-null  object
 35  ParkingTotal                  833265 non-null  float64
 36  BuilderName                   30416 non-null   str
 37  PropertySubType               779803 non-null  str
 38  LotSizeAcres                  803371 non-null  float64
 39  SubdivisionName               296646 non-null  str
 40  BuyerOfficeAOR                255731 non-null  str
 41  YearBuilt                     815737 non-null  float64
 42  DaysOnMarket.1                887636 non-null  int64
 43  BuyerAgencyCompensationType   123538 non-null  str
 44  StreetNumberNumeric           883708 non-null  float64
 45  LivingArea.1                  777273 non-null  float64
 46  ListingId                     887636 non-null  str
 47  BathroomsTotalInteger         814954 non-null  float64
 48  City                          886651 non-null  str
 49  BuyerAgencyCompensation       123519 non-null  float64
 50  TaxYear                       903 non-null     float64
 51  BuildingAreaTotal             141869 non-null  float64
 52  BedroomsTotal                 780820 non-null  float64
 53  ContractStatusChangeDate      880579 non-null  str
 54  Longitude.1                   776065 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         21850 non-null   str
 57  PurchaseContractDate          395698 non-null  str
 58  ListingContractDate           887636 non-null  str
 59  BelowGradeFinishedArea        3618 non-null    float64
 60  BusinessType                  6208 non-null    str
 61  Latitude.1                    775343 non-null  float64
 62  ListPrice.1                   885421 non-null  float64
 63  StateOrProvince               887556 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          82794 non-null   str
 66  FireplaceYN                   760656 non-null  object
 67  Stories                       658535 non-null  float64
 68  HighSchool                    108878 non-null  str
 69  Levels                        718073 non-null  str
 70  ListAgentLastName.1           887560 non-null  str
 71  CloseDate.1                   280180 non-null  str
 72  LotSizeDimensions             50655 non-null   str
 73  LotSizeArea                   807279 non-null  float64
 74  MainLevelBedrooms             411914 non-null  float64
 75  NewConstructionYN             768506 non-null  object
 76  GarageSpaces                  719981 non-null  float64
 77  HighSchoolDistrict            535563 non-null  str
 78  PostalCode                    887418 non-null  str
 79  BuyerOfficeName.1             269492 non-null  str
 80  AssociationFee                601867 non-null  float64
 81  LotSizeSquareFeet             806172 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             885364 non-null  str
 84  Year                          887636 non-null  int64
 85  Month                         887636 non-null  int64
dtypes: datetime64[us](1), float64(32), int64(6), object(3), str(44)
memory usage: 582.4+ MB

In [68]:
print("Preview of Concatenated Listing DataFrame")
display(all_listings_df.tail())

print("---------/--------")
print("All columns in DataFrame\n")
print(all_listings_df.columns)
print("---------/--------")
print("Description of DataFrame\n")
print(all_listings_df.describe)

Preview of Concatenated Listing DataFrame

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month
887631,1375000.0,1151355330,NaN,NaT,NaN,Athir,Markos,32.811131,-116.946359,1161 N Anza Street,...,NaN,NaN,92021,NaN,0.0,222156.0,NaN,1161 N Anza Street,2026,4
887632,985000.0,1149517845,NaN,NaT,NaN,Aisa,Tu,33.645255,-117.358172,33115 Evergreen Sreet,...,3.0,Lake Elsinore Unified,92530,NaN,0.0,14810.0,NaN,33115 Evergreen Sreet,2026,4
887633,450000.0,1147219386,NaN,NaT,NaN,Nathaly,Vera,32.746368,-116.984283,9860 Dale Avenue D2,...,0.0,Other,91977,NaN,510.0,91040.4,NaN,9860 Dale Avenue D2,2026,4
887634,249000.0,1145273331,NaN,NaT,NaN,Bill,Church,33.229747,-117.127269,Little Canyon Lane,...,NaN,NaN,92026,NaN,210.0,37897.0,NaN,Little Canyon Lane,2026,4
887635,1056400.0,1144232364,NaN,2026-02-05,965200.0,John,Osborne,33.637915,-114.575821,9165 Intake Boulevard,...,NaN,NaN,92225,SimpliHOM,NaN,3445160.0,NaN,9165 Intake Boulevard,2026,4

---------/--------
All columns in DataFrame

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1', 'Year', 'Month'],
      dtype='str')
---------/--------
Description of DataFrame

<bound method NDFrame.describe of         OriginalListPrice  ListingKey                        ListAgentEmail  \
0                 90000.0  1075010398                miriamlara03@gmail.com
1               1500000.0  1074974457                  janelle@judsonre.com
2               1340000.0  1074973329                    haleh360@Gmail.com
3               2500000.0  1074954552  Reneechen@yourhomesoldguaranteed.com
4               3150000.0  1074936537                      anader@dppre.com
...                   ...         ...                                   ...
887631          1375000.0  1151355330                                   NaN
887632           985000.0  1149517845                                   NaN
887633           450000.0  1147219386                                   NaN
887634           249000.0  1145273331                                   NaN
887635          1056400.0  1144232364                                   NaN

        CloseDate  ClosePrice ListAgentFirstName ListAgentLastName   Latitude  \
0             NaT         NaN             Miriam              Lara  34.097939
1             NaT         NaN            Janelle            Judson  33.121241
2             NaT         NaN              Haleh       Dowlatshahi  34.052207
3             NaT         NaN              Renee              Chen  33.496363
4             NaT         NaN           Margaret             Nader  34.119345
...           ...         ...                ...               ...        ...
887631        NaT         NaN              Athir            Markos  32.811131
887632        NaT         NaN               Aisa                Tu  33.645255
887633        NaT         NaN            Nathaly              Vera  32.746368
887634        NaT         NaN               Bill            Church  33.229747
887635 2026-02-05    965200.0               John           Osborne  33.637915

         Longitude                UnparsedAddress  ... GarageSpaces  \
0      -117.909653                1045 N Azusa 61  ...          2.0
1      -117.081614                            NaN  ...          NaN
2      -118.408445  2220 Avenue Of The Stars 2704  ...          NaN
3      -117.691677                   16 Palisades  ...          3.0
4      -118.111254              1615 Waverly Road  ...          2.0
...            ...                            ...  ...          ...
887631 -116.946359             1161 N Anza Street  ...          NaN
887632 -117.358172          33115 Evergreen Sreet  ...          3.0
887633 -116.984283            9860 Dale Avenue D2  ...          0.0
887634 -117.127269             Little Canyon Lane  ...          NaN
887635 -114.575821          9165 Intake Boulevard  ...          NaN

           HighSchoolDistrict  PostalCode  BuyerOfficeName.1 AssociationFee  \
0       Covina Valley Unified       91722                NaN            0.0
1                         NaN       92025                NaN            0.0
2                         NaN       90067                NaN         2105.0
3          Capistrano Unified       92677                NaN          254.0
4                         NaN       91108                NaN            NaN
...                       ...         ...                ...            ...
887631                    NaN       92021                NaN            0.0
887632  Lake Elsinore Unified       92530                NaN            0.0
887633                  Other       91977                NaN          510.0
887634                    NaN       92026                NaN          210.0
887635                    NaN       92225          SimpliHOM            NaN

       LotSizeSquareFeet MiddleOrJuniorSchoolDistrict  \
0                    NaN                          NaN
1                    NaN                          NaN
2               177861.0                          NaN
3                 5300.0                          NaN
4                 9404.0                          NaN
...                  ...                          ...
887631          222156.0                          NaN
887632           14810.0                          NaN
887633           91040.4                          NaN
887634           37897.0                          NaN
887635         3445160.0                          NaN

                    UnparsedAddress.1  Year Month
0                     1045 N Azusa 61  2024     1
1                                 NaN  2024     1
2       2220 Avenue Of The Stars 2704  2024     1
3                        16 Palisades  2024     1
4                   1615 Waverly Road  2024     1
...                               ...   ...   ...
887631             1161 N Anza Street  2026     4
887632          33115 Evergreen Sreet  2026     4
887633            9860 Dale Avenue D2  2026     4
887634             Little Canyon Lane  2026     4
887635          9165 Intake Boulevard  2026     4

[887636 rows x 86 columns]>

In [69]:
cleaned_listings=all_listings_df[all_listings_df['PropertyType']=='Residential']
cleaned_listings.info()
display(cleaned_listings.head())

<class 'pandas.DataFrame'>
Index: 563856 entries, 2 to 887633
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             563043 non-null  float64
 1   ListingKey                    563856 non-null  int64
 2   ListAgentEmail                493182 non-null  str
 3   CloseDate                     178407 non-null  datetime64[us]
 4   ClosePrice                    157726 non-null  float64
 5   ListAgentFirstName            559470 non-null  str
 6   ListAgentLastName             563816 non-null  str
 7   Latitude                      483486 non-null  float64
 8   Longitude                     483486 non-null  float64
 9   UnparsedAddress               563107 non-null  str
 10  PropertyType                  563856 non-null  str
 11  LivingArea                    563284 non-null  float64
 12  ListPrice                     563856 non-null  float64
 13  DaysOnMarket                  563856 non-null  int64
 14  ListOfficeName                563856 non-null  str
 15  BuyerOfficeName               169196 non-null  str
 16  CoListOfficeName              126646 non-null  str
 17  ListAgentFullName             563762 non-null  str
 18  CoListAgentFirstName          126135 non-null  str
 19  CoListAgentLastName           126549 non-null  str
 20  BuyerAgentMlsId               171499 non-null  str
 21  BuyerAgentFirstName           170854 non-null  str
 22  BuyerAgentLastName            171620 non-null  str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       241161 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             563856 non-null  int64
 27  MLSAreaMajor                  487566 non-null  str
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                563856 non-null  str
 30  PropertyType.1                563856 non-null  str
 31  MlsStatus                     563856 non-null  str
 32  ElementarySchool              67278 non-null   str
 33  ListAgentFirstName.1          559470 non-null  str
 34  AttachedGarageYN              465442 non-null  object
 35  ParkingTotal                  563836 non-null  float64
 36  BuilderName                   26213 non-null   str
 37  PropertySubType               562554 non-null  str
 38  LotSizeAcres                  517569 non-null  float64
 39  SubdivisionName               207697 non-null  str
 40  BuyerOfficeAOR                157708 non-null  str
 41  YearBuilt                     562886 non-null  float64
 42  DaysOnMarket.1                563856 non-null  int64
 43  BuyerAgencyCompensationType   79013 non-null   str
 44  StreetNumberNumeric           562918 non-null  float64
 45  LivingArea.1                  563284 non-null  float64
 46  ListingId                     563856 non-null  str
 47  BathroomsTotalInteger         563799 non-null  float64
 48  City                          563259 non-null  str
 49  BuyerAgencyCompensation       78993 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             50029 non-null   float64
 52  BedroomsTotal                 563704 non-null  float64
 53  ContractStatusChangeDate      557634 non-null  str
 54  Longitude.1                   483486 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         15687 non-null   str
 57  PurchaseContractDate          282849 non-null  str
 58  ListingContractDate           563856 non-null  str
 59  BelowGradeFinishedArea        3219 non-null    float64
 60  BusinessType                  0 non-null       str
 61  Latitude.1                    483486 non-null  float64
 62  ListPrice.1                   563856 non-null  float64
 63  StateOrProvince               563789 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          67367 non-null   str
 66  FireplaceYN                   563260 non-null  object
 67  Stories                       465776 non-null  float64
 68  HighSchool                    88316 non-null   str
 69  Levels                        503496 non-null  str
 70  ListAgentLastName.1           563816 non-null  str
 71  CloseDate.1                   178407 non-null  str
 72  LotSizeDimensions             29486 non-null   str
 73  LotSizeArea                   518452 non-null  float64
 74  MainLevelBedrooms             307265 non-null  float64
 75  NewConstructionYN             524898 non-null  object
 76  GarageSpaces                  532632 non-null  float64
 77  HighSchoolDistrict            394361 non-null  str
 78  PostalCode                    563843 non-null  str
 79  BuyerOfficeName.1             169196 non-null  str
 80  AssociationFee                428680 non-null  float64
 81  LotSizeSquareFeet             518273 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             563107 non-null  str
 84  Year                          563856 non-null  int64
 85  Month                         563856 non-null  int64
dtypes: datetime64[us](1), float64(32), int64(6), object(3), str(44)
memory usage: 374.3+ MB

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month
2,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,NaN,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,3.0,Capistrano Unified,92677,NaN,254.00,5300.0,NaN,16 Palisades,2024,1
4,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024,1
5,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,4.0,Walnut Valley Unified,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road,2024,1
6,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,2.0,Newport Mesa Unified,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront,2024,1

In [70]:
before_r_list = all_listings_df.shape[0]
after_r_list = cleaned_listings.shape[0]

print(f"Row count before Residential filter: {before_r_list} rows")
print(f"Row count after Residential filter: {after_r_list} rows")
row_change = before_r_list - after_r_list
print(f"{row_change} rows were dropped after filtering for 'Residential' property only.")

Row count before Residential filter: 887636 rows
Row count after Residential filter: 563856 rows
323780 rows were dropped after filtering for 'Residential' property only.

In [71]:
cleaned_listings.to_csv("cleaned_listings.csv",index=True,encoding="utf-8-sig")

In [72]:
sold_dfs = []

for year in range(2024,2027):
    for month in range(1, 13):
        fname = f"CRMLSSold{year}{month:02d}.csv"
        try:
            df = pd.read_csv(fname)
            df['Year'] = year
            df['Month'] = month
            sold_dfs.append(df)
        except FileNotFoundError:
            # Skip months that don't exist yet
            continue

# If you want one big DataFrame:
all_sold_df = pd.concat(sold_dfs, ignore_index=True)

/var/folders/lb/w22468fj03vf0vnvwqj9nf840000gn/T/ipykernel_50165/3338404984.py:7: DtypeWarning: Columns (0: WaterfrontYN, 1: ElementarySchool, 2: BuilderName, 3: CoBuyerAgentFirstName, 4: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fname)
/var/folders/lb/w22468fj03vf0vnvwqj9nf840000gn/T/ipykernel_50165/3338404984.py:7: DtypeWarning: Columns (0: WaterfrontYN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fname)
/var/folders/lb/w22468fj03vf0vnvwqj9nf840000gn/T/ipykernel_50165/3338404984.py:7: DtypeWarning: Columns (0: WaterfrontYN, 1: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fname)

In [73]:
all_sold_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 612097 entries, 0 to 612096
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 538774 non-null  str
 1   ListAgentAOR                  544041 non-null  str
 2   Flooring                      359870 non-null  str
 3   ViewYN                        550844 non-null  object
 4   WaterfrontYN                  335 non-null     object
 5   BasementYN                    10098 non-null   object
 6   PoolPrivateYN                 535907 non-null  object
 7   OriginalListPrice             610314 non-null  float64
 8   ListingKey                    612097 non-null  int64
 9   ListAgentEmail                547714 non-null  str
 10  CloseDate                     612097 non-null  str
 11  ClosePrice                    612091 non-null  float64
 12  ListAgentFirstName            608561 non-null  str
 13  ListAgentLastName             612039 non-null  str
 14  Latitude                      592845 non-null  float64
 15  Longitude                     593019 non-null  float64
 16  UnparsedAddress               611147 non-null  str
 17  PropertyType                  612097 non-null  str
 18  LivingArea                    569387 non-null  float64
 19  ListPrice                     611169 non-null  float64
 20  DaysOnMarket                  612097 non-null  int64
 21  ListOfficeName                612097 non-null  str
 22  BuyerOfficeName               604591 non-null  str
 23  CoListOfficeName              131266 non-null  str
 24  ListAgentFullName             611933 non-null  str
 25  CoListAgentFirstName          126538 non-null  str
 26  CoListAgentLastName           126796 non-null  str
 27  BuyerAgentMlsId               610178 non-null  str
 28  BuyerAgentFirstName           609420 non-null  str
 29  BuyerAgentLastName            611753 non-null  str
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       180984 non-null  str
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             612097 non-null  int64
 34  MLSAreaMajor                  544644 non-null  str
 35  TaxAnnualAmount               2557 non-null    float64
 36  CountyOrParish                612097 non-null  str
 37  MlsStatus                     612097 non-null  str
 38  ElementarySchool              67848 non-null   str
 39  AttachedGarageYN              442596 non-null  object
 40  ParkingTotal                  593105 non-null  float64
 41  BuilderName                   23277 non-null   str
 42  PropertySubType               565613 non-null  str
 43  LotSizeAcres                  554343 non-null  float64
 44  SubdivisionName               216354 non-null  str
 45  BuyerOfficeAOR                584720 non-null  str
 46  YearBuilt                     586585 non-null  float64
 47  StreetNumberNumeric           610567 non-null  float64
 48  ListingId                     612097 non-null  str
 49  BathroomsTotalInteger         584157 non-null  float64
 50  City                          611657 non-null  str
 51  TaxYear                       373 non-null     float64
 52  BuildingAreaTotal             79213 non-null   float64
 53  BedroomsTotal                 571835 non-null  float64
 54  ContractStatusChangeDate      611385 non-null  str
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         49848 non-null   str
 57  PurchaseContractDate          599848 non-null  str
 58  ListingContractDate           612012 non-null  str
 59  BelowGradeFinishedArea        2699 non-null    float64
 60  BusinessType                  1653 non-null    str
 61  StateOrProvince               612097 non-null  str
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          68340 non-null   str
 64  FireplaceYN                   559119 non-null  object
 65  Stories                       490244 non-null  float64
 66  HighSchool                    89035 non-null   str
 67  Levels                        528619 non-null  str
 68  LotSizeDimensions             32117 non-null   str
 69  LotSizeArea                   556267 non-null  float64
 70  MainLevelBedrooms             324889 non-null  float64
 71  NewConstructionYN             539484 non-null  object
 72  GarageSpaces                  534077 non-null  float64
 73  HighSchoolDistrict            407799 non-null  str
 74  PostalCode                    611929 non-null  object
 75  AssociationFee                422221 non-null  float64
 76  LotSizeSquareFeet             555804 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         80991 non-null   str
 79  OriginatingSystemSubName      80991 non-null   str
 80  Year                          612097 non-null  int64
 81  Month                         612097 non-null  int64
 82  BuyerAgencyCompensationType   67747 non-null   str
 83  BuyerAgencyCompensation       67780 non-null   float64
 84  latfilled                     95793 non-null   object
 85  lonfilled                     95793 non-null   object
dtypes: float64(28), int64(5), object(10), str(43)
memory usage: 401.6+ MB

In [74]:
print("Preview of Concatenated Sold DataFrame")
display(all_sold_df.head())

print("---------/--------")
print("All columns in DataFrame\n")
print(all_sold_df.columns)
print("---------/--------")
print("Description of DataFrame\n")
print(all_sold_df.describe)

before_shape = all_sold_df.shape

Preview of Concatenated Sold DataFrame

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,NaN,NaN,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,52320.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,217364.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,217800.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,108883.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN

---------/--------
All columns in DataFrame

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName', 'Year', 'Month',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='str')
---------/--------
Description of DataFrame

<bound method NDFrame.describe of                    BuyerAgentAOR              ListAgentAOR          Flooring  \
0                    Mlslistings               Mlslistings  Carpet,Tile,Wood
1                     HighDesert                HighDesert               NaN
2                   OrangeCounty              OrangeCounty               NaN
3                  InlandValleys             InlandValleys               NaN
4       SouthwestRiversideCounty  SouthwestRiversideCounty               NaN
...                          ...                       ...               ...
612092         SierraNorthValley         SierraNorthValley               NaN
612093  SouthwestRiversideCounty             InlandValleys               NaN
612094                     Mrmls                 Southland               NaN
612095              OrangeCounty                HighDesert               NaN
612096              CitrusValley              CitrusValley               NaN

       ViewYN WaterfrontYN BasementYN PoolPrivateYN  OriginalListPrice  \
0        True          NaN        NaN         False           499000.0
1         NaN          NaN        NaN           NaN                0.0
2        True          NaN        NaN           NaN            75000.0
3        True          NaN        NaN           NaN           199000.0
4        True          NaN        NaN           NaN            19500.0
...       ...          ...        ...           ...                ...
612092   True          NaN        NaN           NaN           200000.0
612093   True          NaN        NaN           NaN            97500.0
612094   True          NaN        NaN           NaN            15999.0
612095   True          NaN        NaN           NaN          6000000.0
612096  False          NaN        NaN         False                NaN

        ListingKey              ListAgentEmail  ... LotSizeSquareFeet  \
0        551985747       jwachter@cbnorcal.com  ...               NaN
1        535486633  eabrown@lee-associates.com  ...           52320.0
2        529986282             Joe@9WINWIN.com  ...          217364.0
3        529618166    carolthefinder@yahoo.com  ...          217800.0
4        522614340      jtavisola@tavisola.com  ...          108883.0
...            ...                         ...  ...               ...
612092  1014741959                         NaN  ...          910839.6
612093  1002540286                         NaN  ...          522720.0
612094   482785043                         NaN  ...           20009.0
612095   446619807                         NaN  ...          122839.0
612096   431883449                         NaN  ...           21780.0

        MiddleOrJuniorSchoolDistrict OriginatingSystemName  \
0                                NaN                 CRMLS
1                                NaN                 CRMLS
2                                NaN                 CRMLS
3                                NaN                 CRMLS
4                                NaN                 CRMLS
...                              ...                   ...
612092                           NaN                 CRMLS
612093                           NaN                 CRMLS
612094                           NaN                 CRMLS
612095                           NaN                 CRMLS
612096                           NaN                 CRMLS

       OriginatingSystemSubName  Year  Month BuyerAgencyCompensationType  \
0                    CRMLS_MLSL  2024      1                         NaN
1                     CRMLS_CRM  2024      1                         NaN
2                     CRMLS_CRM  2024      1                         NaN
3                     CRMLS_CRM  2024      1                         NaN
4                     CRMLS_CRM  2024      1                         NaN
...                         ...   ...    ...                         ...
612092                CRMLS_CRM  2026      4                         NaN
612093                CRMLS_CRM  2026      4                         NaN
612094                CRMLS_CRM  2026      4                         NaN
612095                CRMLS_CRM  2026      4                         NaN
612096                CRMLS_CRM  2026      4                         NaN

       BuyerAgencyCompensation  latfilled  lonfilled
0                          NaN        NaN        NaN
1                          NaN        NaN        NaN
2                          NaN        NaN        NaN
3                          NaN        NaN        NaN
4                          NaN        NaN        NaN
...                        ...        ...        ...
612092                     NaN        NaN        NaN
612093                     NaN        NaN        NaN
612094                     NaN        NaN        NaN
612095                     NaN        NaN        NaN
612096                     NaN        NaN        NaN

[612097 rows x 86 columns]>

In [75]:
prop_type = all_sold_df['PropertyType'].unique()
print(f"Unique Property Types: {prop_type}")

Unique Property Types: <StringArray>
[        'Residential',     'CommercialLease',                'Land',
    'ResidentialLease',  'ManufacturedInPark',   'ResidentialIncome',
      'CommercialSale', 'BusinessOpportunity']
Length: 8, dtype: str

In [76]:
residential_sold_df=all_sold_df[all_sold_df['PropertyType']=='Residential']
residential_sold_df.info()
display(residential_sold_df.tail())

after_shape = residential_sold_df.shape

<class 'pandas.DataFrame'>
Index: 411523 entries, 0 to 612078
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 360927 non-null  str
 1   ListAgentAOR                  365335 non-null  str
 2   Flooring                      263863 non-null  str
 3   ViewYN                        376351 non-null  object
 4   WaterfrontYN                  256 non-null     object
 5   BasementYN                    8038 non-null    object
 6   PoolPrivateYN                 376018 non-null  object
 7   OriginalListPrice             410763 non-null  float64
 8   ListingKey                    411523 non-null  int64
 9   ListAgentEmail                368591 non-null  str
 10  CloseDate                     411523 non-null  str
 11  ClosePrice                    411521 non-null  float64
 12  ListAgentFirstName            408426 non-null  str
 13  ListAgentLastName             411485 non-null  str
 14  Latitude                      395592 non-null  float64
 15  Longitude                     395592 non-null  float64
 16  UnparsedAddress               411134 non-null  str
 17  PropertyType                  411523 non-null  str
 18  LivingArea                    411289 non-null  float64
 19  ListPrice                     411523 non-null  float64
 20  DaysOnMarket                  411523 non-null  int64
 21  ListOfficeName                411523 non-null  str
 22  BuyerOfficeName               404819 non-null  str
 23  CoListOfficeName              97414 non-null   str
 24  ListAgentFullName             411437 non-null  str
 25  CoListAgentFirstName          94320 non-null   str
 26  CoListAgentLastName           94561 non-null   str
 27  BuyerAgentMlsId               410999 non-null  str
 28  BuyerAgentFirstName           409529 non-null  str
 29  BuyerAgentLastName            411350 non-null  str
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       171334 non-null  str
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             411523 non-null  int64
 34  MLSAreaMajor                  356382 non-null  str
 35  TaxAnnualAmount               0 non-null       float64
 36  CountyOrParish                411523 non-null  str
 37  MlsStatus                     411523 non-null  str
 38  ElementarySchool              54803 non-null   str
 39  AttachedGarageYN              348686 non-null  object
 40  ParkingTotal                  411097 non-null  float64
 41  BuilderName                   20118 non-null   str
 42  PropertySubType               410723 non-null  str
 43  LotSizeAcres                  379157 non-null  float64
 44  SubdivisionName               153190 non-null  str
 45  BuyerOfficeAOR                388507 non-null  str
 46  YearBuilt                     411151 non-null  float64
 47  StreetNumberNumeric           411046 non-null  float64
 48  ListingId                     411523 non-null  str
 49  BathroomsTotalInteger         411454 non-null  float64
 50  City                          411213 non-null  str
 51  TaxYear                       0 non-null       float64
 52  BuildingAreaTotal             28797 non-null   float64
 53  BedroomsTotal                 411513 non-null  float64
 54  ContractStatusChangeDate      410934 non-null  str
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         37424 non-null   str
 57  PurchaseContractDate          411329 non-null  str
 58  ListingContractDate           411522 non-null  str
 59  BelowGradeFinishedArea        2383 non-null    float64
 60  BusinessType                  0 non-null       str
 61  StateOrProvince               411523 non-null  str
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          55207 non-null   str
 64  FireplaceYN                   411196 non-null  object
 65  Stories                       348076 non-null  float64
 66  HighSchool                    71651 non-null   str
 67  Levels                        371792 non-null  str
 68  LotSizeDimensions             19976 non-null   str
 69  LotSizeArea                   379680 non-null  float64
 70  MainLevelBedrooms             238526 non-null  float64
 71  NewConstructionYN             380935 non-null  object
 72  GarageSpaces                  393881 non-null  float64
 73  HighSchoolDistrict            298423 non-null  str
 74  PostalCode                    411521 non-null  object
 75  AssociationFee                317207 non-null  float64
 76  LotSizeSquareFeet             379552 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         53172 non-null   str
 79  OriginatingSystemSubName      53172 non-null   str
 80  Year                          411523 non-null  int64
 81  Month                         411523 non-null  int64
 82  BuyerAgencyCompensationType   46136 non-null   str
 83  BuyerAgencyCompensation       46125 non-null   float64
 84  latfilled                     63884 non-null   object
 85  lonfilled                     63884 non-null   object
dtypes: float64(28), int64(5), object(10), str(43)
memory usage: 273.2+ MB

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
612065,LakeCounty,LakeCounty,NaN,True,NaN,True,False,279000.0,1069708148,NaN,...,10019.0,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN
612067,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,NaN,True,False,449000.0,1067010583,NaN,...,12096.0,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN
612070,SanDiego,TriCounties,Vinyl,True,NaN,NaN,False,1579000.0,1063196193,NaN,...,859874.4,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN
612071,Mrmls,OrangeCounty,NaN,True,NaN,NaN,False,855000.0,1062106215,NaN,...,2733.0,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN
612078,Southland,PacificWest,"Carpet,Vinyl",False,NaN,NaN,False,375000.0,1052387780,NaN,...,23878.0,NaN,CRMLS,CRMLS_CRM,2026,4,NaN,NaN,NaN,NaN

In [77]:
# Change in rows
print(f"Row count before Residential filter: {before_shape[0]} rows")
print(f"Row count after Residential filter: {after_shape[0]} rows")
row_change = before_shape[0] - after_shape[0]
print(f"{row_change} rows were dropped after filtering for 'Residential' property only.")

Row count before Residential filter: 612097 rows
Row count after Residential filter: 411523 rows
200574 rows were dropped after filtering for 'Residential' property only.

In [78]:
completedness_count = pd.DataFrame(
    residential_sold_df.isnull().sum()
).reset_index()
completedness_count.columns = ["Column Name", "count"]
completedness_count = completedness_count.sort_values(by='count',ascending=False)

display(completedness_count)

completedness_pct = pd.DataFrame(residential_sold_df.isnull().mean()).reset_index()
completedness_pct.columns = ["Column Name","pct"]

                     Column Name   count
62                 CoveredSpaces  411523
77  MiddleOrJuniorSchoolDistrict  411523
32        AboveGradeFinishedArea  411523
30               FireplacesTotal  411523
51                       TaxYear  411523
..                           ...     ...
20                  DaysOnMarket       0
21                ListOfficeName       0
48                     ListingId       0
33             ListingKeyNumeric       0
61               StateOrProvince       0

[86 rows x 2 columns]

In [79]:
flagged_columns = completedness_pct[completedness_pct['pct']>=0.9].sort_values(by='pct',ascending=False).reset_index(drop=True)
display(flagged_columns)

lst_flagged = flagged_columns["Column Name"].to_list()
print(lst_flagged)

                     Column Name       pct
0                FireplacesTotal  1.000000
1         AboveGradeFinishedArea  1.000000
2                TaxAnnualAmount  1.000000
3                        TaxYear  1.000000
4       ElementarySchoolDistrict  1.000000
5                   BusinessType  1.000000
6                  CoveredSpaces  1.000000
7   MiddleOrJuniorSchoolDistrict  1.000000
8                   WaterfrontYN  0.999378
9         BelowGradeFinishedArea  0.994209
10                    BasementYN  0.980468
11             LotSizeDimensions  0.951458
12                   BuilderName  0.951113
13             BuildingAreaTotal  0.930023
14         CoBuyerAgentFirstName  0.909060

['FireplacesTotal', 'AboveGradeFinishedArea', 'TaxAnnualAmount', 'TaxYear', 'ElementarySchoolDistrict', 'BusinessType', 'CoveredSpaces', 'MiddleOrJuniorSchoolDistrict', 'WaterfrontYN', 'BelowGradeFinishedArea', 'BasementYN', 'LotSizeDimensions', 'BuilderName', 'BuildingAreaTotal', 'CoBuyerAgentFirstName']

In [80]:
cleaned_sold = residential_sold_df.drop(columns=lst_flagged)

print(f"Number of Columns before filtering out flagged columns: {len(all_sold_df.columns.to_list())} columns.")
print(f"Number of Columns after filtering out flagged columns: {len(cleaned_sold.columns.to_list())} columns.")
print(f"{len(lst_flagged)} columns are removed due to high percentage of missing values.")

Number of Columns before filtering out flagged columns: 86 columns.
Number of Columns after filtering out flagged columns: 71 columns.
15 columns are removed due to high percentage of missing values.

In [81]:
#Summary table for ClosePrice, LivingArea, and DaysOnMarket
cols = ["ClosePrice","LivingArea","DaysOnMarket"]

summary = cleaned_sold[cols].agg([
    "min","max","mean","median",
    lambda x: x.quantile(0.25),
    lambda x: x.quantile(0.75),
    lambda x: x.quantile(0.90),
    lambda x: x.quantile(0.95)
])

summary.index = ["min", "max", "mean", "median", "p25", "p75", "p90", "p95"]

display(summary.T)

,min,max,mean,median,p25,p75,p90,p95
ClosePrice,0.0,989500000.0,1.186901e+06,825000.0,575000.0,1300000.0,2065000.0,2850000.0
LivingArea,0.0,17021321.0,1.902954e+03,1642.0,1248.0,2218.0,2974.0,3555.6
DaysOnMarket,-288.0,12430.0,3.673675e+01,18.0,8.0,47.0,92.0,130.0

In [82]:
cleaned_sold.to_csv("cleaned_sold.csv",index=True,encoding="utf-8-sig")

In [83]:
# Combining FRED data
mortgage

#Resample

mortgage['year_month'] = mortgage['date'].dt.to_period('M')

monthly_mortgage = mortgage.groupby('year_month')["rate_30yr_fixed"].mean().reset_index()

display(monthly_mortgage)

    year_month  rate_30yr_fixed
0      1971-04           7.3100
1      1971-05           7.4250
2      1971-06           7.5300
3      1971-07           7.6040
4      1971-08           7.6975
..         ...              ...
657    2026-01           6.1025
658    2026-02           6.0475
659    2026-03           6.1775
660    2026-04           6.3320
661    2026-05           6.3650

[662 rows x 2 columns]

In [84]:
#Re-format date columns for Sold and Listing DFs

cleaned_sold["year_month"] = pd.to_datetime(cleaned_sold["CloseDate"]).dt.to_period("M")

cleaned_listings['year_month'] = pd.to_datetime(cleaned_listings['ListingContractDate']).dt.to_period('M')

In [85]:
sold_w_rates = cleaned_sold.merge(monthly_mortgage,on="year_month",how="left").reset_index(drop=True)

listing_w_rates = cleaned_listings.merge(monthly_mortgage,on="year_month",how="left").reset_index(drop=True)

display(sold_w_rates.head())
display(listing_w_rates.head())

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,CRMLS,CRMLS_SAND,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,CRMLS,CRMLS_SAND,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month,year_month,rate_30yr_fixed
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1,2024-01,6.6425
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,92677,NaN,254.00,5300.0,NaN,16 Palisades,2024,1,2024-01,6.6425
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024,1,2024-01,6.6425
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road,2024,1,2024-01,6.6425
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront,2024,1,2024-01,6.6425

In [86]:
print(sold_w_rates['rate_30yr_fixed'].isnull().sum())
print(listing_w_rates['rate_30yr_fixed'].isnull().sum())

display(sold_w_rates[['CloseDate','year_month','ClosePrice','rate_30yr_fixed']].head())

0
0

    CloseDate year_month  ClosePrice  rate_30yr_fixed
0  2024-01-26    2024-01    240000.0           6.6425
1  2024-01-05    2024-01    815000.0           6.6425
2  2024-01-05    2024-01    810000.0           6.6425
3  2024-01-30    2024-01    858000.0           6.6425
4  2024-01-29    2024-01   1890500.0           6.6425

In [87]:
# Convert file to CSV format
sold_w_rates.to_csv('enriched_sold.csv',index=True,encoding='utf-8-sig')
listing_w_rates.to_csv('enriched_listing.csv',index=True,encoding='utf-8-sig')

In [88]:
# Re-read 'enriched_sold.csv' with correct date format
enriched_sold = pd.read_csv('enriched_sold.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])
enriched_sold.info()

/var/folders/lb/w22468fj03vf0vnvwqj9nf840000gn/T/ipykernel_50165/1178815760.py:2: DtypeWarning: Columns (0: ListAgentAOR, 1: Flooring, 2: CloseDate, 3: Stories, 4: OriginatingSystemSubName, 5: Year, 6: BuyerAgencyCompensation, 7: lonfilled, 8: year_month) have mixed types. Specify dtype option on import or set low_memory=False.
  enriched_sold = pd.read_csv('enriched_sold.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])

<class 'pandas.DataFrame'>
RangeIndex: 411523 entries, 0 to 411522
Data columns (total 73 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   BuyerAgentAOR                360927 non-null  str
 1   ListAgentAOR                 365335 non-null  str
 2   Flooring                     263863 non-null  str
 3   ViewYN                       376351 non-null  object
 4   PoolPrivateYN                376018 non-null  object
 5   OriginalListPrice            410763 non-null  float64
 6   ListingKey                   411523 non-null  int64
 7   ListAgentEmail               368591 non-null  str
 8   CloseDate                    411523 non-null  datetime64[us]
 9   ClosePrice                   411521 non-null  float64
 10  ListAgentFirstName           408426 non-null  str
 11  ListAgentLastName            411485 non-null  str
 12  Latitude                     395592 non-null  float64
 13  Longitude                    395592 non-null  float64
 14  UnparsedAddress              411134 non-null  str
 15  PropertyType                 411523 non-null  str
 16  LivingArea                   411289 non-null  float64
 17  ListPrice                    411523 non-null  float64
 18  DaysOnMarket                 411523 non-null  int64
 19  ListOfficeName               411523 non-null  str
 20  BuyerOfficeName              404819 non-null  str
 21  CoListOfficeName             97414 non-null   str
 22  ListAgentFullName            411437 non-null  str
 23  CoListAgentFirstName         94320 non-null   str
 24  CoListAgentLastName          94561 non-null   str
 25  BuyerAgentMlsId              410999 non-null  str
 26  BuyerAgentFirstName          409529 non-null  str
 27  BuyerAgentLastName           411350 non-null  str
 28  AssociationFeeFrequency      171334 non-null  str
 29  ListingKeyNumeric            411523 non-null  int64
 30  MLSAreaMajor                 356382 non-null  str
 31  CountyOrParish               411523 non-null  str
 32  MlsStatus                    411523 non-null  str
 33  ElementarySchool             54803 non-null   str
 34  AttachedGarageYN             348686 non-null  object
 35  ParkingTotal                 411097 non-null  float64
 36  PropertySubType              410723 non-null  str
 37  LotSizeAcres                 379157 non-null  float64
 38  SubdivisionName              153190 non-null  str
 39  BuyerOfficeAOR               388507 non-null  str
 40  YearBuilt                    411151 non-null  float64
 41  StreetNumberNumeric          411046 non-null  float64
 42  ListingId                    411523 non-null  str
 43  BathroomsTotalInteger        411454 non-null  float64
 44  City                         411213 non-null  str
 45  BedroomsTotal                411513 non-null  float64
 46  ContractStatusChangeDate     410934 non-null  datetime64[us]
 47  PurchaseContractDate         411329 non-null  datetime64[us]
 48  ListingContractDate          411522 non-null  datetime64[us]
 49  StateOrProvince              411523 non-null  str
 50  MiddleOrJuniorSchool         55207 non-null   str
 51  FireplaceYN                  411196 non-null  object
 52  Stories                      348076 non-null  float64
 53  HighSchool                   71651 non-null   str
 54  Levels                       371792 non-null  str
 55  LotSizeArea                  379680 non-null  float64
 56  MainLevelBedrooms            238526 non-null  float64
 57  NewConstructionYN            380935 non-null  object
 58  GarageSpaces                 393881 non-null  float64
 59  HighSchoolDistrict           298423 non-null  str
 60  PostalCode                   411521 non-null  str
 61  AssociationFee               317207 non-null  float64
 62  LotSizeSquareFeet            379552 non-null  float64
 63  OriginatingSystemName        53172 non-null   str
 64  OriginatingSystemSubName     53172 non-null   str
 65  Year                         411523 non-null  int64
 66  Month                        411523 non-null  int64
 67  BuyerAgencyCompensationType  46136 non-null   str
 68  BuyerAgencyCompensation      46125 non-null   float64
 69  latfilled                    63884 non-null   object
 70  lonfilled                    63884 non-null   object
 71  year_month                   411523 non-null  str
 72  rate_30yr_fixed              411523 non-null  float64
dtypes: datetime64[us](4), float64(20), int64(5), object(7), str(37)
memory usage: 229.2+ MB

In [89]:
# Re-read 'enriched_listings.csv' with correct date format
enriched_listing = pd.read_csv('enriched_listing.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])
enriched_listing.info()

/var/folders/lb/w22468fj03vf0vnvwqj9nf840000gn/T/ipykernel_50165/2771643693.py:2: DtypeWarning: Columns (0: CloseDate, 1: StreetNumberNumeric) have mixed types. Specify dtype option on import or set low_memory=False.
  enriched_listing = pd.read_csv('enriched_listing.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])

<class 'pandas.DataFrame'>
RangeIndex: 563856 entries, 0 to 563855
Data columns (total 88 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             563043 non-null  float64
 1   ListingKey                    563856 non-null  int64
 2   ListAgentEmail                493182 non-null  str
 3   CloseDate                     178407 non-null  datetime64[us]
 4   ClosePrice                    157726 non-null  float64
 5   ListAgentFirstName            559470 non-null  str
 6   ListAgentLastName             563816 non-null  str
 7   Latitude                      483486 non-null  float64
 8   Longitude                     483486 non-null  float64
 9   UnparsedAddress               563107 non-null  str
 10  PropertyType                  563856 non-null  str
 11  LivingArea                    563284 non-null  float64
 12  ListPrice                     563856 non-null  float64
 13  DaysOnMarket                  563856 non-null  int64
 14  ListOfficeName                563856 non-null  str
 15  BuyerOfficeName               169196 non-null  str
 16  CoListOfficeName              126646 non-null  str
 17  ListAgentFullName             563762 non-null  str
 18  CoListAgentFirstName          126135 non-null  str
 19  CoListAgentLastName           126549 non-null  str
 20  BuyerAgentMlsId               171499 non-null  str
 21  BuyerAgentFirstName           170854 non-null  str
 22  BuyerAgentLastName            171620 non-null  str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       241161 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             563856 non-null  int64
 27  MLSAreaMajor                  487566 non-null  str
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                563856 non-null  str
 30  PropertyType.1                563856 non-null  str
 31  MlsStatus                     563856 non-null  str
 32  ElementarySchool              67278 non-null   str
 33  ListAgentFirstName.1          559470 non-null  str
 34  AttachedGarageYN              465442 non-null  object
 35  ParkingTotal                  563836 non-null  float64
 36  BuilderName                   26213 non-null   str
 37  PropertySubType               562554 non-null  str
 38  LotSizeAcres                  517569 non-null  float64
 39  SubdivisionName               207697 non-null  str
 40  BuyerOfficeAOR                157708 non-null  str
 41  YearBuilt                     562886 non-null  float64
 42  DaysOnMarket.1                563856 non-null  int64
 43  BuyerAgencyCompensationType   79013 non-null   str
 44  StreetNumberNumeric           562918 non-null  float64
 45  LivingArea.1                  563284 non-null  float64
 46  ListingId                     563856 non-null  str
 47  BathroomsTotalInteger         563799 non-null  float64
 48  City                          563259 non-null  str
 49  BuyerAgencyCompensation       78993 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             50029 non-null   float64
 52  BedroomsTotal                 563704 non-null  float64
 53  ContractStatusChangeDate      557634 non-null  datetime64[us]
 54  Longitude.1                   483486 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         15687 non-null   str
 57  PurchaseContractDate          282849 non-null  datetime64[us]
 58  ListingContractDate           563856 non-null  datetime64[us]
 59  BelowGradeFinishedArea        3219 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    483486 non-null  float64
 62  ListPrice.1                   563856 non-null  float64
 63  StateOrProvince               563789 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          67367 non-null   str
 66  FireplaceYN                   563260 non-null  object
 67  Stories                       465776 non-null  float64
 68  HighSchool                    88316 non-null   str
 69  Levels                        503496 non-null  str
 70  ListAgentLastName.1           563816 non-null  str
 71  CloseDate.1                   178407 non-null  str
 72  LotSizeDimensions             29486 non-null   str
 73  LotSizeArea                   518452 non-null  float64
 74  MainLevelBedrooms             307265 non-null  float64
 75  NewConstructionYN             524898 non-null  object
 76  GarageSpaces                  532632 non-null  float64
 77  HighSchoolDistrict            394361 non-null  str
 78  PostalCode                    563843 non-null  str
 79  BuyerOfficeName.1             169196 non-null  str
 80  AssociationFee                428680 non-null  float64
 81  LotSizeSquareFeet             518273 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             563107 non-null  str
 84  Year                          563856 non-null  int64
 85  Month                         563856 non-null  int64
 86  year_month                    563856 non-null  str
 87  rate_30yr_fixed               563856 non-null  float64
dtypes: datetime64[us](4), float64(34), int64(6), object(3), str(41)
memory usage: 378.6+ MB

In [90]:
# Checking if date follows the correct order

# Check if listing is after close

def list_after_close(listing_date,close_date):
    return listing_date > close_date # True = faulty value, False = correct value

def purchase_after_close(purchase_date,close_date):
    return purchase_date > close_date # True = faulty value, False = correct value


enriched_sold['list_after_close_flag']= enriched_sold.apply(
    lambda row: list_after_close(row['ListingContractDate'],row['CloseDate']),
                axis=1
)

enriched_sold['purchase_after_close_flag']=enriched_sold.apply(
    lambda row: purchase_after_close(row['PurchaseContractDate'],row['CloseDate']),
    axis=1
)

In [91]:
enriched_sold['negative_timeline_flag'] = (
    enriched_sold['list_after_close_flag'] | enriched_sold['purchase_after_close_flag']
)

enriched_sold_postimeline = enriched_sold[enriched_sold['negative_timeline_flag']==False].copy()
print(enriched_sold_postimeline.info())
display(enriched_sold_postimeline.head())

<class 'pandas.DataFrame'>
Index: 411222 entries, 0 to 411522
Data columns (total 76 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   BuyerAgentAOR                360683 non-null  str
 1   ListAgentAOR                 365090 non-null  str
 2   Flooring                     263746 non-null  str
 3   ViewYN                       376050 non-null  object
 4   PoolPrivateYN                375942 non-null  object
 5   OriginalListPrice            410660 non-null  float64
 6   ListingKey                   411222 non-null  int64
 7   ListAgentEmail               368300 non-null  str
 8   CloseDate                    411222 non-null  datetime64[us]
 9   ClosePrice                   411220 non-null  float64
 10  ListAgentFirstName           408148 non-null  str
 11  ListAgentLastName            411185 non-null  str
 12  Latitude                     395355 non-null  float64
 13  Longitude                    395355 non-null  float64
 14  UnparsedAddress              410833 non-null  str
 15  PropertyType                 411222 non-null  str
 16  LivingArea                   410988 non-null  float64
 17  ListPrice                    411222 non-null  float64
 18  DaysOnMarket                 411222 non-null  int64
 19  ListOfficeName               411222 non-null  str
 20  BuyerOfficeName              404535 non-null  str
 21  CoListOfficeName             97348 non-null   str
 22  ListAgentFullName            411136 non-null  str
 23  CoListAgentFirstName         94256 non-null   str
 24  CoListAgentLastName          94496 non-null   str
 25  BuyerAgentMlsId              410700 non-null  str
 26  BuyerAgentFirstName          409247 non-null  str
 27  BuyerAgentLastName           411050 non-null  str
 28  AssociationFeeFrequency      171268 non-null  str
 29  ListingKeyNumeric            411222 non-null  int64
 30  MLSAreaMajor                 356089 non-null  str
 31  CountyOrParish               411222 non-null  str
 32  MlsStatus                    411222 non-null  str
 33  ElementarySchool             54775 non-null   str
 34  AttachedGarageYN             348422 non-null  object
 35  ParkingTotal                 410796 non-null  float64
 36  PropertySubType              410423 non-null  str
 37  LotSizeAcres                 378899 non-null  float64
 38  SubdivisionName              153156 non-null  str
 39  BuyerOfficeAOR               388229 non-null  str
 40  YearBuilt                    410851 non-null  float64
 41  StreetNumberNumeric          410745 non-null  float64
 42  ListingId                    411222 non-null  str
 43  BathroomsTotalInteger        411153 non-null  float64
 44  City                         410915 non-null  str
 45  BedroomsTotal                411212 non-null  float64
 46  ContractStatusChangeDate     410633 non-null  datetime64[us]
 47  PurchaseContractDate         411028 non-null  datetime64[us]
 48  ListingContractDate          411221 non-null  datetime64[us]
 49  StateOrProvince              411222 non-null  str
 50  MiddleOrJuniorSchool         55182 non-null   str
 51  FireplaceYN                  410895 non-null  object
 52  Stories                      348016 non-null  float64
 53  HighSchool                   71625 non-null   str
 54  Levels                       371722 non-null  str
 55  LotSizeArea                  379422 non-null  float64
 56  MainLevelBedrooms            238523 non-null  float64
 57  NewConstructionYN            380643 non-null  object
 58  GarageSpaces                 393595 non-null  float64
 59  HighSchoolDistrict           298189 non-null  str
 60  PostalCode                   411220 non-null  str
 61  AssociationFee               317118 non-null  float64
 62  LotSizeSquareFeet            379294 non-null  float64
 63  OriginatingSystemName        53150 non-null   str
 64  OriginatingSystemSubName     53150 non-null   str
 65  Year                         411222 non-null  int64
 66  Month                        411222 non-null  int64
 67  BuyerAgencyCompensationType  46080 non-null   str
 68  BuyerAgencyCompensation      46069 non-null   float64
 69  latfilled                    63830 non-null   object
 70  lonfilled                    63830 non-null   object
 71  year_month                   411222 non-null  str
 72  rate_30yr_fixed              411222 non-null  float64
 73  list_after_close_flag        411222 non-null  bool
 74  purchase_after_close_flag    411222 non-null  bool
 75  negative_timeline_flag       411222 non-null  bool
dtypes: bool(3), datetime64[us](4), float64(20), int64(5), object(7), str(37)
memory usage: 233.3+ MB
None

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
5,NorthSanLuisObispo,NorthSanLuisObispo,NaN,True,False,2100000.0,1067652762,jenniferarielkennedy@gmail.com,2024-01-02,2100000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False

In [92]:
enriched_listing['list_after_close_flag']= enriched_listing.apply(
    lambda row: list_after_close(row['ListingContractDate'],row['CloseDate']),
                axis=1
)

enriched_listing['purchase_after_close_flag']=enriched_listing.apply(
    lambda row: purchase_after_close(row['PurchaseContractDate'],row['CloseDate']),
    axis=1
)

In [93]:
enriched_listing['negative_timeline_flag'] = (
    enriched_listing['list_after_close_flag'] | enriched_listing['purchase_after_close_flag']
)
enriched_listing_postimeline = enriched_listing[enriched_listing['negative_timeline_flag']==False].copy()
print(enriched_listing_postimeline.info())
display(enriched_listing_postimeline.head())

<class 'pandas.DataFrame'>
Index: 563523 entries, 0 to 563855
Data columns (total 91 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             562913 non-null  float64
 1   ListingKey                    563523 non-null  int64
 2   ListAgentEmail                492861 non-null  str
 3   CloseDate                     178074 non-null  datetime64[us]
 4   ClosePrice                    157411 non-null  float64
 5   ListAgentFirstName            559161 non-null  str
 6   ListAgentLastName             563484 non-null  str
 7   Latitude                      483280 non-null  float64
 8   Longitude                     483280 non-null  float64
 9   UnparsedAddress               562774 non-null  str
 10  PropertyType                  563523 non-null  str
 11  LivingArea                    562952 non-null  float64
 12  ListPrice                     563523 non-null  float64
 13  DaysOnMarket                  563523 non-null  int64
 14  ListOfficeName                563523 non-null  str
 15  BuyerOfficeName               168879 non-null  str
 16  CoListOfficeName              126573 non-null  str
 17  ListAgentFullName             563429 non-null  str
 18  CoListAgentFirstName          126064 non-null  str
 19  CoListAgentLastName           126477 non-null  str
 20  BuyerAgentMlsId               171167 non-null  str
 21  BuyerAgentFirstName           170537 non-null  str
 22  BuyerAgentLastName            171287 non-null  str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       241090 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             563523 non-null  int64
 27  MLSAreaMajor                  487259 non-null  str
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                563523 non-null  str
 30  PropertyType.1                563523 non-null  str
 31  MlsStatus                     563523 non-null  str
 32  ElementarySchool              67250 non-null   str
 33  ListAgentFirstName.1          559161 non-null  str
 34  AttachedGarageYN              465151 non-null  object
 35  ParkingTotal                  563503 non-null  float64
 36  BuilderName                   26213 non-null   str
 37  PropertySubType               562222 non-null  str
 38  LotSizeAcres                  517279 non-null  float64
 39  SubdivisionName               207644 non-null  str
 40  BuyerOfficeAOR                157399 non-null  str
 41  YearBuilt                     562555 non-null  float64
 42  DaysOnMarket.1                563523 non-null  int64
 43  BuyerAgencyCompensationType   78941 non-null   str
 44  StreetNumberNumeric           562585 non-null  float64
 45  LivingArea.1                  562952 non-null  float64
 46  ListingId                     563523 non-null  str
 47  BathroomsTotalInteger         563466 non-null  float64
 48  City                          562928 non-null  str
 49  BuyerAgencyCompensation       78921 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             50002 non-null   float64
 52  BedroomsTotal                 563371 non-null  float64
 53  ContractStatusChangeDate      557301 non-null  datetime64[us]
 54  Longitude.1                   483280 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         15647 non-null   str
 57  PurchaseContractDate          282516 non-null  datetime64[us]
 58  ListingContractDate           563523 non-null  datetime64[us]
 59  BelowGradeFinishedArea        3219 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    483280 non-null  float64
 62  ListPrice.1                   563523 non-null  float64
 63  StateOrProvince               563456 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          67340 non-null   str
 66  FireplaceYN                   562927 non-null  object
 67  Stories                       465691 non-null  float64
 68  HighSchool                    88288 non-null   str
 69  Levels                        503401 non-null  str
 70  ListAgentLastName.1           563484 non-null  str
 71  CloseDate.1                   178074 non-null  str
 72  LotSizeDimensions             29472 non-null   str
 73  LotSizeArea                   518162 non-null  float64
 74  MainLevelBedrooms             307264 non-null  float64
 75  NewConstructionYN             524583 non-null  object
 76  GarageSpaces                  532314 non-null  float64
 77  HighSchoolDistrict            394117 non-null  str
 78  PostalCode                    563510 non-null  str
 79  BuyerOfficeName.1             168879 non-null  str
 80  AssociationFee                428584 non-null  float64
 81  LotSizeSquareFeet             517983 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             562774 non-null  str
 84  Year                          563523 non-null  int64
 85  Month                         563523 non-null  int64
 86  year_month                    563523 non-null  str
 87  rate_30yr_fixed               563523 non-null  float64
 88  list_after_close_flag         563523 non-null  bool
 89  purchase_after_close_flag     563523 non-null  bool
 90  negative_timeline_flag        563523 non-null  bool
dtypes: bool(3), datetime64[us](4), float64(34), int64(6), object(3), str(41)
memory usage: 384.3+ MB
None

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1,2024-01,6.6425,False,False,False
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,5300.0,NaN,16 Palisades,2024,1,2024-01,6.6425,False,False,False
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,9404.0,NaN,1615 Waverly Road,2024,1,2024-01,6.6425,False,False,False
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,58232.0,NaN,2250 Indian Creek Road,2024,1,2024-01,6.6425,False,False,False
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,2250.0,NaN,317 E. Bayfront,2024,1,2024-01,6.6425,False,False,False

In [94]:
# Checking Longtitude & Latitude for valid format
enriched_listing_postimeline['Latitude']=pd.to_numeric(enriched_listing_postimeline['Latitude'],errors='coerce')
enriched_listing_postimeline['Longitude']=pd.to_numeric(enriched_listing_postimeline['Longitude'],errors='coerce')

enriched_sold_postimeline['Latitude']=pd.to_numeric(enriched_sold_postimeline['Latitude'],errors='coerce')
enriched_sold_postimeline['Longitude']=pd.to_numeric(enriched_sold_postimeline['Longitude'],errors='coerce')

def check_coord(longitude,latitude):
    if not pd.isna(longitude) and not pd.isna(latitude):
        if (longitude < 0) and (latitude != 0):
            if (32.5 <= latitude <= 42.0) and (-124.5 <= longitude <= -114.0):
                return True # True = coordinate is valid and pass all checks
    return False
            
enriched_listing_postimeline['correct_coord'] = enriched_listing_postimeline.apply(
    lambda row: check_coord(row['Longitude'],row['Latitude']),
    axis=1
)

enriched_sold_postimeline['correct_coord'] = enriched_sold_postimeline.apply(
    lambda row: check_coord(row['Longitude'],row['Latitude']),
    axis=1
)

In [95]:
print('Correct Coordinates Value Counts for Sold Data\n')
print(enriched_sold_postimeline['correct_coord'].value_counts())
print('\nCorrect Coordinates Value Counts for Listing Data\n')
print(enriched_listing_postimeline['correct_coord'].value_counts())

Correct Coordinates Value Counts for Sold Data

correct_coord
True     395266
False     15956
Name: count, dtype: int64

Correct Coordinates Value Counts for Listing Data

correct_coord
True     482953
False     80570
Name: count, dtype: int64

In [96]:
enriched_sold_v3 = enriched_sold_postimeline[enriched_sold_postimeline['correct_coord']==True]
print(enriched_sold_v3.info())
display(enriched_sold_v3.head())

<class 'pandas.DataFrame'>
Index: 395266 entries, 4 to 411522
Data columns (total 77 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   BuyerAgentAOR                357465 non-null  str
 1   ListAgentAOR                 361793 non-null  str
 2   Flooring                     252611 non-null  str
 3   ViewYN                       364657 non-null  object
 4   PoolPrivateYN                365044 non-null  object
 5   OriginalListPrice            394784 non-null  float64
 6   ListingKey                   395266 non-null  int64
 7   ListAgentEmail               352676 non-null  str
 8   CloseDate                    395266 non-null  datetime64[us]
 9   ClosePrice                   395264 non-null  float64
 10  ListAgentFirstName           392667 non-null  str
 11  ListAgentLastName            395229 non-null  str
 12  Latitude                     395266 non-null  float64
 13  Longitude                    395266 non-null  float64
 14  UnparsedAddress              394972 non-null  str
 15  PropertyType                 395266 non-null  str
 16  LivingArea                   395033 non-null  float64
 17  ListPrice                    395266 non-null  float64
 18  DaysOnMarket                 395266 non-null  int64
 19  ListOfficeName               395266 non-null  str
 20  BuyerOfficeName              389613 non-null  str
 21  CoListOfficeName             93862 non-null   str
 22  ListAgentFullName            395180 non-null  str
 23  CoListAgentFirstName         90845 non-null   str
 24  CoListAgentLastName          91068 non-null   str
 25  BuyerAgentMlsId              394749 non-null  str
 26  BuyerAgentFirstName          393600 non-null  str
 27  BuyerAgentLastName           395100 non-null  str
 28  AssociationFeeFrequency      164927 non-null  str
 29  ListingKeyNumeric            395266 non-null  int64
 30  MLSAreaMajor                 345942 non-null  str
 31  CountyOrParish               395266 non-null  str
 32  MlsStatus                    395266 non-null  str
 33  ElementarySchool             52713 non-null   str
 34  AttachedGarageYN             334727 non-null  object
 35  ParkingTotal                 395264 non-null  float64
 36  PropertySubType              394550 non-null  str
 37  LotSizeAcres                 365786 non-null  float64
 38  SubdivisionName              144149 non-null  str
 39  BuyerOfficeAOR               374123 non-null  str
 40  YearBuilt                    394896 non-null  float64
 41  StreetNumberNumeric          394898 non-null  float64
 42  ListingId                    395266 non-null  str
 43  BathroomsTotalInteger        395197 non-null  float64
 44  City                         395012 non-null  str
 45  BedroomsTotal                395256 non-null  float64
 46  ContractStatusChangeDate     395266 non-null  datetime64[us]
 47  PurchaseContractDate         395072 non-null  datetime64[us]
 48  ListingContractDate          395265 non-null  datetime64[us]
 49  StateOrProvince              395266 non-null  str
 50  MiddleOrJuniorSchool         53237 non-null   str
 51  FireplaceYN                  394939 non-null  object
 52  Stories                      338949 non-null  float64
 53  HighSchool                   69418 non-null   str
 54  Levels                       361824 non-null  str
 55  LotSizeArea                  366309 non-null  float64
 56  MainLevelBedrooms            238399 non-null  float64
 57  NewConstructionYN            364700 non-null  object
 58  GarageSpaces                 377649 non-null  float64
 59  HighSchoolDistrict           290762 non-null  str
 60  PostalCode                   395265 non-null  str
 61  AssociationFee               310243 non-null  float64
 62  LotSizeSquareFeet            366182 non-null  float64
 63  OriginatingSystemName        50091 non-null   str
 64  OriginatingSystemSubName     50091 non-null   str
 65  Year                         395266 non-null  int64
 66  Month                        395266 non-null  int64
 67  BuyerAgencyCompensationType  33421 non-null   str
 68  BuyerAgencyCompensation      33427 non-null   float64
 69  latfilled                    63700 non-null   object
 70  lonfilled                    63700 non-null   object
 71  year_month                   395266 non-null  str
 72  rate_30yr_fixed              395266 non-null  float64
 73  list_after_close_flag        395266 non-null  bool
 74  purchase_after_close_flag    395266 non-null  bool
 75  negative_timeline_flag       395266 non-null  bool
 76  correct_coord                395266 non-null  bool
dtypes: bool(4), datetime64[us](4), float64(20), int64(5), object(7), str(37)
memory usage: 224.7+ MB
None

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag,correct_coord
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
5,NorthSanLuisObispo,NorthSanLuisObispo,NaN,True,False,2100000.0,1067652762,jenniferarielkennedy@gmail.com,2024-01-02,2100000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
6,CoastalMendocino,CoastalMendocino,Tile,True,False,1950000.0,1063453216,kira@mendosir.com,2024-01-22,1950000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
8,PacificSouthwest,PacificSouthwest,"Stone,Wood",True,False,1550000.0,1061822266,MaxSellsSanDiego@gmail.com,2024-01-31,1485000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
9,PasadenaFoothills,PasadenaFoothills,Wood,True,False,999000.0,1061617422,kerry.kimble@theagencyre.com,2024-01-30,1130000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True

In [97]:
enriched_listing_v3 = enriched_listing_postimeline[enriched_listing_postimeline['correct_coord']==True]
print(enriched_listing_v3.info())
display(enriched_listing_v3.head())

<class 'pandas.DataFrame'>
Index: 482953 entries, 0 to 563855
Data columns (total 92 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             482486 non-null  float64
 1   ListingKey                    482953 non-null  int64
 2   ListAgentEmail                413086 non-null  str
 3   CloseDate                     154701 non-null  datetime64[us]
 4   ClosePrice                    141619 non-null  float64
 5   ListAgentFirstName            479996 non-null  str
 6   ListAgentLastName             482917 non-null  str
 7   Latitude                      482953 non-null  float64
 8   Longitude                     482953 non-null  float64
 9   UnparsedAddress               482376 non-null  str
 10  PropertyType                  482953 non-null  str
 11  LivingArea                    482413 non-null  float64
 12  ListPrice                     482953 non-null  float64
 13  DaysOnMarket                  482953 non-null  int64
 14  ListOfficeName                482953 non-null  str
 15  BuyerOfficeName               148646 non-null  str
 16  CoListOfficeName              110102 non-null  str
 17  ListAgentFullName             482859 non-null  str
 18  CoListAgentFirstName          109738 non-null  str
 19  CoListAgentLastName           110097 non-null  str
 20  BuyerAgentMlsId               150013 non-null  str
 21  BuyerAgentFirstName           149658 non-null  str
 22  BuyerAgentLastName            150127 non-null  str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       208472 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             482953 non-null  int64
 27  MLSAreaMajor                  428552 non-null  str
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                482953 non-null  str
 30  PropertyType.1                482953 non-null  str
 31  MlsStatus                     482953 non-null  str
 32  ElementarySchool              56108 non-null   str
 33  ListAgentFirstName.1          479996 non-null  str
 34  AttachedGarageYN              395311 non-null  object
 35  ParkingTotal                  482947 non-null  float64
 36  BuilderName                   22365 non-null   str
 37  PropertySubType               481969 non-null  str
 38  LotSizeAcres                  447094 non-null  float64
 39  SubdivisionName               169913 non-null  str
 40  BuyerOfficeAOR                138665 non-null  str
 41  YearBuilt                     482022 non-null  float64
 42  DaysOnMarket.1                482953 non-null  int64
 43  BuyerAgencyCompensationType   57008 non-null   str
 44  StreetNumberNumeric           482265 non-null  float64
 45  LivingArea.1                  482413 non-null  float64
 46  ListingId                     482953 non-null  str
 47  BathroomsTotalInteger         482900 non-null  float64
 48  City                          482620 non-null  str
 49  BuyerAgencyCompensation       57018 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             49945 non-null   float64
 52  BedroomsTotal                 482803 non-null  float64
 53  ContractStatusChangeDate      476934 non-null  datetime64[us]
 54  Longitude.1                   482953 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         14300 non-null   str
 57  PurchaseContractDate          243117 non-null  datetime64[us]
 58  ListingContractDate           482953 non-null  datetime64[us]
 59  BelowGradeFinishedArea        2955 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    482953 non-null  float64
 62  ListPrice.1                   482953 non-null  float64
 63  StateOrProvince               482953 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          56437 non-null   str
 66  FireplaceYN                   482373 non-null  object
 67  Stories                       408658 non-null  float64
 68  HighSchool                    74709 non-null   str
 69  Levels                        441360 non-null  str
 70  ListAgentLastName.1           482917 non-null  str
 71  CloseDate.1                   154701 non-null  str
 72  LotSizeDimensions             28544 non-null   str
 73  LotSizeArea                   447962 non-null  float64
 74  MainLevelBedrooms             277451 non-null  float64
 75  NewConstructionYN             444077 non-null  object
 76  GarageSpaces                  451851 non-null  float64
 77  HighSchoolDistrict            341441 non-null  str
 78  PostalCode                    482950 non-null  str
 79  BuyerOfficeName.1             148646 non-null  str
 80  AssociationFee                376469 non-null  float64
 81  LotSizeSquareFeet             447795 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             482376 non-null  str
 84  Year                          482953 non-null  int64
 85  Month                         482953 non-null  int64
 86  year_month                    482953 non-null  str
 87  rate_30yr_fixed               482953 non-null  float64
 88  list_after_close_flag         482953 non-null  bool
 89  purchase_after_close_flag     482953 non-null  bool
 90  negative_timeline_flag        482953 non-null  bool
 91  correct_coord                 482953 non-null  bool
dtypes: bool(4), datetime64[us](4), float64(34), int64(6), object(3), str(41)
memory usage: 329.8+ MB
None

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag,correct_coord
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,2220 Avenue Of The Stars 2704,2024,1,2024-01,6.6425,False,False,False,True
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,NaN,16 Palisades,2024,1,2024-01,6.6425,False,False,False,True
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,1615 Waverly Road,2024,1,2024-01,6.6425,False,False,False,True
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,NaN,2250 Indian Creek Road,2024,1,2024-01,6.6425,False,False,False,True
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,NaN,317 E. Bayfront,2024,1,2024-01,6.6425,False,False,False,True

In [98]:
# Find the difference in rows after checking for date and coordinates

sold_r_change = len(enriched_sold)-len(enriched_sold_v3)

listing_r_change = len(enriched_listing)-len(enriched_listing_v3)

print(f'After checking for correct timeline and coordinates, {sold_r_change} rows are removed for Sold data')
print(f'After checking for correct timeline and coordinates, {listing_r_change} rows are removed for Listing data')

After checking for correct timeline and coordinates, 16257 rows are removed for Sold data
After checking for correct timeline and coordinates, 80903 rows are removed for Listing data

In [99]:
enriched_sold_v3.to_csv('enriched_sold_v3.csv',index=True,encoding='utf-8-sig')
enriched_listing_v3.to_csv('enriched_listing_v3.csv',index=True,encoding='utf-8-sig')

# Week 6- Feature Engineering and Market Metrics

In [100]:
# Price Ratio
enriched_sold_v4 = enriched_sold_v3.copy()
enriched_sold_v4['price_ratio']=enriched_sold_v3['ClosePrice']/enriched_sold_v3['OriginalListPrice']

#Price per SqFt
enriched_sold_v4['ppsf']=enriched_sold_v3['ClosePrice']/enriched_sold_v3['LivingArea']

#Time Series
enriched_sold_v4['yrmo'] = (
    enriched_sold_v3['CloseDate'].dt.year * 100
    + enriched_sold_v3['CloseDate'].dt.month
)

#Listing duration
enriched_sold_v4['listing_duration']=enriched_sold_v3['PurchaseContractDate']-enriched_sold_v3['ListingContractDate']

#Close Duration
enriched_sold_v4['close_duration']=enriched_sold_v3['CloseDate']-enriched_sold_v3['PurchaseContractDate']

In [101]:
# Price Ratio
enriched_listing_v4 = enriched_listing_v3.copy()
enriched_listing_v4['price_ratio']=enriched_listing_v4['ClosePrice']/enriched_listing_v4['OriginalListPrice']

#Price per SqFt
enriched_listing_v4['ppsf']=enriched_listing_v4['ClosePrice']/enriched_listing_v4['LivingArea']

#Time Series
enriched_listing_v4['yrmo'] = (
    enriched_listing_v4['CloseDate'].dt.year * 100
    + enriched_listing_v4['CloseDate'].dt.month
)

#Listing duration
enriched_listing_v4['listing_duration']=enriched_listing_v4['PurchaseContractDate']-enriched_listing_v4['ListingContractDate']

#Close Duration
enriched_listing_v4['close_duration']=enriched_listing_v4['CloseDate']-enriched_listing_v4['PurchaseContractDate']

In [102]:
# Descriptive stats table 

prop_type_df = enriched_sold_v4.groupby(['PropertyType','PropertySubType']).agg(
        n_sales=("ClosePrice", "size"),
        avg_close_price=("ClosePrice", "mean"),
        avg_price_ratio=("price_ratio", "mean"),
        avg_ppsf=("ppsf", "mean"),
        avg_days_on_market=("DaysOnMarket", "mean"),
        avg_listing_duration=("listing_duration","mean"),
        avg_close_duration=("close_duration","mean")
).dropna().reset_index().transpose().T
prop_type_df

,PropertyType,PropertySubType,n_sales,avg_close_price,avg_price_ratio,avg_ppsf,avg_days_on_market,avg_listing_duration,avg_close_duration
0,Residential,BoatSlip,80,216073.75,0.914159,2049.806818,58.0625,63 days 03:18:00,19 days 11:24:00
1,Residential,Cabin,461,282457.264642,0.899684,620.751745,77.058568,84 days 23:16:16.138828,36 days 06:27:19.913232
2,Residential,CoOwnership,18,749694.388889,56.533748,485.708763,39.777778,46 days 16:00:00,54 days 09:20:00
3,Residential,Condominium,64768,880463.657357,27.175316,inf,41.47139,48 days 22:03:10.228979,30 days 11:26:59.646802
4,Residential,DeededParking,6,575833.333333,0.837471,410.512905,21.333333,22 days 04:00:00,28 days 04:00:00
5,Residential,Duplex,2183,1225230.057261,446.813839,638.748877,42.090243,54 days 13:09:35.538250,38 days 06:41:03.765460
6,Residential,Farm,10,2045400.0,1.03463,999.953426,35.0,35 days 00:00:00,77 days 12:00:00
7,Residential,Loft,27,698881.07,0.984511,550.111682,62.740741,69 days 08:53:20,38 days 03:33:20
8,Residential,ManufacturedHome,29,305574.482759,0.940673,207.8192,60.448276,66 days 06:37:14.482758,37 days 00:00:00
9,Residential,ManufacturedOnLand,5233,352535.194867,1.298178,inf,57.771833,68 days 13:19:39.820370,40 days 12:11:08.679533
10,Residential,MixedUse,203,992474.931034,0.889201,503.753096,83.482759,95 days 13:00:17.733990,47 days 10:24:14.187192
11,Residential,MobileHome,50,484960.0,0.888672,inf,73.32,81 days 13:55:12,15 days 04:19:12
12,Residential,OwnYourOwn,57,343915.894737,0.929178,inf,65.298246,72 days 13:28:25.263157,38 days 10:56:50.526315
13,Residential,Quadruplex,141,1444902.141844,0.991866,442.093018,57.815603,79 days 02:43:24.255319,41 days 17:42:07.659574
14,Residential,SingleFamilyResidence,296480,1280016.193844,inf,inf,36.082677,44 days 07:42:07.955780,31 days 14:37:46.905579
15,Residential,StockCooperative,1639,391489.979866,1.556419,406.629446,37.365467,47 days 16:11:42.867602,47 days 04:20:03.660768
16,Residential,Studio,11,350953.636364,0.9573,692.592624,43.363636,57 days 00:00:00,38 days 06:32:43.636363
17,Residential,Timeshare,15,443700.0,0.915588,325.496773,75.2,81 days 12:48:00,32 days 08:00:00
18,Residential,Townhouse,22806,998944.97513,44.081393,642.291423,32.165044,38 days 13:37:37.402289,31 days 00:27:28.637978
19,Residential,Triplex,333,1296876.399399,1.029089,580.3717,56.024024,67 days 22:59:27.567567,44 days 23:47:01.621621

In [103]:
county_or_parish_df = enriched_sold_v4.groupby(['CountyOrParish','MLSAreaMajor']).agg(
        n_sales=("ClosePrice", "size"),
        avg_close_price=("ClosePrice", "mean"),
        avg_price_ratio=("price_ratio", "mean"),
        avg_ppsf=("ppsf", "mean"),
        avg_days_on_market=("DaysOnMarket", "mean"),
        avg_listing_duration=("listing_duration","mean"),
        avg_close_duration=("close_duration","mean")
).dropna().reset_index().transpose().T
county_or_parish_df

,CountyOrParish,MLSAreaMajor,n_sales,avg_close_price,avg_price_ratio,avg_ppsf,avg_days_on_market,avg_listing_duration,avg_close_duration
0,Alameda,699 - Not Defined,1481,1254223.711006,1.025012,772.058778,26.675895,27 days 03:34:52.910195,28 days 16:28:50.722484
1,Alameda,BERK - Berkeley,3,574333.0,1.090453,576.71224,27.666667,47 days 00:00:00,28 days 08:00:00
2,Amador,699 - Not Defined,3,301666.666667,0.87048,149.641577,87.0,87 days 08:00:00,8 days 00:00:00
3,Butte,699 - Not Defined,53,420790.566038,20.535733,251.289644,65.226415,73 days 04:04:31.698113,37 days 13:07:55.471698
4,Butte,PARA - Paradise,57,393840.035088,0.961803,258.937192,70.052632,78 days 23:09:28.421052,35 days 10:56:50.526315
...,...,...,...,...,...,...,...,...,...
1224,Ventura,WEH - West Hills,1,1075000.0,1.075001,379.858657,9.0,16 days 00:00:00,68 days 00:00:00
1225,Ventura,WV - Westlake Village,705,2108667.545929,0.977827,694.163968,55.08227,58 days 16:11:35.454545,22 days 06:12:16.363636
1226,Ventura,WW - Wagon Wheel,2,734800.0,0.966142,349.157414,39.5,44 days 12:00:00,21 days 12:00:00
1227,Yolo,699 - Not Defined,12,521500.0,1.026406,321.176475,35.833333,42 days 04:00:00,33 days 02:00:00
1228,Yuba,699 - Not Defined,9,429388.888889,0.917627,288.486082,122.222222,129 days 08:00:00,35 days 16:00:00

In [104]:
lprop_type_df = enriched_listing_v4.groupby(['ListOfficeName','BuyerOfficeName']).agg(
        n_sales=("ClosePrice", "size"),
        avg_close_price=("ClosePrice", "mean"),
        avg_price_ratio=("price_ratio", "mean"),
        avg_ppsf=("ppsf", "mean"),
        avg_days_on_market=("DaysOnMarket", "mean"),
        avg_listing_duration=("listing_duration","mean"),
        avg_close_duration=("close_duration","mean")
).dropna().reset_index().transpose().T
prop_type_df

,PropertyType,PropertySubType,n_sales,avg_close_price,avg_price_ratio,avg_ppsf,avg_days_on_market,avg_listing_duration,avg_close_duration
0,Residential,BoatSlip,80,216073.75,0.914159,2049.806818,58.0625,63 days 03:18:00,19 days 11:24:00
1,Residential,Cabin,461,282457.264642,0.899684,620.751745,77.058568,84 days 23:16:16.138828,36 days 06:27:19.913232
2,Residential,CoOwnership,18,749694.388889,56.533748,485.708763,39.777778,46 days 16:00:00,54 days 09:20:00
3,Residential,Condominium,64768,880463.657357,27.175316,inf,41.47139,48 days 22:03:10.228979,30 days 11:26:59.646802
4,Residential,DeededParking,6,575833.333333,0.837471,410.512905,21.333333,22 days 04:00:00,28 days 04:00:00
5,Residential,Duplex,2183,1225230.057261,446.813839,638.748877,42.090243,54 days 13:09:35.538250,38 days 06:41:03.765460
6,Residential,Farm,10,2045400.0,1.03463,999.953426,35.0,35 days 00:00:00,77 days 12:00:00
7,Residential,Loft,27,698881.07,0.984511,550.111682,62.740741,69 days 08:53:20,38 days 03:33:20
8,Residential,ManufacturedHome,29,305574.482759,0.940673,207.8192,60.448276,66 days 06:37:14.482758,37 days 00:00:00
9,Residential,ManufacturedOnLand,5233,352535.194867,1.298178,inf,57.771833,68 days 13:19:39.820370,40 days 12:11:08.679533
10,Residential,MixedUse,203,992474.931034,0.889201,503.753096,83.482759,95 days 13:00:17.733990,47 days 10:24:14.187192
11,Residential,MobileHome,50,484960.0,0.888672,inf,73.32,81 days 13:55:12,15 days 04:19:12
12,Residential,OwnYourOwn,57,343915.894737,0.929178,inf,65.298246,72 days 13:28:25.263157,38 days 10:56:50.526315
13,Residential,Quadruplex,141,1444902.141844,0.991866,442.093018,57.815603,79 days 02:43:24.255319,41 days 17:42:07.659574
14,Residential,SingleFamilyResidence,296480,1280016.193844,inf,inf,36.082677,44 days 07:42:07.955780,31 days 14:37:46.905579
15,Residential,StockCooperative,1639,391489.979866,1.556419,406.629446,37.365467,47 days 16:11:42.867602,47 days 04:20:03.660768
16,Residential,Studio,11,350953.636364,0.9573,692.592624,43.363636,57 days 00:00:00,38 days 06:32:43.636363
17,Residential,Timeshare,15,443700.0,0.915588,325.496773,75.2,81 days 12:48:00,32 days 08:00:00
18,Residential,Townhouse,22806,998944.97513,44.081393,642.291423,32.165044,38 days 13:37:37.402289,31 days 00:27:28.637978
19,Residential,Triplex,333,1296876.399399,1.029089,580.3717,56.024024,67 days 22:59:27.567567,44 days 23:47:01.621621

In [105]:
lcounty_or_parish_df = enriched_listing_v4.groupby(['CountyOrParish','MLSAreaMajor']).agg(
        n_sales=("ClosePrice", "size"),
        avg_close_price=("ClosePrice", "mean"),
        avg_price_ratio=("price_ratio", "mean"),
        avg_ppsf=("ppsf", "mean"),
        avg_days_on_market=("DaysOnMarket", "mean"),
        avg_listing_duration=("listing_duration","mean"),
        avg_close_duration=("close_duration","mean")
).dropna().reset_index().transpose().T
lcounty_or_parish_df

,CountyOrParish,MLSAreaMajor,n_sales,avg_close_price,avg_price_ratio,avg_ppsf,avg_days_on_market,avg_listing_duration,avg_close_duration
0,Alameda,699 - Not Defined,2071,1248141.2,1.032601,766.425421,21.099952,15 days 16:55:01.910828,25 days 20:56:10.212765
1,Alameda,BERK - Berkeley,5,466499.5,1.152499,560.519401,29.2,18 days 16:00:00,34 days 12:00:00
2,Butte,699 - Not Defined,93,385846.153846,0.932863,217.935622,35.365591,52 days 01:36:00,33 days 03:41:32.307692
3,Butte,PARA - Paradise,93,426349.958333,0.959068,265.207359,27.569892,48 days 17:08:34.285714,32 days 15:00:00
4,Calaveras,699 - Not Defined,13,589000.0,0.98183,297.324584,44.923077,38 days 00:00:00,62 days 00:00:00
...,...,...,...,...,...,...,...,...,...
1115,Ventura,VTU - Ventura,297,803427.329114,0.970287,602.170806,24.188552,34 days 07:51:55.966386,26 days 20:57:43.291139
1116,Ventura,WEH - West Hills,7,1075000.0,1.075001,379.858657,24.142857,22 days 12:00:00,68 days 00:00:00
1117,Ventura,WV - Westlake Village,993,1935408.883895,0.982381,691.216488,22.321249,29 days 13:17:25.161290,19 days 19:41:07.415730
1118,Yolo,699 - Not Defined,25,508750.0,1.097485,326.241522,23.8,32 days 20:34:17.142857,27 days 17:08:34.285714
1119,Yuba,699 - Not Defined,17,401500.0,0.990667,277.562687,46.705882,16 days 08:00:00,31 days 12:00:00

# Week 7- Outlier Detection and Data Quality

In [106]:
def flagging_outlier(df,column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return (df[column] < lower) | (df[column] > upper)

In [107]:
enriched_sold_v5 = enriched_sold_v4.copy()
enriched_sold_v5 = enriched_sold_v5[
    (enriched_sold_v5['ClosePrice'] > 0) &
    (enriched_sold_v5['LivingArea'] > 0) &
    (enriched_sold_v5['DaysOnMarket'] > 0)
]

In [108]:
enriched_listing_v5 = enriched_listing_v4.copy()
enriched_listing_v5 = enriched_listing_v5[
    (enriched_listing_v5['ClosePrice'] > 0) &
    (enriched_listing_v5['LivingArea'] > 0) &
    (enriched_listing_v5['DaysOnMarket'] > 0)
]

In [109]:
enriched_sold_v6 = enriched_sold_v5.copy()
enriched_sold_v6['price_outlier']=flagging_outlier(enriched_sold_v5,'ClosePrice')
enriched_sold_v6['area_outlier']=flagging_outlier(enriched_sold_v5,'LivingArea')
enriched_sold_v6['daysonmarket_outlier']=flagging_outlier(enriched_sold_v5,'DaysOnMarket')

In [110]:
enriched_listing_v6 = enriched_sold_v5.copy()
enriched_listing_v6['price_outlier']=flagging_outlier(enriched_listing_v6,'ClosePrice')
enriched_listing_v6['area_outlier']=flagging_outlier(enriched_listing_v6,'LivingArea')
enriched_listing_v6['daysonmarket_outlier']=flagging_outlier(enriched_listing_v6,'DaysOnMarket')

In [111]:
enriched_sold_v6.reset_index(drop=True).head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,negative_timeline_flag,correct_coord,price_ratio,ppsf,yrmo,listing_duration,close_duration,price_outlier,area_outlier,daysonmarket_outlier
0,PasadenaFoothills,PasadenaFoothills,Wood,True,False,999000.0,1061617422,kerry.kimble@theagencyre.com,2024-01-30,1130000.0,...,False,True,1.131131,529.026217,202401,1 days,17 days,False,False,False
1,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,True,False,1050000.0,1060223286,aliciao@kw.com,2024-01-16,1060000.0,...,False,True,1.009524,552.947314,202401,34 days,6 days,False,False,False
2,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,False,650000.0,1059869734,thinkjamesyou@gmail.com,2024-01-31,650000.0,...,False,True,1.000000,464.285714,202401,6 days,1 days,False,False,False
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,"Carpet,Tile,Wood",False,NaN,10750000.0,1059617256,jonathan@resnickandnash.com,2024-01-31,9635000.0,...,False,True,0.896279,1780.961183,202401,25 days,50 days,True,True,False
4,Southland,Southland,NaN,False,False,900000.0,1059560972,julian@getrealvalley.com,2024-01-31,762000.0,...,False,True,0.846667,485.350318,202401,1 days,0 days,False,False,False

In [112]:
enriched_listing_v6.reset_index(drop=True).head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,negative_timeline_flag,correct_coord,price_ratio,ppsf,yrmo,listing_duration,close_duration,price_outlier,area_outlier,daysonmarket_outlier
0,PasadenaFoothills,PasadenaFoothills,Wood,True,False,999000.0,1061617422,kerry.kimble@theagencyre.com,2024-01-30,1130000.0,...,False,True,1.131131,529.026217,202401,1 days,17 days,False,False,False
1,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,True,False,1050000.0,1060223286,aliciao@kw.com,2024-01-16,1060000.0,...,False,True,1.009524,552.947314,202401,34 days,6 days,False,False,False
2,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,False,650000.0,1059869734,thinkjamesyou@gmail.com,2024-01-31,650000.0,...,False,True,1.000000,464.285714,202401,6 days,1 days,False,False,False
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,"Carpet,Tile,Wood",False,NaN,10750000.0,1059617256,jonathan@resnickandnash.com,2024-01-31,9635000.0,...,False,True,0.896279,1780.961183,202401,25 days,50 days,True,True,False
4,Southland,Southland,NaN,False,False,900000.0,1059560972,julian@getrealvalley.com,2024-01-31,762000.0,...,False,True,0.846667,485.350318,202401,1 days,0 days,False,False,False

In [113]:
enriched_sold_v7 = enriched_sold_v6[
    (enriched_sold_v6['price_outlier']==False)
    &(enriched_sold_v6['area_outlier']==False)
    &(enriched_sold_v6['daysonmarket_outlier']==False)
].copy()

enriched_sold_v7.dropna(subset=['City','PropertySubType'])
print(enriched_sold_v7['daysonmarket_outlier'].value_counts())

daysonmarket_outlier
False    322493
Name: count, dtype: int64

In [ ]:
enriched_listing_v7 = enriched_listing_v6[
    (enriched_sold_v6['price_outlier']==False)
    &(enriched_sold_v6['area_outlier']==False)
    &(enriched_sold_v6['daysonmarket_outlier']==False)
].copy()

enriched_listing_v7.dropna(subset=['City','PropertySubType'])

City
San Diego            14452
Los Angeles          12211
San Jose              6233
Riverside             4401
Long Beach            4389
                     ...
Keene                    1
Palo Cedro               1
Belvedere Tiburon        1
Bullhead City            1
Lindsay                  1
Name: count, Length: 1062, dtype: int64

In [115]:
before_summary = enriched_sold_v6[['ClosePrice','LivingArea','DaysOnMarket']].describe()
before_summary

         ClosePrice    LivingArea   DaysOnMarket
count  3.793510e+05  3.793510e+05  379351.000000
mean   1.160541e+06  1.905143e+03      38.700296
std    5.974727e+06  2.765097e+04      53.732882
min    1.150000e+00  1.000000e+00       1.000000
25%    5.700000e+05  1.248000e+03       8.000000
50%    8.110000e+05  1.643000e+03      20.000000
75%    1.275000e+06  2.216000e+03      50.000000
max    9.895000e+08  1.702132e+07   12430.000000

In [116]:
after_summary = enriched_sold_v7[['ClosePrice','LivingArea','DaysOnMarket']].describe()
after_summary

         ClosePrice     LivingArea   DaysOnMarket
count  3.224930e+05  322493.000000  322493.000000
mean   8.843318e+05    1675.851141      28.111702
std    4.483657e+05     625.439479      26.307220
min    1.150000e+00       1.000000       1.000000
25%    5.590000e+05    1215.000000       8.000000
50%    7.750000e+05    1571.000000      18.000000
75%    1.125000e+06    2037.000000      41.000000
max    2.332000e+06    3668.000000     113.000000

In [117]:
lbefore_summary = enriched_listing_v6[['ClosePrice','LivingArea','DaysOnMarket']].describe()
lbefore_summary

         ClosePrice    LivingArea   DaysOnMarket
count  3.793510e+05  3.793510e+05  379351.000000
mean   1.160541e+06  1.905143e+03      38.700296
std    5.974727e+06  2.765097e+04      53.732882
min    1.150000e+00  1.000000e+00       1.000000
25%    5.700000e+05  1.248000e+03       8.000000
50%    8.110000e+05  1.643000e+03      20.000000
75%    1.275000e+06  2.216000e+03      50.000000
max    9.895000e+08  1.702132e+07   12430.000000

In [118]:
lafter_summary = enriched_listing_v7[['ClosePrice','LivingArea','DaysOnMarket']].describe()
lafter_summary

         ClosePrice     LivingArea   DaysOnMarket
count  3.224930e+05  322493.000000  322493.000000
mean   8.843318e+05    1675.851141      28.111702
std    4.483657e+05     625.439479      26.307220
min    1.150000e+00       1.000000       1.000000
25%    5.590000e+05    1215.000000       8.000000
50%    7.750000e+05    1571.000000      18.000000
75%    1.125000e+06    2037.000000      41.000000
max    2.332000e+06    3668.000000     113.000000

In [119]:
#Change in number of values 

print(f'Difference in rows after filtering out outliers for sold dataset: {len(enriched_sold_v6)-len(enriched_sold_v7)} rows.')
print(f'Difference in rows after filtering out outliers for listing dataset: {len(enriched_listing_v6)-len(enriched_listing_v7)} rows.')

Difference in rows after filtering out outliers for sold dataset: 56858 rows.
Difference in rows after filtering out outliers for listing dataset: 56858 rows.

In [120]:
enriched_sold_v7.to_csv('completed_sold.csv',index=True,encoding='utf-8-sig')

In [121]:
enriched_listing_v7.to_csv('completed_listing.csv',index=True,encoding='utf-8-sig')

In [122]:
enriched_sold_v5['correct_coord'].value_counts()

correct_coord
True    379351
Name: count, dtype: int64

In [123]:
print(enriched_sold_v5.columns)

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'PoolPrivateYN',
       'OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'AssociationFeeFrequency', 'ListingKeyNumeric',
       'MLSAreaMajor', 'CountyOrParish', 'MlsStatus', 'ElementarySchool',
       'AttachedGarageYN', 'ParkingTotal', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BedroomsTotal',
       'ContractStatusChangeDate', 'PurchaseContractDate',
       'ListingContractDate', 'StateOrProvince', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'LotSizeArea',
       'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces',
       'HighSchoolDistrict', 'PostalCode', 'AssociationFee',
       'LotSizeSquareFeet', 'OriginatingSystemName',
       'OriginatingSystemSubName', 'Year', 'Month',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled', 'year_month', 'rate_30yr_fixed', 'list_after_close_flag',
       'purchase_after_close_flag', 'negative_timeline_flag', 'correct_coord',
       'price_ratio', 'ppsf', 'yrmo', 'listing_duration', 'close_duration'],
      dtype='str')

In [124]:
enriched_listing_v3['PropertyType'].value_counts()

PropertyType
Residential    482953
Name: count, dtype: int64

In [125]:
enriched_listing_v7[enriched_listing_v7['CloseDate'].dt.year==2025]

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,negative_timeline_flag,correct_coord,price_ratio,ppsf,yrmo,listing_duration,close_duration,price_outlier,area_outlier,daysonmarket_outlier
186257,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,"Laminate,Tile",True,False,560000.0,1104126717,reganmears@gmail.com,2025-01-31,560000.0,...,False,True,1.000000,680.437424,202501,2 days,22 days,False,False,False
186285,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,NaN,True,NaN,950000.0,1103661593,karlynnelson7@gmail.com,2025-01-30,950000.0,...,False,True,1.000000,775.510204,202501,22 days,26 days,False,False,False
186327,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,True,False,1080000.0,1103384327,RealtorEricaJung@Gmail.com,2025-01-29,1050000.0,...,False,True,0.972222,647.748304,202501,2 days,1 days,False,False,False
186333,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,False,1199000.0,1103334693,james@larealproperty.com,2025-01-22,1350000.0,...,False,True,1.125938,1223.934723,202501,4 days,41 days,False,False,False
186334,CaliforniaDesert,CaliforniaDesert,"Carpet,Stone,Tile",True,True,1120000.0,1103326366,dianeflaherty@outlook.com,2025-01-30,1090000.0,...,False,True,0.973214,337.356855,202501,4 days,1 days,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359408,NorthSanDiegoCounty,NorthSanDiegoCounty,NaN,False,False,399999.0,1090210736,listings@bottrellteam.com,2025-12-02,390000.0,...,False,True,0.975002,628.019324,202512,46 days,382 days,False,False,False
359413,Southland,Southland,NaN,True,False,699000.0,1088930596,Bandele@BogunEnterprises.com,2025-12-23,700000.0,...,False,True,1.001431,274.079875,202512,11 days,440 days,False,False,False
359433,TheInlandGateway,TheInlandGateway,"Carpet,Laminate,Tile",False,False,1706840.0,1079985234,lolivo@taylormorrison.com,2025-12-19,1562570.0,...,False,True,0.915475,477.266341,202512,68 days,422 days,False,False,False
359450,PacificWest,PacificWest,"Tile,Wood",False,False,699900.0,1076635310,josieyourrealtor@gmail.com,2025-12-10,684900.0,...,False,True,0.978568,596.602787,202512,499 days,40 days,False,False,False
359467,TheInlandGateway,TheInlandGateway,NaN,True,False,494900.0,1035520905,brian@cohen-realty.com,2025-12-15,380000.0,...,False,True,0.767832,261.707989,202512,954 days,26 days,False,False,False