# Weeks 1–2 – Dataset Exploration and Python Setup
## Main Tasks:
+ Understand the structure and content of the data before any analysis begins

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# Making a un
listing_dfs = []

for year in [2024, 2026]:
    for month in range(1, 13):
        fname = f"CRMLSListing{year}{month:02d}.csv"
        try:
            df = pd.read_csv(fname,parse_dates=['CloseDate'])
            df['Year'] = year
            df['Month'] = month
            listing_dfs.append(df)
        except FileNotFoundError:
            # Skip months that don't exist yet
            continue

# If you want one big DataFrame:
all_listings_df = pd.concat(listing_dfs, ignore_index=True)

In [10]:
all_listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 451075 entries, 0 to 451074
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             449300 non-null  float64
 1   ListingKey                    451075 non-null  int64
 2   ListAgentEmail                418402 non-null  object
 3   CloseDate                     106708 non-null  datetime64[ns]
 4   ClosePrice                    92307 non-null   float64
 5   ListAgentFirstName            448276 non-null  object
 6   ListAgentLastName             451040 non-null  object
 7   Latitude                      344756 non-null  float64
 8   Longitude                     345261 non-null  float64
 9   UnparsedAddress               449916 non-null  object
 10  PropertyType                  451075 non-null  object
 11  LivingArea                    393411 non-null  float64
 12  ListPrice                     449924 non-null  float64
 13  DaysOnMarket                  451075 non-null  int64
 14  ListOfficeName                451075 non-null  object
 15  BuyerOfficeName               100257 non-null  object
 16  CoListOfficeName              88740 non-null   object
 17  ListAgentFullName             451001 non-null  object
 18  CoListAgentFirstName          88324 non-null   object
 19  CoListAgentLastName           88574 non-null   object
 20  BuyerAgentMlsId               101313 non-null  object
 21  BuyerAgentFirstName           101034 non-null  object
 22  BuyerAgentLastName            101519 non-null  object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       129493 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             451075 non-null  int64
 27  MLSAreaMajor                  400464 non-null  object
 28  TaxAnnualAmount               3393 non-null    float64
 29  CountyOrParish                451074 non-null  object
 30  PropertyType.1                451075 non-null  object
 31  MlsStatus                     451075 non-null  object
 32  ElementarySchool              42722 non-null   object
 33  ListAgentFirstName.1          448276 non-null  object
 34  AttachedGarageYN              297476 non-null  object
 35  ParkingTotal                  422247 non-null  float64
 36  BuilderName                   15178 non-null   object
 37  PropertySubType               394638 non-null  object
 38  LotSizeAcres                  405895 non-null  float64
 39  SubdivisionName               149520 non-null  object
 40  BuyerOfficeAOR                96668 non-null   object
 41  YearBuilt                     413743 non-null  float64
 42  DaysOnMarket.1                451075 non-null  int64
 43  BuyerAgencyCompensationType   123538 non-null  object
 44  StreetNumberNumeric           449035 non-null  float64
 45  LivingArea.1                  393411 non-null  float64
 46  ListingId                     451075 non-null  object
 47  BathroomsTotalInteger         412767 non-null  float64
 48  City                          450444 non-null  object
 49  BuyerAgencyCompensation       123519 non-null  float64
 50  TaxYear                       480 non-null     float64
 51  BuildingAreaTotal             72681 non-null   float64
 52  BedroomsTotal                 395086 non-null  float64
 53  ContractStatusChangeDate      447028 non-null  object
 54  Longitude.1                   345261 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         7728 non-null    object
 57  PurchaseContractDate          178815 non-null  object
 58  ListingContractDate           451075 non-null  object
 59  BelowGradeFinishedArea        1629 non-null    float64
 60  BusinessType                  3390 non-null    object
 61  Latitude.1                    344756 non-null  float64
 62  ListPrice.1                   449924 non-null  float64
 63  StateOrProvince               451047 non-null  object
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          42857 non-null   object
 66  FireplaceYN                   384621 non-null  object
 67  Stories                       330095 non-null  float64
 68  HighSchool                    55999 non-null   object
 69  Levels                        360446 non-null  object
 70  ListAgentLastName.1           451040 non-null  object
 71  CloseDate.1                   106708 non-null  object
 72  LotSizeDimensions             25516 non-null   object
 73  LotSizeArea                   407962 non-null  float64
 74  MainLevelBedrooms             206168 non-null  float64
 75  NewConstructionYN             390191 non-null  object
 76  GarageSpaces                  364695 non-null  float64
 77  HighSchoolDistrict            271742 non-null  object
 78  PostalCode                    450942 non-null  object
 79  BuyerOfficeName.1             100257 non-null  object
 80  AssociationFee                304133 non-null  float64
 81  LotSizeSquareFeet             407376 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             449916 non-null  object
 84  Year                          451075 non-null  int64
 85  Month                         451075 non-null  int64
dtypes: datetime64[ns](1), float64(32), int64(6), object(47)
memory usage: 296.0+ MB

In [9]:
print("Preview of Concatenated Listing DataFrame")
display(all_listings_df.head())

print("---------/--------")
print("All columns in DataFrame\n")
print(all_listings_df.columns)
print("---------/--------")
print("Description of DataFrame\n")
print(all_listings_df.describe)

Preview of Concatenated Listing DataFrame

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month
0,90000.0,1075010398,miriamlara03@gmail.com,NaT,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61,2024,1
1,1500000.0,1074974457,janelle@judsonre.com,NaT,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN,2024,1
2,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades,2024,1
4,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024,1

---------/--------
All columns in DataFrame

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1', 'Year', 'Month'],
      dtype='object')
---------/--------
Description of DataFrame

<bound method NDFrame.describe of         OriginalListPrice  ListingKey                        ListAgentEmail  \
0                 90000.0  1075010398                miriamlara03@gmail.com
1               1500000.0  1074974457                  janelle@judsonre.com
2               1340000.0  1074973329                    haleh360@Gmail.com
3               2500000.0  1074954552  Reneechen@yourhomesoldguaranteed.com
4               3150000.0  1074936537                      anader@dppre.com
...                   ...         ...                                   ...
451070             4950.0  1149458718                                   NaN
451071             1699.0  1146439434                                   NaN
451072           350000.0  1146104836                                   NaN
451073             1325.0  1107246684                                   NaN
451074             6000.0  1063377179                                   NaN

       CloseDate  ClosePrice ListAgentFirstName ListAgentLastName   Latitude  \
0            NaT         NaN             Miriam              Lara  34.097939
1            NaT         NaN            Janelle            Judson  33.121241
2            NaT         NaN              Haleh       Dowlatshahi  34.052207
3            NaT         NaN              Renee              Chen  33.496363
4            NaT         NaN           Margaret             Nader  34.119345
...          ...         ...                ...               ...        ...
451070       NaT         NaN           Alphonso           Lascano  34.044402
451071       NaT         NaN               Gene             Smith  38.115612
451072       NaT         NaN              Jason          Lipovsky  33.139128
451073       NaT         NaN              Kathy              Lund  32.572312
451074       NaT         NaN              Jaime              Rook  33.162293

         Longitude                UnparsedAddress  ... GarageSpaces  \
0      -117.909653                1045 N Azusa 61  ...          2.0
1      -117.081614                            NaN  ...          NaN
2      -118.408445  2220 Avenue Of The Stars 2704  ...          NaN
3      -117.691677                   16 Palisades  ...          3.0
4      -118.111254              1615 Waverly Road  ...          2.0
...            ...                            ...  ...          ...
451070 -118.365074          1716 S Genesee Avenue  ...          NaN
451071 -122.267146                 124 Benson Ave  ...          1.0
451072 -117.053881         475 N Midway Drive 169  ...          0.0
451073 -117.034778              4589 Casa nova ct  ...          2.0
451074 -117.266434               4717 Majorca Way  ...          2.0

           HighSchoolDistrict  PostalCode  BuyerOfficeName.1 AssociationFee  \
0       Covina Valley Unified       91722                NaN            0.0
1                         NaN       92025                NaN            0.0
2                         NaN       90067                NaN         2105.0
3          Capistrano Unified       92677                NaN          254.0
4                         NaN       91108                NaN            NaN
...                       ...         ...                ...            ...
451070                    NaN       90019                NaN            NaN
451071                    NaN       94590                NaN            NaN
451072        Escondido Union       92027                NaN          400.0
451073                  Other       92154                NaN            0.0
451074      Oceanside Unified       92056                NaN            NaN

       LotSizeSquareFeet MiddleOrJuniorSchoolDistrict  \
0                    NaN                          NaN
1                    NaN                          NaN
2               177861.0                          NaN
3                 5300.0                          NaN
4                 9404.0                          NaN
...                  ...                          ...
451070            4886.0                          NaN
451071           15681.0                          NaN
451072          261360.0                          NaN
451073            2224.0                          NaN
451074            3519.0                          NaN

                    UnparsedAddress.1  Year Month
0                     1045 N Azusa 61  2024     1
1                                 NaN  2024     1
2       2220 Avenue Of The Stars 2704  2024     1
3                        16 Palisades  2024     1
4                   1615 Waverly Road  2024     1
...                               ...   ...   ...
451070          1716 S Genesee Avenue  2026     2
451071                 124 Benson Ave  2026     2
451072         475 N Midway Drive 169  2026     2
451073              4589 Casa nova ct  2026     2
451074               4717 Majorca Way  2026     2

[451075 rows x 86 columns]>

In [12]:
prop_type = all_listings_df['PropertyType'].unique()
print(prop_type)

['ManufacturedInPark' 'CommercialSale' 'Residential' 'ResidentialLease'
 'Land' 'ResidentialIncome' 'CommercialLease' 'BusinessOpportunity']

In [11]:
residential_listings_df=all_listings_df[all_listings_df['PropertyType']=='Residential']
residential_listings_df.info()
display(residential_listings_df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 285380 entries, 2 to 451072
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             285005 non-null  float64
 1   ListingKey                    285380 non-null  int64
 2   ListAgentEmail                264550 non-null  object
 3   CloseDate                     67392 non-null   datetime64[ns]
 4   ClosePrice                    54521 non-null   float64
 5   ListAgentFirstName            283051 non-null  object
 6   ListAgentLastName             285365 non-null  object
 7   Latitude                      207765 non-null  float64
 8   Longitude                     207765 non-null  float64
 9   UnparsedAddress               285023 non-null  object
 10  PropertyType                  285380 non-null  object
 11  LivingArea                    285092 non-null  float64
 12  ListPrice                     285380 non-null  float64
 13  DaysOnMarket                  285380 non-null  int64
 14  ListOfficeName                285380 non-null  object
 15  BuyerOfficeName               61886 non-null   object
 16  CoListOfficeName              63045 non-null   object
 17  ListAgentFullName             285360 non-null  object
 18  CoListAgentFirstName          62727 non-null   object
 19  CoListAgentLastName           62931 non-null   object
 20  BuyerAgentMlsId               63047 non-null   object
 21  BuyerAgentFirstName           62702 non-null   object
 22  BuyerAgentLastName            63076 non-null   object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       121361 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             285380 non-null  int64
 27  MLSAreaMajor                  247312 non-null  object
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                285380 non-null  object
 30  PropertyType.1                285380 non-null  object
 31  MlsStatus                     285380 non-null  object
 32  ElementarySchool              34663 non-null   object
 33  ListAgentFirstName.1          283051 non-null  object
 34  AttachedGarageYN              235765 non-null  object
 35  ParkingTotal                  285364 non-null  float64
 36  BuilderName                   13015 non-null   object
 37  PropertySubType               284750 non-null  object
 38  LotSizeAcres                  260625 non-null  float64
 39  SubdivisionName               104334 non-null  object
 40  BuyerOfficeAOR                58787 non-null   object
 41  YearBuilt                     284884 non-null  float64
 42  DaysOnMarket.1                285380 non-null  int64
 43  BuyerAgencyCompensationType   79013 non-null   object
 44  StreetNumberNumeric           284929 non-null  float64
 45  LivingArea.1                  285092 non-null  float64
 46  ListingId                     285380 non-null  object
 47  BathroomsTotalInteger         285344 non-null  float64
 48  City                          285017 non-null  object
 49  BuyerAgencyCompensation       78993 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             25315 non-null   float64
 52  BedroomsTotal                 285326 non-null  float64
 53  ContractStatusChangeDate      281824 non-null  object
 54  Longitude.1                   207765 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         5514 non-null    object
 57  PurchaseContractDate          131785 non-null  object
 58  ListingContractDate           285380 non-null  object
 59  BelowGradeFinishedArea        1425 non-null    float64
 60  BusinessType                  0 non-null       object
 61  Latitude.1                    207765 non-null  float64
 62  ListPrice.1                   285380 non-null  float64
 63  StateOrProvince               285358 non-null  object
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          34789 non-null   object
 66  FireplaceYN                   285086 non-null  object
 67  Stories                       233509 non-null  float64
 68  HighSchool                    45274 non-null   object
 69  Levels                        252648 non-null  object
 70  ListAgentLastName.1           285365 non-null  object
 71  CloseDate.1                   67392 non-null   object
 72  LotSizeDimensions             14847 non-null   object
 73  LotSizeArea                   261083 non-null  float64
 74  MainLevelBedrooms             154396 non-null  float64
 75  NewConstructionYN             266360 non-null  object
 76  GarageSpaces                  269763 non-null  float64
 77  HighSchoolDistrict            200356 non-null  object
 78  PostalCode                    285374 non-null  object
 79  BuyerOfficeName.1             61886 non-null   object
 80  AssociationFee                216072 non-null  float64
 81  LotSizeSquareFeet             260998 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             285023 non-null  object
 84  Year                          285380 non-null  int64
 85  Month                         285380 non-null  int64
dtypes: datetime64[ns](1), float64(32), int64(6), object(47)
memory usage: 189.4+ MB

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month
2,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,NaN,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,3.0,Capistrano Unified,92677,NaN,254.00,5300.0,NaN,16 Palisades,2024,1
4,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024,1
5,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,4.0,Walnut Valley Unified,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road,2024,1
6,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,2.0,Newport Mesa Unified,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront,2024,1