In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=MORTGAGE30US"

mortgage = pd.read_csv(url, parse_dates=['observation_date'])

mortgage.columns = ['date', 'rate_30yr_fixed']

In [2]:
# Making a unified listing df
listing_dfs = []

for year in [2024, 2026]:
    for month in range(1, 13):
        fname = f"CRMLSListing{year}{month:02d}.csv"
        try:
            df = pd.read_csv(fname,parse_dates=['CloseDate'])
            df['Year'] = year
            df['Month'] = month
            listing_dfs.append(df)
        except FileNotFoundError:
            # Skip months that don't exist yet
            continue

# If you want one big DataFrame:
all_listings_df = pd.concat(listing_dfs, ignore_index=True)

In [3]:
all_listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468245 entries, 0 to 468244
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             466437 non-null  float64
 1   ListingKey                    468245 non-null  int64
 2   ListAgentEmail                418402 non-null  object
 3   CloseDate                     102822 non-null  datetime64[ns]
 4   ClosePrice                    87505 non-null   float64
 5   ListAgentFirstName            465337 non-null  object
 6   ListAgentLastName             468212 non-null  object
 7   Latitude                      361619 non-null  float64
 8   Longitude                     362134 non-null  float64
 9   UnparsedAddress               466982 non-null  object
 10  PropertyType                  468245 non-null  object
 11  LivingArea                    408827 non-null  float64
 12  ListPrice                     467092 non-null  float64
 13  DaysOnMarket                  468245 non-null  int64
 14  ListOfficeName                468245 non-null  object
 15  BuyerOfficeName               96076 non-null   object
 16  CoListOfficeName              92195 non-null   object
 17  ListAgentFullName             468158 non-null  object
 18  CoListAgentFirstName          91775 non-null   object
 19  CoListAgentLastName           92043 non-null   object
 20  BuyerAgentMlsId               97103 non-null   object
 21  BuyerAgentFirstName           96815 non-null   object
 22  BuyerAgentLastName            97297 non-null   object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       134974 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             468245 non-null  int64
 27  MLSAreaMajor                  415542 non-null  object
 28  TaxAnnualAmount               3561 non-null    float64
 29  CountyOrParish                468244 non-null  object
 30  PropertyType.1                468245 non-null  object
 31  MlsStatus                     468245 non-null  object
 32  ElementarySchool              44427 non-null   object
 33  ListAgentFirstName.1          465337 non-null  object
 34  AttachedGarageYN              309269 non-null  object
 35  ParkingTotal                  438708 non-null  float64
 36  BuilderName                   15784 non-null   object
 37  PropertySubType               410153 non-null  object
 38  LotSizeAcres                  421487 non-null  float64
 39  SubdivisionName               155253 non-null  object
 40  BuyerOfficeAOR                92869 non-null   object
 41  YearBuilt                     429830 non-null  float64
 42  DaysOnMarket.1                468245 non-null  int64
 43  BuyerAgencyCompensationType   123538 non-null  object
 44  StreetNumberNumeric           466093 non-null  float64
 45  LivingArea.1                  408827 non-null  float64
 46  ListingId                     468245 non-null  object
 47  BathroomsTotalInteger         428879 non-null  float64
 48  City                          467606 non-null  object
 49  BuyerAgencyCompensation       123519 non-null  float64
 50  TaxYear                       487 non-null     float64
 51  BuildingAreaTotal             75196 non-null   float64
 52  BedroomsTotal                 410493 non-null  float64
 53  ContractStatusChangeDate      463915 non-null  object
 54  Longitude.1                   362134 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         7332 non-null    object
 57  PurchaseContractDate          177596 non-null  object
 58  ListingContractDate           468245 non-null  object
 59  BelowGradeFinishedArea        1724 non-null    float64
 60  BusinessType                  3413 non-null    object
 61  Latitude.1                    361619 non-null  float64
 62  ListPrice.1                   467092 non-null  float64
 63  StateOrProvince               468206 non-null  object
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          44555 non-null   object
 66  FireplaceYN                   399739 non-null  object
 67  Stories                       342442 non-null  float64
 68  HighSchool                    58259 non-null   object
 69  Levels                        374113 non-null  object
 70  ListAgentLastName.1           468212 non-null  object
 71  CloseDate.1                   102822 non-null  object
 72  LotSizeDimensions             26432 non-null   object
 73  LotSizeArea                   423634 non-null  float64
 74  MainLevelBedrooms             214165 non-null  float64
 75  NewConstructionYN             405304 non-null  object
 76  GarageSpaces                  379189 non-null  float64
 77  HighSchoolDistrict            282763 non-null  object
 78  PostalCode                    468110 non-null  object
 79  BuyerOfficeName.1             96076 non-null   object
 80  AssociationFee                316018 non-null  float64
 81  LotSizeSquareFeet             423017 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             466982 non-null  object
 84  Year                          468245 non-null  int64
 85  Month                         468245 non-null  int64
dtypes: datetime64[ns](1), float64(32), int64(6), object(47)
memory usage: 307.2+ MB

In [4]:
print("Preview of Concatenated Listing DataFrame")
display(all_listings_df.tail())

print("---------/--------")
print("All columns in DataFrame\n")
print(all_listings_df.columns)
print("---------/--------")
print("Description of DataFrame\n")
print(all_listings_df.describe)

Preview of Concatenated Listing DataFrame

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month
468240,6395000.0,1150511005,NaN,NaT,NaN,Arlene,Baxter,37.883215,-122.261440,2501 ROSE WALK,...,NaN,NaN,94708-1902,NaN,0.0,20000.0,NaN,2501 ROSE WALK,2026,3
468241,825000.0,1148377048,NaN,NaT,NaN,Adriana,Gliha,32.621759,-116.996024,1461 Fieldbrook Street,...,2.0,Sweetwater Union,91913,NaN,116.0,3049.2,NaN,1461 Fieldbrook Street,2026,3
468242,2849000.0,1145743715,NaN,NaT,NaN,Lori,Barnett,33.102975,-117.299101,1005 Canvasback Drive,...,3.0,Carlsbad Unified,92011,NaN,227.0,12645.0,NaN,1005 Canvasback Drive,2026,3
468243,1649000.0,1139631172,NaN,NaT,NaN,George,Wood Jr.,32.579821,-117.104163,943 Georgia Street,...,0.0,Sweetwater Union,91932,NaN,0.0,7191.0,NaN,943 Georgia Street,2026,3
468244,1649000.0,1139626731,NaN,NaT,NaN,George,Wood Jr.,32.580200,-117.116500,943 Georgia Street,...,0.0,NaN,91932,NaN,0.0,7191.0,NaN,943 Georgia Street,2026,3

---------/--------
All columns in DataFrame

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1', 'Year', 'Month'],
      dtype='object')
---------/--------
Description of DataFrame

<bound method NDFrame.describe of         OriginalListPrice  ListingKey                        ListAgentEmail  \
0                 90000.0  1075010398                miriamlara03@gmail.com
1               1500000.0  1074974457                  janelle@judsonre.com
2               1340000.0  1074973329                    haleh360@Gmail.com
3               2500000.0  1074954552  Reneechen@yourhomesoldguaranteed.com
4               3150000.0  1074936537                      anader@dppre.com
...                   ...         ...                                   ...
468240          6395000.0  1150511005                                   NaN
468241           825000.0  1148377048                                   NaN
468242          2849000.0  1145743715                                   NaN
468243          1649000.0  1139631172                                   NaN
468244          1649000.0  1139626731                                   NaN

       CloseDate  ClosePrice ListAgentFirstName ListAgentLastName   Latitude  \
0            NaT         NaN             Miriam              Lara  34.097939
1            NaT         NaN            Janelle            Judson  33.121241
2            NaT         NaN              Haleh       Dowlatshahi  34.052207
3            NaT         NaN              Renee              Chen  33.496363
4            NaT         NaN           Margaret             Nader  34.119345
...          ...         ...                ...               ...        ...
468240       NaT         NaN             Arlene            Baxter  37.883215
468241       NaT         NaN            Adriana             Gliha  32.621759
468242       NaT         NaN               Lori           Barnett  33.102975
468243       NaT         NaN             George          Wood Jr.  32.579821
468244       NaT         NaN             George          Wood Jr.  32.580200

         Longitude                UnparsedAddress  ... GarageSpaces  \
0      -117.909653                1045 N Azusa 61  ...          2.0
1      -117.081614                            NaN  ...          NaN
2      -118.408445  2220 Avenue Of The Stars 2704  ...          NaN
3      -117.691677                   16 Palisades  ...          3.0
4      -118.111254              1615 Waverly Road  ...          2.0
...            ...                            ...  ...          ...
468240 -122.261440                 2501 ROSE WALK  ...          NaN
468241 -116.996024         1461 Fieldbrook Street  ...          2.0
468242 -117.299101          1005 Canvasback Drive  ...          3.0
468243 -117.104163             943 Georgia Street  ...          0.0
468244 -117.116500             943 Georgia Street  ...          0.0

           HighSchoolDistrict  PostalCode  BuyerOfficeName.1 AssociationFee  \
0       Covina Valley Unified       91722                NaN            0.0
1                         NaN       92025                NaN            0.0
2                         NaN       90067                NaN         2105.0
3          Capistrano Unified       92677                NaN          254.0
4                         NaN       91108                NaN            NaN
...                       ...         ...                ...            ...
468240                    NaN  94708-1902                NaN            0.0
468241       Sweetwater Union       91913                NaN          116.0
468242       Carlsbad Unified       92011                NaN          227.0
468243       Sweetwater Union       91932                NaN            0.0
468244                    NaN       91932                NaN            0.0

       LotSizeSquareFeet MiddleOrJuniorSchoolDistrict  \
0                    NaN                          NaN
1                    NaN                          NaN
2               177861.0                          NaN
3                 5300.0                          NaN
4                 9404.0                          NaN
...                  ...                          ...
468240           20000.0                          NaN
468241            3049.2                          NaN
468242           12645.0                          NaN
468243            7191.0                          NaN
468244            7191.0                          NaN

                    UnparsedAddress.1  Year Month
0                     1045 N Azusa 61  2024     1
1                                 NaN  2024     1
2       2220 Avenue Of The Stars 2704  2024     1
3                        16 Palisades  2024     1
4                   1615 Waverly Road  2024     1
...                               ...   ...   ...
468240                 2501 ROSE WALK  2026     3
468241         1461 Fieldbrook Street  2026     3
468242          1005 Canvasback Drive  2026     3
468243             943 Georgia Street  2026     3
468244             943 Georgia Street  2026     3

[468245 rows x 86 columns]>

In [5]:
cleaned_listings=all_listings_df[all_listings_df['PropertyType']=='Residential']
cleaned_listings.info()
display(cleaned_listings.head())

<class 'pandas.core.frame.DataFrame'>
Index: 297358 entries, 2 to 468243
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             296964 non-null  float64
 1   ListingKey                    297358 non-null  int64
 2   ListAgentEmail                264550 non-null  object
 3   CloseDate                     64676 non-null   datetime64[ns]
 4   ClosePrice                    50961 non-null   float64
 5   ListAgentFirstName            294916 non-null  object
 6   ListAgentLastName             297343 non-null  object
 7   Latitude                      219599 non-null  float64
 8   Longitude                     219599 non-null  float64
 9   UnparsedAddress               296947 non-null  object
 10  PropertyType                  297358 non-null  object
 11  LivingArea                    297051 non-null  float64
 12  ListPrice                     297358 non-null  float64
 13  DaysOnMarket                  297358 non-null  int64
 14  ListOfficeName                297358 non-null  object
 15  BuyerOfficeName               58939 non-null   object
 16  CoListOfficeName              65627 non-null   object
 17  ListAgentFullName             297333 non-null  object
 18  CoListAgentFirstName          65302 non-null   object
 19  CoListAgentLastName           65521 non-null   object
 20  BuyerAgentMlsId               60061 non-null   object
 21  BuyerAgentFirstName           59720 non-null   object
 22  BuyerAgentLastName            60088 non-null   object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       126610 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             297358 non-null  int64
 27  MLSAreaMajor                  257668 non-null  object
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                297358 non-null  object
 30  PropertyType.1                297358 non-null  object
 31  MlsStatus                     297358 non-null  object
 32  ElementarySchool              36189 non-null   object
 33  ListAgentFirstName.1          294916 non-null  object
 34  AttachedGarageYN              245763 non-null  object
 35  ParkingTotal                  297342 non-null  float64
 36  BuilderName                   13559 non-null   object
 37  PropertySubType               296716 non-null  object
 38  LotSizeAcres                  271674 non-null  float64
 39  SubdivisionName               108456 non-null  object
 40  BuyerOfficeAOR                56155 non-null   object
 41  YearBuilt                     296824 non-null  float64
 42  DaysOnMarket.1                297358 non-null  int64
 43  BuyerAgencyCompensationType   79013 non-null   object
 44  StreetNumberNumeric           296850 non-null  float64
 45  LivingArea.1                  297051 non-null  float64
 46  ListingId                     297358 non-null  object
 47  BathroomsTotalInteger         297322 non-null  float64
 48  City                          296984 non-null  object
 49  BuyerAgencyCompensation       78993 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             26314 non-null   float64
 52  BedroomsTotal                 297298 non-null  float64
 53  ContractStatusChangeDate      293533 non-null  object
 54  Longitude.1                   219599 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         5187 non-null    object
 57  PurchaseContractDate          131501 non-null  object
 58  ListingContractDate           297358 non-null  object
 59  BelowGradeFinishedArea        1513 non-null    float64
 60  BusinessType                  0 non-null       object
 61  Latitude.1                    219599 non-null  float64
 62  ListPrice.1                   297358 non-null  float64
 63  StateOrProvince               297325 non-null  object
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          36302 non-null   object
 66  FireplaceYN                   297062 non-null  object
 67  Stories                       242783 non-null  float64
 68  HighSchool                    47292 non-null   object
 69  Levels                        262778 non-null  object
 70  ListAgentLastName.1           297343 non-null  object
 71  CloseDate.1                   64676 non-null   object
 72  LotSizeDimensions             15388 non-null   object
 73  LotSizeArea                   272142 non-null  float64
 74  MainLevelBedrooms             160730 non-null  float64
 75  NewConstructionYN             277597 non-null  object
 76  GarageSpaces                  281157 non-null  float64
 77  HighSchoolDistrict            209115 non-null  object
 78  PostalCode                    297352 non-null  object
 79  BuyerOfficeName.1             58939 non-null   object
 80  AssociationFee                225043 non-null  float64
 81  LotSizeSquareFeet             272058 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             296947 non-null  object
 84  Year                          297358 non-null  int64
 85  Month                         297358 non-null  int64
dtypes: datetime64[ns](1), float64(32), int64(6), object(47)
memory usage: 197.4+ MB

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month
2,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,NaN,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,3.0,Capistrano Unified,92677,NaN,254.00,5300.0,NaN,16 Palisades,2024,1
4,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024,1
5,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,4.0,Walnut Valley Unified,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road,2024,1
6,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,2.0,Newport Mesa Unified,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront,2024,1

In [6]:
before_r_list = all_listings_df.shape[0]
after_r_list = cleaned_listings.shape[0]

print(f"Row count before Residential filter: {before_r_list} rows")
print(f"Row count after Residential filter: {after_r_list} rows")
row_change = before_r_list - after_r_list
print(f"{row_change} rows were dropped after filtering for 'Residential' property only.")

Row count before Residential filter: 468245 rows
Row count after Residential filter: 297358 rows
170887 rows were dropped after filtering for 'Residential' property only.

In [7]:
cleaned_listings.to_csv("cleaned_listings.csv",index=True,encoding="utf-8-sig")

In [8]:
sold_dfs = []

for year in [2024, 2026]:
    for month in range(1, 13):
        fname = f"CRMLSSold{year}{month:02d}.csv"
        try:
            df = pd.read_csv(fname)
            df['Year'] = year
            df['Month'] = month
            sold_dfs.append(df)
        except FileNotFoundError:
            # Skip months that don't exist yet
            continue

# If you want one big DataFrame:
all_sold_df = pd.concat(sold_dfs, ignore_index=True)

/var/folders/b9/2nft45yn149gpklybfl7lll40000gp/T/ipykernel_53510/825790866.py:7: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fname)
/var/folders/b9/2nft45yn149gpklybfl7lll40000gp/T/ipykernel_53510/825790866.py:7: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fname)

In [9]:
all_sold_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331597 entries, 0 to 331596
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 260150 non-null  object
 1   ListAgentAOR                  263656 non-null  object
 2   Flooring                      194804 non-null  object
 3   ViewYN                        298525 non-null  object
 4   WaterfrontYN                  177 non-null     object
 5   BasementYN                    5444 non-null    object
 6   PoolPrivateYN                 286399 non-null  object
 7   OriginalListPrice             330665 non-null  float64
 8   ListingKey                    331597 non-null  int64
 9   ListAgentEmail                288535 non-null  object
 10  CloseDate                     331597 non-null  object
 11  ClosePrice                    331593 non-null  float64
 12  ListAgentFirstName            329464 non-null  object
 13  ListAgentLastName             331567 non-null  object
 14  Latitude                      312619 non-null  float64
 15  Longitude                     312784 non-null  float64
 16  UnparsedAddress               331078 non-null  object
 17  PropertyType                  331597 non-null  object
 18  LivingArea                    308113 non-null  float64
 19  ListPrice                     331118 non-null  float64
 20  DaysOnMarket                  331597 non-null  int64
 21  ListOfficeName                331597 non-null  object
 22  BuyerOfficeName               326773 non-null  object
 23  CoListOfficeName              67706 non-null   object
 24  ListAgentFullName             331516 non-null  object
 25  CoListAgentFirstName          67391 non-null   object
 26  CoListAgentLastName           67538 non-null   object
 27  BuyerAgentMlsId               330728 non-null  object
 28  BuyerAgentFirstName           329962 non-null  object
 29  BuyerAgentLastName            331421 non-null  object
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       98719 non-null   object
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             331597 non-null  int64
 34  MLSAreaMajor                  295297 non-null  object
 35  TaxAnnualAmount               1591 non-null    float64
 36  CountyOrParish                331597 non-null  object
 37  MlsStatus                     331597 non-null  object
 38  ElementarySchool              37965 non-null   object
 39  AttachedGarageYN              241246 non-null  object
 40  ParkingTotal                  320614 non-null  float64
 41  BuilderName                   12710 non-null   object
 42  PropertySubType               305551 non-null  object
 43  LotSizeAcres                  298056 non-null  float64
 44  SubdivisionName               116232 non-null  object
 45  BuyerOfficeAOR                317646 non-null  object
 46  YearBuilt                     317570 non-null  float64
 47  StreetNumberNumeric           330727 non-null  float64
 48  ListingId                     331597 non-null  object
 49  BathroomsTotalInteger         316034 non-null  float64
 50  City                          331288 non-null  object
 51  TaxYear                       206 non-null     float64
 52  BuildingAreaTotal             41883 non-null   float64
 53  BedroomsTotal                 309301 non-null  float64
 54  ContractStatusChangeDate      330885 non-null  object
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         26690 non-null   object
 57  PurchaseContractDate          324927 non-null  object
 58  ListingContractDate           331548 non-null  object
 59  BelowGradeFinishedArea        1340 non-null    float64
 60  BusinessType                  973 non-null     object
 61  StateOrProvince               331597 non-null  object
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          38209 non-null   object
 64  FireplaceYN                   302076 non-null  object
 65  Stories                       260814 non-null  float64
 66  HighSchool                    49587 non-null   object
 67  Levels                        281283 non-null  object
 68  LotSizeDimensions             16910 non-null   object
 69  LotSizeArea                   299160 non-null  float64
 70  MainLevelBedrooms             173400 non-null  float64
 71  NewConstructionYN             292337 non-null  object
 72  GarageSpaces                  289834 non-null  float64
 73  HighSchoolDistrict            222718 non-null  object
 74  PostalCode                    331493 non-null  object
 75  AssociationFee                228160 non-null  float64
 76  LotSizeSquareFeet             298897 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         60595 non-null   object
 79  OriginatingSystemSubName      60595 non-null   object
 80  Year                          331597 non-null  int64
 81  Month                         331597 non-null  int64
 82  BuyerAgencyCompensationType   67747 non-null   object
 83  BuyerAgencyCompensation       67780 non-null   float64
 84  latfilled                     77055 non-null   object
 85  lonfilled                     77055 non-null   object
dtypes: float64(28), int64(5), object(53)
memory usage: 217.6+ MB

In [10]:
print("Preview of Concatenated Sold DataFrame")
display(all_sold_df.head())

print("---------/--------")
print("All columns in DataFrame\n")
print(all_sold_df.columns)
print("---------/--------")
print("Description of DataFrame\n")
print(all_sold_df.describe)

before_shape = all_sold_df.shape

Preview of Concatenated Sold DataFrame

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,NaN,NaN,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,52320.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,217364.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,217800.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,108883.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN

---------/--------
All columns in DataFrame

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName', 'Year', 'Month',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='object')
---------/--------
Description of DataFrame

<bound method NDFrame.describe of                    BuyerAgentAOR              ListAgentAOR          Flooring  \
0                    Mlslistings               Mlslistings  Carpet,Tile,Wood
1                     HighDesert                HighDesert               NaN
2                   OrangeCounty              OrangeCounty               NaN
3                  InlandValleys             InlandValleys               NaN
4       SouthwestRiversideCounty  SouthwestRiversideCounty               NaN
...                          ...                       ...               ...
331592                    Laguna                    Laguna               NaN
331593               Mlslistings               Mlslistings               NaN
331594                  SanDiego                  SanDiego               NaN
331595          TheInlandGateway          TheInlandGateway               NaN
331596                   Newport                   Newport               NaN

       ViewYN WaterfrontYN BasementYN PoolPrivateYN  OriginalListPrice  \
0        True          NaN        NaN         False           499000.0
1         NaN          NaN        NaN           NaN                0.0
2        True          NaN        NaN           NaN            75000.0
3        True          NaN        NaN           NaN           199000.0
4        True          NaN        NaN           NaN            19500.0
...       ...          ...        ...           ...                ...
331592   True          NaN        NaN         False             5500.0
331593  False          NaN        NaN           NaN           800000.0
331594   True          NaN        NaN         False             2950.0
331595   True          NaN        NaN           NaN           100000.0
331596   True          NaN        NaN         False          7500000.0

        ListingKey              ListAgentEmail  ... LotSizeSquareFeet  \
0        551985747       jwachter@cbnorcal.com  ...               NaN
1        535486633  eabrown@lee-associates.com  ...           52320.0
2        529986282             Joe@9WINWIN.com  ...          217364.0
3        529618166    carolthefinder@yahoo.com  ...          217800.0
4        522614340      jtavisola@tavisola.com  ...          108883.0
...            ...                         ...  ...               ...
331592  1000650939                         NaN  ...            2614.0
331593   446945221                         NaN  ...           79279.0
331594   446940200                         NaN  ...               NaN
331595   446010441                         NaN  ...          108900.0
331596   425834366                         NaN  ...         1742835.6

        MiddleOrJuniorSchoolDistrict OriginatingSystemName  \
0                                NaN                 CRMLS
1                                NaN                 CRMLS
2                                NaN                 CRMLS
3                                NaN                 CRMLS
4                                NaN                 CRMLS
...                              ...                   ...
331592                           NaN                 CRMLS
331593                           NaN                 CRMLS
331594                           NaN                 CRMLS
331595                           NaN                 CRMLS
331596                           NaN                 CRMLS

       OriginatingSystemSubName  Year  Month BuyerAgencyCompensationType  \
0                    CRMLS_MLSL  2024      1                         NaN
1                     CRMLS_CRM  2024      1                         NaN
2                     CRMLS_CRM  2024      1                         NaN
3                     CRMLS_CRM  2024      1                         NaN
4                     CRMLS_CRM  2024      1                         NaN
...                         ...   ...    ...                         ...
331592                CRMLS_CRM  2026      3                         NaN
331593               CRMLS_MLSL  2026      3                         NaN
331594               CRMLS_SAND  2026      3                         NaN
331595                CRMLS_CRM  2026      3                         NaN
331596                CRMLS_CRM  2026      3                         NaN

       BuyerAgencyCompensation  latfilled  lonfilled
0                          NaN        NaN        NaN
1                          NaN        NaN        NaN
2                          NaN        NaN        NaN
3                          NaN        NaN        NaN
4                          NaN        NaN        NaN
...                        ...        ...        ...
331592                     NaN        NaN        NaN
331593                     NaN        NaN        NaN
331594                     NaN        NaN        NaN
331595                     NaN        NaN        NaN
331596                     NaN        NaN        NaN

[331597 rows x 86 columns]>

In [11]:
prop_type = all_sold_df['PropertyType'].unique()
print(f"Unique Property Types: {prop_type}")

Unique Property Types: ['Residential' 'CommercialLease' 'Land' 'ResidentialLease'
 'ManufacturedInPark' 'ResidentialIncome' 'CommercialSale'
 'BusinessOpportunity']

In [12]:
residential_sold_df=all_sold_df[all_sold_df['PropertyType']=='Residential']
residential_sold_df.info()
display(residential_sold_df.tail())

after_shape = residential_sold_df.shape

<class 'pandas.core.frame.DataFrame'>
Index: 224372 entries, 0 to 331596
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 175304 non-null  object
 1   ListAgentAOR                  178208 non-null  object
 2   Flooring                      143728 non-null  object
 3   ViewYN                        205546 non-null  object
 4   WaterfrontYN                  135 non-null     object
 5   BasementYN                    4347 non-null    object
 6   PoolPrivateYN                 202219 non-null  object
 7   OriginalListPrice             223973 non-null  float64
 8   ListingKey                    224372 non-null  int64
 9   ListAgentEmail                196025 non-null  object
 10  CloseDate                     224372 non-null  object
 11  ClosePrice                    224370 non-null  float64
 12  ListAgentFirstName            222516 non-null  object
 13  ListAgentLastName             224355 non-null  object
 14  Latitude                      208567 non-null  float64
 15  Longitude                     208567 non-null  float64
 16  UnparsedAddress               224167 non-null  object
 17  PropertyType                  224372 non-null  object
 18  LivingArea                    224246 non-null  float64
 19  ListPrice                     224372 non-null  float64
 20  DaysOnMarket                  224372 non-null  int64
 21  ListOfficeName                224372 non-null  object
 22  BuyerOfficeName               220033 non-null  object
 23  CoListOfficeName              50743 non-null   object
 24  ListAgentFullName             224330 non-null  object
 25  CoListAgentFirstName          50485 non-null   object
 26  CoListAgentLastName           50623 non-null   object
 27  BuyerAgentMlsId               224107 non-null  object
 28  BuyerAgentFirstName           223145 non-null  object
 29  BuyerAgentLastName            224277 non-null  object
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       93575 non-null   object
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             224372 non-null  int64
 34  MLSAreaMajor                  194870 non-null  object
 35  TaxAnnualAmount               0 non-null       float64
 36  CountyOrParish                224372 non-null  object
 37  MlsStatus                     224372 non-null  object
 38  ElementarySchool              30714 non-null   object
 39  AttachedGarageYN              190878 non-null  object
 40  ParkingTotal                  223947 non-null  float64
 41  BuilderName                   10984 non-null   object
 42  PropertySubType               223962 non-null  object
 43  LotSizeAcres                  205343 non-null  float64
 44  SubdivisionName               82397 non-null   object
 45  BuyerOfficeAOR                212505 non-null  object
 46  YearBuilt                     224175 non-null  float64
 47  StreetNumberNumeric           224125 non-null  float64
 48  ListingId                     224372 non-null  object
 49  BathroomsTotalInteger         224329 non-null  float64
 50  City                          224148 non-null  object
 51  TaxYear                       0 non-null       float64
 52  BuildingAreaTotal             15169 non-null   float64
 53  BedroomsTotal                 224364 non-null  float64
 54  ContractStatusChangeDate      223783 non-null  object
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         20136 non-null   object
 57  PurchaseContractDate          224191 non-null  object
 58  ListingContractDate           224371 non-null  object
 59  BelowGradeFinishedArea        1165 non-null    float64
 60  BusinessType                  0 non-null       object
 61  StateOrProvince               224372 non-null  object
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          30909 non-null   object
 64  FireplaceYN                   224207 non-null  object
 65  Stories                       186263 non-null  float64
 66  HighSchool                    39944 non-null   object
 67  Levels                        199040 non-null  object
 68  LotSizeDimensions             10610 non-null   object
 69  LotSizeArea                   205636 non-null  float64
 70  MainLevelBedrooms             128253 non-null  float64
 71  NewConstructionYN             208227 non-null  object
 72  GarageSpaces                  215154 non-null  float64
 73  HighSchoolDistrict            164190 non-null  object
 74  PostalCode                    224372 non-null  object
 75  AssociationFee                171974 non-null  float64
 76  LotSizeSquareFeet             205576 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         39240 non-null   object
 79  OriginatingSystemSubName      39240 non-null   object
 80  Year                          224372 non-null  int64
 81  Month                         224372 non-null  int64
 82  BuyerAgencyCompensationType   46136 non-null   object
 83  BuyerAgencyCompensation       46125 non-null   float64
 84  latfilled                     52908 non-null   object
 85  lonfilled                     52908 non-null   object
dtypes: float64(28), int64(5), object(53)
memory usage: 148.9+ MB

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
331571,InlandValleys,InlandValleys,"Carpet,Stone,Tile",True,NaN,True,False,34000000.0,1048452308,NaN,...,1229263.2,NaN,CRMLS,CRMLS_CRM,2026,3,NaN,NaN,NaN,NaN
331578,HighDesert,HighDesert,NaN,True,NaN,NaN,False,470000.0,1045564874,NaN,...,56628.0,NaN,CRMLS,CRMLS_CRM,2026,3,NaN,NaN,NaN,NaN
331581,Mrmls,TheInlandGateway,"Carpet,Vinyl",True,NaN,NaN,False,375000.0,1037668743,NaN,...,16988.0,NaN,CRMLS,CRMLS_CRM,2026,3,NaN,NaN,NaN,NaN
331582,CaliforniaDesert,CaliforniaDesert,"Stone,Wood",True,NaN,NaN,False,525000.0,1037643293,NaN,...,7200.0,NaN,CRMLS,CRMLS_CDAR,2026,3,NaN,NaN,NaN,NaN
331596,Newport,Newport,NaN,True,NaN,NaN,False,7500000.0,425834366,NaN,...,1742835.6,NaN,CRMLS,CRMLS_CRM,2026,3,NaN,NaN,NaN,NaN

In [13]:
# Change in rows
print(f"Row count before Residential filter: {before_shape[0]} rows")
print(f"Row count after Residential filter: {after_shape[0]} rows")
row_change = before_shape[0] - after_shape[0]
print(f"{row_change} rows were dropped after filtering for 'Residential' property only.")

Row count before Residential filter: 331597 rows
Row count after Residential filter: 224372 rows
107225 rows were dropped after filtering for 'Residential' property only.

In [14]:
completedness_count = pd.DataFrame(
    residential_sold_df.isnull().sum()
).reset_index()
completedness_count.columns = ["Column Name", "count"]
completedness_count = completedness_count.sort_values(by='count',ascending=False)

display(completedness_count)

completedness_pct = pd.DataFrame(residential_sold_df.isnull().mean()).reset_index()
completedness_pct.columns = ["Column Name","pct"]

                 Column Name   count
32    AboveGradeFinishedArea  224372
35           TaxAnnualAmount  224372
30           FireplacesTotal  224372
51                   TaxYear  224372
55  ElementarySchoolDistrict  224372
..                       ...     ...
81                     Month       0
33         ListingKeyNumeric       0
36            CountyOrParish       0
48                 ListingId       0
17              PropertyType       0

[86 rows x 2 columns]

In [15]:
flagged_columns = completedness_pct[completedness_pct['pct']>=0.9].sort_values(by='pct',ascending=False).reset_index(drop=True)
display(flagged_columns)

lst_flagged = flagged_columns["Column Name"].to_list()
print(lst_flagged)

                     Column Name       pct
0                FireplacesTotal  1.000000
1         AboveGradeFinishedArea  1.000000
2                TaxAnnualAmount  1.000000
3                        TaxYear  1.000000
4       ElementarySchoolDistrict  1.000000
5                   BusinessType  1.000000
6                  CoveredSpaces  1.000000
7   MiddleOrJuniorSchoolDistrict  1.000000
8                   WaterfrontYN  0.999398
9         BelowGradeFinishedArea  0.994808
10                    BasementYN  0.980626
11             LotSizeDimensions  0.952712
12                   BuilderName  0.951046
13             BuildingAreaTotal  0.932394
14         CoBuyerAgentFirstName  0.910256

['FireplacesTotal', 'AboveGradeFinishedArea', 'TaxAnnualAmount', 'TaxYear', 'ElementarySchoolDistrict', 'BusinessType', 'CoveredSpaces', 'MiddleOrJuniorSchoolDistrict', 'WaterfrontYN', 'BelowGradeFinishedArea', 'BasementYN', 'LotSizeDimensions', 'BuilderName', 'BuildingAreaTotal', 'CoBuyerAgentFirstName']

In [16]:
cleaned_sold = all_sold_df.drop(columns=lst_flagged)

print(f"Number of Columns before filtering out flagged columns: {len(all_sold_df.columns.to_list())} columns.")
print(f"Number of Columns after filtering out flagged columns: {len(cleaned_sold.columns.to_list())} columns.")
print(f"{len(lst_flagged)} columns are removed due to high percentage of missing values.")

Number of Columns before filtering out flagged columns: 86 columns.
Number of Columns after filtering out flagged columns: 71 columns.
15 columns are removed due to high percentage of missing values.

In [17]:
#Summary table for ClosePrice, LivingArea, and DaysOnMarket
cols = ["ClosePrice","LivingArea","DaysOnMarket"]

summary = cleaned_sold[cols].agg([
    "min","max","mean","median",
    lambda x: x.quantile(0.25),
    lambda x: x.quantile(0.75),
    lambda x: x.quantile(0.90),
    lambda x: x.quantile(0.95)
])

summary.index = ["min", "max", "mean", "median", "p25", "p75", "p90", "p95"]

display(summary.T)

,min,max,mean,median,p25,p75,p90,p95
ClosePrice,0.0,760000000.0,854025.690884,632500.0,74100.0,1077500.0,1795000.0,2500000.0
LivingArea,0.0,909090909.0,4756.411821,1577.0,1185.0,2144.0,2909.0,3513.0
DaysOnMarket,-84.0,12430.0,41.604686,20.0,8.0,51.0,100.0,143.0

In [18]:
cleaned_sold.to_csv("cleaned_sold.csv",index=True,encoding="utf-8-sig")

In [19]:
# Combining FRED data
mortgage

#Resample

mortgage['year_month'] = mortgage['date'].dt.to_period('M')

monthly_mortgage = mortgage.groupby('year_month')["rate_30yr_fixed"].mean().reset_index()

display(monthly_mortgage)

    year_month  rate_30yr_fixed
0      1971-04         7.310000
1      1971-05         7.425000
2      1971-06         7.530000
3      1971-07         7.604000
4      1971-08         7.697500
..         ...              ...
656    2025-12         6.190000
657    2026-01         6.102500
658    2026-02         6.047500
659    2026-03         6.177500
660    2026-04         6.376667

[661 rows x 2 columns]

In [20]:
#Re-format date columns for Sold and Listing DFs

cleaned_sold["year_month"] = pd.to_datetime(cleaned_sold["CloseDate"]).dt.to_period("M")

cleaned_listings['year_month'] = pd.to_datetime(cleaned_listings['ListingContractDate']).dt.to_period('M')

/var/folders/b9/2nft45yn149gpklybfl7lll40000gp/T/ipykernel_53510/3417382810.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_listings['year_month'] = pd.to_datetime(cleaned_listings['ListingContractDate']).dt.to_period('M')

In [39]:
sold_w_rates = cleaned_sold.merge(monthly_mortgage,on="year_month",how="left").reset_index(drop=True)

listing_w_rates = cleaned_listings.merge(monthly_mortgage,on="year_month",how="left").reset_index(drop=True)

display(sold_w_rates.head())
display(listing_w_rates.head())

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
1,HighDesert,HighDesert,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,2024-01-24,950.0,...,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
2,OrangeCounty,OrangeCounty,NaN,True,NaN,75000.0,529986282,Joe@9WINWIN.com,2024-01-16,45000.0,...,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
3,InlandValleys,InlandValleys,NaN,True,NaN,199000.0,529618166,carolthefinder@yahoo.com,2024-01-08,141500.0,...,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,19500.0,522614340,jtavisola@tavisola.com,2024-01-17,15000.0,...,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN,2024-01,6.6425

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month,year_month,rate_30yr_fixed
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1,2024-01,6.6425
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,92677,NaN,254.00,5300.0,NaN,16 Palisades,2024,1,2024-01,6.6425
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024,1,2024-01,6.6425
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road,2024,1,2024-01,6.6425
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront,2024,1,2024-01,6.6425

In [40]:
print(sold_w_rates['rate_30yr_fixed'].isnull().sum())
print(listing_w_rates['rate_30yr_fixed'].isnull().sum())

display(sold_w_rates[['CloseDate','year_month','ClosePrice','rate_30yr_fixed']].head())

0
0

    CloseDate year_month  ClosePrice  rate_30yr_fixed
0  2024-01-26    2024-01    240000.0           6.6425
1  2024-01-24    2024-01       950.0           6.6425
2  2024-01-16    2024-01     45000.0           6.6425
3  2024-01-08    2024-01    141500.0           6.6425
4  2024-01-17    2024-01     15000.0           6.6425

In [41]:
# Convert file to CSV format
sold_w_rates.to_csv('enriched_sold.csv',index=True,encoding='utf-8-sig')
listing_w_rates.to_csv('enriched_listing.csv',index=True,encoding='utf-8-sig')

In [55]:
# Re-read 'enriched_sold.csv' with correct date format
enriched_sold = pd.read_csv('enriched_sold.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])
enriched_sold.info()

/var/folders/b9/2nft45yn149gpklybfl7lll40000gp/T/ipykernel_53510/1178815760.py:2: DtypeWarning: Columns (1,2,8,64,65,68,70,71) have mixed types. Specify dtype option on import or set low_memory=False.
  enriched_sold = pd.read_csv('enriched_sold.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])

<class 'pandas.core.frame.DataFrame'>
Index: 331597 entries, 0 to 331596
Data columns (total 73 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   BuyerAgentAOR                260150 non-null  object
 1   ListAgentAOR                 263656 non-null  object
 2   Flooring                     194804 non-null  object
 3   ViewYN                       298525 non-null  object
 4   PoolPrivateYN                286399 non-null  object
 5   OriginalListPrice            330665 non-null  float64
 6   ListingKey                   331597 non-null  int64
 7   ListAgentEmail               288535 non-null  object
 8   CloseDate                    331597 non-null  datetime64[ns]
 9   ClosePrice                   331593 non-null  float64
 10  ListAgentFirstName           329464 non-null  object
 11  ListAgentLastName            331567 non-null  object
 12  Latitude                     312619 non-null  float64
 13  Longitude                    312784 non-null  float64
 14  UnparsedAddress              331078 non-null  object
 15  PropertyType                 331597 non-null  object
 16  LivingArea                   308113 non-null  float64
 17  ListPrice                    331118 non-null  float64
 18  DaysOnMarket                 331597 non-null  int64
 19  ListOfficeName               331597 non-null  object
 20  BuyerOfficeName              326773 non-null  object
 21  CoListOfficeName             67706 non-null   object
 22  ListAgentFullName            331516 non-null  object
 23  CoListAgentFirstName         67391 non-null   object
 24  CoListAgentLastName          67538 non-null   object
 25  BuyerAgentMlsId              330728 non-null  object
 26  BuyerAgentFirstName          329962 non-null  object
 27  BuyerAgentLastName           331421 non-null  object
 28  AssociationFeeFrequency      98719 non-null   object
 29  ListingKeyNumeric            331597 non-null  int64
 30  MLSAreaMajor                 295297 non-null  object
 31  CountyOrParish               331597 non-null  object
 32  MlsStatus                    331597 non-null  object
 33  ElementarySchool             37965 non-null   object
 34  AttachedGarageYN             241246 non-null  object
 35  ParkingTotal                 320614 non-null  float64
 36  PropertySubType              305551 non-null  object
 37  LotSizeAcres                 298056 non-null  float64
 38  SubdivisionName              116232 non-null  object
 39  BuyerOfficeAOR               317646 non-null  object
 40  YearBuilt                    317570 non-null  float64
 41  StreetNumberNumeric          330727 non-null  float64
 42  ListingId                    331597 non-null  object
 43  BathroomsTotalInteger        316034 non-null  float64
 44  City                         331288 non-null  object
 45  BedroomsTotal                309301 non-null  float64
 46  ContractStatusChangeDate     330885 non-null  datetime64[ns]
 47  PurchaseContractDate         324927 non-null  datetime64[ns]
 48  ListingContractDate          331548 non-null  datetime64[ns]
 49  StateOrProvince              331597 non-null  object
 50  MiddleOrJuniorSchool         38209 non-null   object
 51  FireplaceYN                  302076 non-null  object
 52  Stories                      260814 non-null  float64
 53  HighSchool                   49587 non-null   object
 54  Levels                       281283 non-null  object
 55  LotSizeArea                  299160 non-null  float64
 56  MainLevelBedrooms            173400 non-null  float64
 57  NewConstructionYN            292337 non-null  object
 58  GarageSpaces                 289834 non-null  float64
 59  HighSchoolDistrict           222718 non-null  object
 60  PostalCode                   331493 non-null  object
 61  AssociationFee               228160 non-null  float64
 62  LotSizeSquareFeet            298897 non-null  float64
 63  OriginatingSystemName        60595 non-null   object
 64  OriginatingSystemSubName     60595 non-null   object
 65  Year                         331597 non-null  int64
 66  Month                        331597 non-null  int64
 67  BuyerAgencyCompensationType  67747 non-null   object
 68  BuyerAgencyCompensation      67780 non-null   float64
 69  latfilled                    77055 non-null   object
 70  lonfilled                    77055 non-null   object
 71  year_month                   331597 non-null  object
 72  rate_30yr_fixed              331597 non-null  float64
dtypes: datetime64[ns](4), float64(20), int64(5), object(44)
memory usage: 187.2+ MB

In [53]:
# Re-read 'enriched_listings.csv' with correct date format
enriched_listing = pd.read_csv('enriched_listing.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])
enriched_listing.info()

/var/folders/b9/2nft45yn149gpklybfl7lll40000gp/T/ipykernel_53510/2771643693.py:2: DtypeWarning: Columns (3,44) have mixed types. Specify dtype option on import or set low_memory=False.
  enriched_listing = pd.read_csv('enriched_listing.csv',index_col=0,parse_dates=['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate'])

<class 'pandas.core.frame.DataFrame'>
Index: 297358 entries, 0 to 297357
Data columns (total 88 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             296964 non-null  float64
 1   ListingKey                    297358 non-null  int64
 2   ListAgentEmail                264550 non-null  object
 3   CloseDate                     64676 non-null   datetime64[ns]
 4   ClosePrice                    50961 non-null   float64
 5   ListAgentFirstName            294916 non-null  object
 6   ListAgentLastName             297343 non-null  object
 7   Latitude                      219599 non-null  float64
 8   Longitude                     219599 non-null  float64
 9   UnparsedAddress               296947 non-null  object
 10  PropertyType                  297358 non-null  object
 11  LivingArea                    297051 non-null  float64
 12  ListPrice                     297358 non-null  float64
 13  DaysOnMarket                  297358 non-null  int64
 14  ListOfficeName                297358 non-null  object
 15  BuyerOfficeName               58939 non-null   object
 16  CoListOfficeName              65627 non-null   object
 17  ListAgentFullName             297333 non-null  object
 18  CoListAgentFirstName          65302 non-null   object
 19  CoListAgentLastName           65521 non-null   object
 20  BuyerAgentMlsId               60061 non-null   object
 21  BuyerAgentFirstName           59720 non-null   object
 22  BuyerAgentLastName            60088 non-null   object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       126610 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             297358 non-null  int64
 27  MLSAreaMajor                  257668 non-null  object
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                297358 non-null  object
 30  PropertyType.1                297358 non-null  object
 31  MlsStatus                     297358 non-null  object
 32  ElementarySchool              36189 non-null   object
 33  ListAgentFirstName.1          294916 non-null  object
 34  AttachedGarageYN              245763 non-null  object
 35  ParkingTotal                  297342 non-null  float64
 36  BuilderName                   13559 non-null   object
 37  PropertySubType               296716 non-null  object
 38  LotSizeAcres                  271674 non-null  float64
 39  SubdivisionName               108456 non-null  object
 40  BuyerOfficeAOR                56155 non-null   object
 41  YearBuilt                     296824 non-null  float64
 42  DaysOnMarket.1                297358 non-null  int64
 43  BuyerAgencyCompensationType   79013 non-null   object
 44  StreetNumberNumeric           296850 non-null  float64
 45  LivingArea.1                  297051 non-null  float64
 46  ListingId                     297358 non-null  object
 47  BathroomsTotalInteger         297322 non-null  float64
 48  City                          296984 non-null  object
 49  BuyerAgencyCompensation       78993 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             26314 non-null   float64
 52  BedroomsTotal                 297298 non-null  float64
 53  ContractStatusChangeDate      293533 non-null  datetime64[ns]
 54  Longitude.1                   219599 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         5187 non-null    object
 57  PurchaseContractDate          131501 non-null  datetime64[ns]
 58  ListingContractDate           297358 non-null  datetime64[ns]
 59  BelowGradeFinishedArea        1513 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    219599 non-null  float64
 62  ListPrice.1                   297358 non-null  float64
 63  StateOrProvince               297325 non-null  object
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          36302 non-null   object
 66  FireplaceYN                   297062 non-null  object
 67  Stories                       242783 non-null  float64
 68  HighSchool                    47292 non-null   object
 69  Levels                        262778 non-null  object
 70  ListAgentLastName.1           297343 non-null  object
 71  CloseDate.1                   64676 non-null   object
 72  LotSizeDimensions             15388 non-null   object
 73  LotSizeArea                   272142 non-null  float64
 74  MainLevelBedrooms             160730 non-null  float64
 75  NewConstructionYN             277597 non-null  object
 76  GarageSpaces                  281157 non-null  float64
 77  HighSchoolDistrict            209115 non-null  object
 78  PostalCode                    297352 non-null  object
 79  BuyerOfficeName.1             58939 non-null   object
 80  AssociationFee                225043 non-null  float64
 81  LotSizeSquareFeet             272058 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             296947 non-null  object
 84  Year                          297358 non-null  int64
 85  Month                         297358 non-null  int64
 86  year_month                    297358 non-null  object
 87  rate_30yr_fixed               297358 non-null  float64
dtypes: datetime64[ns](4), float64(34), int64(6), object(44)
memory usage: 201.9+ MB

In [66]:
# Checking if date follows the correct order

# Check if listing is after close

def list_after_close(listing_date,close_date):
    return listing_date > close_date # True = faulty value, False = correct value

def purchase_after_close(purchase_date,close_date):
    return purchase_date > close_date # True = faulty value, False = correct value


enriched_sold['list_after_close_flag']= enriched_sold.apply(
    lambda row: list_after_close(row['ListingContractDate'],row['CloseDate']),
                axis=1
)

enriched_sold['purchase_after_close_flag']=enriched_sold.apply(
    lambda row: purchase_after_close(row['PurchaseContractDate'],row['CloseDate']),
    axis=1
)

In [72]:
enriched_sold['negative_timeline_flag'] = (
    enriched_sold['list_after_close_flag'] | enriched_sold['purchase_after_close_flag']
)

enriched_sold_postimeline = enriched_sold[enriched_sold['negative_timeline_flag']==False].copy()
print(enriched_sold_postimeline.info())
display(enriched_sold_postimeline.head())

<class 'pandas.core.frame.DataFrame'>
Index: 331327 entries, 0 to 331596
Data columns (total 76 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   BuyerAgentAOR                259965 non-null  object
 1   ListAgentAOR                 263467 non-null  object
 2   Flooring                     194697 non-null  object
 3   ViewYN                       298261 non-null  object
 4   PoolPrivateYN                286293 non-null  object
 5   OriginalListPrice            330529 non-null  float64
 6   ListingKey                   331327 non-null  int64
 7   ListAgentEmail               288286 non-null  object
 8   CloseDate                    331327 non-null  datetime64[ns]
 9   ClosePrice                   331323 non-null  float64
 10  ListAgentFirstName           329213 non-null  object
 11  ListAgentLastName            331297 non-null  object
 12  Latitude                     312438 non-null  float64
 13  Longitude                    312603 non-null  float64
 14  UnparsedAddress              330809 non-null  object
 15  PropertyType                 331327 non-null  object
 16  LivingArea                   307863 non-null  float64
 17  ListPrice                    330848 non-null  float64
 18  DaysOnMarket                 331327 non-null  int64
 19  ListOfficeName               331327 non-null  object
 20  BuyerOfficeName              326517 non-null  object
 21  CoListOfficeName             67651 non-null   object
 22  ListAgentFullName            331246 non-null  object
 23  CoListAgentFirstName         67337 non-null   object
 24  CoListAgentLastName          67484 non-null   object
 25  BuyerAgentMlsId              330459 non-null  object
 26  BuyerAgentFirstName          329709 non-null  object
 27  BuyerAgentLastName           331151 non-null  object
 28  AssociationFeeFrequency      98673 non-null   object
 29  ListingKeyNumeric            331327 non-null  int64
 30  MLSAreaMajor                 295034 non-null  object
 31  CountyOrParish               331327 non-null  object
 32  MlsStatus                    331327 non-null  object
 33  ElementarySchool             37942 non-null   object
 34  AttachedGarageYN             241045 non-null  object
 35  ParkingTotal                 320344 non-null  float64
 36  PropertySubType              305308 non-null  object
 37  LotSizeAcres                 297845 non-null  float64
 38  SubdivisionName              116162 non-null  object
 39  BuyerOfficeAOR               317396 non-null  object
 40  YearBuilt                    317312 non-null  float64
 41  StreetNumberNumeric          330459 non-null  float64
 42  ListingId                    331327 non-null  object
 43  BathroomsTotalInteger        315764 non-null  float64
 44  City                         331022 non-null  object
 45  BedroomsTotal                309054 non-null  float64
 46  ContractStatusChangeDate     330615 non-null  datetime64[ns]
 47  PurchaseContractDate         324659 non-null  datetime64[ns]
 48  ListingContractDate          331278 non-null  datetime64[ns]
 49  StateOrProvince              331327 non-null  object
 50  MiddleOrJuniorSchool         38187 non-null   object
 51  FireplaceYN                  301834 non-null  object
 52  Stories                      260735 non-null  float64
 53  HighSchool                   49563 non-null   object
 54  Levels                       281189 non-null  object
 55  LotSizeArea                  298949 non-null  float64
 56  MainLevelBedrooms            173398 non-null  float64
 57  NewConstructionYN            292140 non-null  object
 58  GarageSpaces                 289600 non-null  float64
 59  HighSchoolDistrict           222546 non-null  object
 60  PostalCode                   331224 non-null  object
 61  AssociationFee               228039 non-null  float64
 62  LotSizeSquareFeet            298686 non-null  float64
 63  OriginatingSystemName        60548 non-null   object
 64  OriginatingSystemSubName     60548 non-null   object
 65  Year                         331327 non-null  int64
 66  Month                        331327 non-null  int64
 67  BuyerAgencyCompensationType  67667 non-null   object
 68  BuyerAgencyCompensation      67701 non-null   float64
 69  latfilled                    77001 non-null   object
 70  lonfilled                    77001 non-null   object
 71  year_month                   331327 non-null  object
 72  rate_30yr_fixed              331327 non-null  float64
 73  list_after_close_flag        331327 non-null  bool
 74  purchase_after_close_flag    331327 non-null  bool
 75  negative_timeline_flag       331327 non-null  bool
dtypes: bool(3), datetime64[ns](4), float64(20), int64(5), object(44)
memory usage: 188.0+ MB
None

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
1,HighDesert,HighDesert,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,2024-01-24,950.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
2,OrangeCounty,OrangeCounty,NaN,True,NaN,75000.0,529986282,Joe@9WINWIN.com,2024-01-16,45000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
3,InlandValleys,InlandValleys,NaN,True,NaN,199000.0,529618166,carolthefinder@yahoo.com,2024-01-08,141500.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,19500.0,522614340,jtavisola@tavisola.com,2024-01-17,15000.0,...,1,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False

In [73]:
enriched_listing['list_after_close_flag']= enriched_sold.apply(
    lambda row: list_after_close(row['ListingContractDate'],row['CloseDate']),
                axis=1
)

enriched_listing['purchase_after_close_flag']=enriched_sold.apply(
    lambda row: purchase_after_close(row['PurchaseContractDate'],row['CloseDate']),
    axis=1
)

In [74]:
enriched_listing['negative_timeline_flag'] = (
    enriched_listing['list_after_close_flag'] | enriched_listing['purchase_after_close_flag']
)
enriched_listing_postimeline = enriched_listing[enriched_listing['negative_timeline_flag']==False].copy()
print(enriched_listing_postimeline.info())
display(enriched_listing_postimeline.head())

<class 'pandas.core.frame.DataFrame'>
Index: 297103 entries, 0 to 297357
Data columns (total 91 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             296710 non-null  float64
 1   ListingKey                    297103 non-null  int64
 2   ListAgentEmail                264304 non-null  object
 3   CloseDate                     64604 non-null   datetime64[ns]
 4   ClosePrice                    50902 non-null   float64
 5   ListAgentFirstName            294661 non-null  object
 6   ListAgentLastName             297088 non-null  object
 7   Latitude                      219408 non-null  float64
 8   Longitude                     219408 non-null  float64
 9   UnparsedAddress               296692 non-null  object
 10  PropertyType                  297103 non-null  object
 11  LivingArea                    296797 non-null  float64
 12  ListPrice                     297103 non-null  float64
 13  DaysOnMarket                  297103 non-null  int64
 14  ListOfficeName                297103 non-null  object
 15  BuyerOfficeName               58875 non-null   object
 16  CoListOfficeName              65565 non-null   object
 17  ListAgentFullName             297078 non-null  object
 18  CoListAgentFirstName          65240 non-null   object
 19  CoListAgentLastName           65459 non-null   object
 20  BuyerAgentMlsId               59996 non-null   object
 21  BuyerAgentFirstName           59655 non-null   object
 22  BuyerAgentLastName            60023 non-null   object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       126511 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             297103 non-null  int64
 27  MLSAreaMajor                  257442 non-null  object
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                297103 non-null  object
 30  PropertyType.1                297103 non-null  object
 31  MlsStatus                     297103 non-null  object
 32  ElementarySchool              36160 non-null   object
 33  ListAgentFirstName.1          294661 non-null  object
 34  AttachedGarageYN              245561 non-null  object
 35  ParkingTotal                  297087 non-null  float64
 36  BuilderName                   13553 non-null   object
 37  PropertySubType               296462 non-null  object
 38  LotSizeAcres                  271445 non-null  float64
 39  SubdivisionName               108376 non-null  object
 40  BuyerOfficeAOR                56098 non-null   object
 41  YearBuilt                     296569 non-null  float64
 42  DaysOnMarket.1                297103 non-null  int64
 43  BuyerAgencyCompensationType   78906 non-null   object
 44  StreetNumberNumeric           296595 non-null  float64
 45  LivingArea.1                  296797 non-null  float64
 46  ListingId                     297103 non-null  object
 47  BathroomsTotalInteger         297067 non-null  float64
 48  City                          296729 non-null  object
 49  BuyerAgencyCompensation       78886 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             26289 non-null   float64
 52  BedroomsTotal                 297043 non-null  float64
 53  ContractStatusChangeDate      293281 non-null  datetime64[ns]
 54  Longitude.1                   219408 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         5178 non-null    object
 57  PurchaseContractDate          131366 non-null  datetime64[ns]
 58  ListingContractDate           297103 non-null  datetime64[ns]
 59  BelowGradeFinishedArea        1511 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    219408 non-null  float64
 62  ListPrice.1                   297103 non-null  float64
 63  StateOrProvince               297070 non-null  object
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          36273 non-null   object
 66  FireplaceYN                   296807 non-null  object
 67  Stories                       242572 non-null  float64
 68  HighSchool                    47258 non-null   object
 69  Levels                        262549 non-null  object
 70  ListAgentLastName.1           297088 non-null  object
 71  CloseDate.1                   64604 non-null   object
 72  LotSizeDimensions             15372 non-null   object
 73  LotSizeArea                   271914 non-null  float64
 74  MainLevelBedrooms             160595 non-null  float64
 75  NewConstructionYN             277372 non-null  object
 76  GarageSpaces                  280918 non-null  float64
 77  HighSchoolDistrict            208936 non-null  object
 78  PostalCode                    297097 non-null  object
 79  BuyerOfficeName.1             58875 non-null   object
 80  AssociationFee                224844 non-null  float64
 81  LotSizeSquareFeet             271830 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             296692 non-null  object
 84  Year                          297103 non-null  int64
 85  Month                         297103 non-null  int64
 86  year_month                    297103 non-null  object
 87  rate_30yr_fixed               297103 non-null  float64
 88  list_after_close_flag         297103 non-null  bool
 89  purchase_after_close_flag     297103 non-null  bool
 90  negative_timeline_flag        297103 non-null  bool
dtypes: bool(3), datetime64[ns](4), float64(34), int64(6), object(44)
memory usage: 202.6+ MB
None

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,177861.0,NaN,2220 Avenue Of The Stars 2704,2024,1,2024-01,6.6425,False,False,False
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,5300.0,NaN,16 Palisades,2024,1,2024-01,6.6425,False,False,False
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,9404.0,NaN,1615 Waverly Road,2024,1,2024-01,6.6425,False,False,False
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,58232.0,NaN,2250 Indian Creek Road,2024,1,2024-01,6.6425,False,False,False
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,2250.0,NaN,317 E. Bayfront,2024,1,2024-01,6.6425,False,False,False

In [75]:
# Checking Longtitude & Latitude for valid format
enriched_listing_postimeline['Latitude']=pd.to_numeric(enriched_listing_postimeline['Latitude'],errors='coerce')
enriched_listing_postimeline['Longitude']=pd.to_numeric(enriched_listing_postimeline['Longitude'],errors='coerce')

enriched_sold_postimeline['Latitude']=pd.to_numeric(enriched_sold_postimeline['Latitude'],errors='coerce')
enriched_sold_postimeline['Longitude']=pd.to_numeric(enriched_sold_postimeline['Longitude'],errors='coerce')

def check_coord(longitude,latitude):
    if not pd.isna(longitude) and not pd.isna(latitude):
        if (longitude < 0) and (latitude != 0):
            if (32.5 <= latitude <= 42.0) and (-124.5 <= longitude <= -114.0):
                return True # True = coordinate is valid and pass all checks
    return False
            
enriched_listing_postimeline['correct_coord'] = enriched_listing_postimeline.apply(
    lambda row: check_coord(row['Longitude'],row['Latitude']),
    axis=1
)

enriched_sold_postimeline['correct_coord'] = enriched_sold_postimeline.apply(
    lambda row: check_coord(row['Longitude'],row['Latitude']),
    axis=1
)

In [79]:
print('Correct Coordinates Value Counts for Sold Data\n')
print(enriched_sold_postimeline['correct_coord'].value_counts())
print('\nCorrect Coordinates Value Counts for Listing Data\n')
print(enriched_listing_postimeline['correct_coord'].value_counts())

Correct Coordinates Value Counts for Sold Data

correct_coord
True     312347
False     18980
Name: count, dtype: int64

Correct Coordinates Value Counts for Listing Data

correct_coord
True     219239
False     77864
Name: count, dtype: int64

In [84]:
enriched_sold_v3 = enriched_sold_postimeline[enriched_sold_postimeline['correct_coord']==True]
print(enriched_sold_v3.info())
display(enriched_sold_v3.head())

<class 'pandas.core.frame.DataFrame'>
Index: 312347 entries, 1 to 331596
Data columns (total 77 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   BuyerAgentAOR                255806 non-null  object
 1   ListAgentAOR                 259238 non-null  object
 2   Flooring                     182244 non-null  object
 3   ViewYN                       284165 non-null  object
 4   PoolPrivateYN                274240 non-null  object
 5   OriginalListPrice            311640 non-null  float64
 6   ListingKey                   312347 non-null  int64
 7   ListAgentEmail               269774 non-null  object
 8   CloseDate                    312347 non-null  datetime64[ns]
 9   ClosePrice                   312343 non-null  float64
 10  ListAgentFirstName           310782 non-null  object
 11  ListAgentLastName            312317 non-null  object
 12  Latitude                     312347 non-null  float64
 13  Longitude                    312347 non-null  float64
 14  UnparsedAddress              311990 non-null  object
 15  PropertyType                 312347 non-null  object
 16  LivingArea                   289772 non-null  float64
 17  ListPrice                    311869 non-null  float64
 18  DaysOnMarket                 312347 non-null  int64
 19  ListOfficeName               312347 non-null  object
 20  BuyerOfficeName              308707 non-null  object
 21  CoListOfficeName             63758 non-null   object
 22  ListAgentFullName            312267 non-null  object
 23  CoListAgentFirstName         63540 non-null   object
 24  CoListAgentLastName          63668 non-null   object
 25  BuyerAgentMlsId              311485 non-null  object
 26  BuyerAgentFirstName          311140 non-null  object
 27  BuyerAgentLastName           312183 non-null  object
 28  AssociationFeeFrequency      92379 non-null   object
 29  ListingKeyNumeric            312347 non-null  int64
 30  MLSAreaMajor                 282159 non-null  object
 31  CountyOrParish               312347 non-null  object
 32  MlsStatus                    312347 non-null  object
 33  ElementarySchool             35614 non-null   object
 34  AttachedGarageYN             226006 non-null  object
 35  ParkingTotal                 301829 non-null  float64
 36  PropertySubType              287939 non-null  object
 37  LotSizeAcres                 283294 non-null  float64
 38  SubdivisionName              105962 non-null  object
 39  BuyerOfficeAOR               300439 non-null  object
 40  YearBuilt                    298916 non-null  float64
 41  StreetNumberNumeric          311704 non-null  float64
 42  ListingId                    312347 non-null  object
 43  BathroomsTotalInteger        296828 non-null  float64
 44  City                         312116 non-null  object
 45  BedroomsTotal                290992 non-null  float64
 46  ContractStatusChangeDate     312233 non-null  datetime64[ns]
 47  PurchaseContractDate         305680 non-null  datetime64[ns]
 48  ListingContractDate          312298 non-null  datetime64[ns]
 49  StateOrProvince              312347 non-null  object
 50  MiddleOrJuniorSchool         35992 non-null   object
 51  FireplaceYN                  284227 non-null  object
 52  Stories                      250587 non-null  float64
 53  HighSchool                   47039 non-null   object
 54  Levels                       270147 non-null  object
 55  LotSizeArea                  284384 non-null  float64
 56  MainLevelBedrooms            173228 non-null  float64
 57  NewConstructionYN            275150 non-null  object
 58  GarageSpaces                 271578 non-null  float64
 59  HighSchoolDistrict           213655 non-null  object
 60  PostalCode                   312244 non-null  object
 61  AssociationFee               218800 non-null  float64
 62  LotSizeSquareFeet            284123 non-null  float64
 63  OriginatingSystemName        56680 non-null   object
 64  OriginatingSystemSubName     56680 non-null   object
 65  Year                         312347 non-null  int64
 66  Month                        312347 non-null  int64
 67  BuyerAgencyCompensationType  52916 non-null   object
 68  BuyerAgencyCompensation      52996 non-null   float64
 69  latfilled                    76757 non-null   object
 70  lonfilled                    76757 non-null   object
 71  year_month                   312347 non-null  object
 72  rate_30yr_fixed              312347 non-null  float64
 73  list_after_close_flag        312347 non-null  bool
 74  purchase_after_close_flag    312347 non-null  bool
 75  negative_timeline_flag       312347 non-null  bool
 76  correct_coord                312347 non-null  bool
dtypes: bool(4), datetime64[ns](4), float64(20), int64(5), object(44)
memory usage: 177.5+ MB
None

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag,correct_coord
1,HighDesert,HighDesert,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,2024-01-24,950.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
2,OrangeCounty,OrangeCounty,NaN,True,NaN,75000.0,529986282,Joe@9WINWIN.com,2024-01-16,45000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
3,InlandValleys,InlandValleys,NaN,True,NaN,199000.0,529618166,carolthefinder@yahoo.com,2024-01-08,141500.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,19500.0,522614340,jtavisola@tavisola.com,2024-01-17,15000.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True
7,Laguna,Laguna,"Carpet,Tile",True,False,5500.0,518662094,Sydney@Agentsyd.com,2024-01-29,1200.0,...,NaN,NaN,NaN,NaN,2024-01,6.6425,False,False,False,True

In [85]:
enriched_listing_v3 = enriched_listing_postimeline[enriched_listing_postimeline['correct_coord']==True]
print(enriched_listing_v3.info())
display(enriched_listing_v3.head())

<class 'pandas.core.frame.DataFrame'>
Index: 219239 entries, 0 to 297357
Data columns (total 92 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             219065 non-null  float64
 1   ListingKey                    219239 non-null  int64
 2   ListAgentEmail                186845 non-null  object
 3   CloseDate                     42143 non-null   datetime64[ns]
 4   ClosePrice                    35788 non-null   float64
 5   ListAgentFirstName            218150 non-null  object
 6   ListAgentLastName             219227 non-null  object
 7   Latitude                      219239 non-null  float64
 8   Longitude                     219239 non-null  float64
 9   UnparsedAddress               218977 non-null  object
 10  PropertyType                  219239 non-null  object
 11  LivingArea                    218951 non-null  float64
 12  ListPrice                     219239 non-null  float64
 13  DaysOnMarket                  219239 non-null  int64
 14  ListOfficeName                219239 non-null  object
 15  BuyerOfficeName               39451 non-null   object
 16  CoListOfficeName              49535 non-null   object
 17  ListAgentFullName             219214 non-null  object
 18  CoListAgentFirstName          49355 non-null   object
 19  CoListAgentLastName           49522 non-null   object
 20  BuyerAgentMlsId               39683 non-null   object
 21  BuyerAgentFirstName           39606 non-null   object
 22  BuyerAgentLastName            39705 non-null   object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       95347 non-null   object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             219239 non-null  int64
 27  MLSAreaMajor                  200289 non-null  object
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                219239 non-null  object
 30  PropertyType.1                219239 non-null  object
 31  MlsStatus                     219239 non-null  object
 32  ElementarySchool              25260 non-null   object
 33  ListAgentFirstName.1          218150 non-null  object
 34  AttachedGarageYN              178003 non-null  object
 35  ParkingTotal                  219237 non-null  float64
 36  BuilderName                   10132 non-null   object
 37  PropertySubType               218872 non-null  object
 38  LotSizeAcres                  203230 non-null  float64
 39  SubdivisionName               72133 non-null   object
 40  BuyerOfficeAOR                37978 non-null   object
 41  YearBuilt                     218719 non-null  float64
 42  DaysOnMarket.1                219239 non-null  int64
 43  BuyerAgencyCompensationType   56929 non-null   object
 44  StreetNumberNumeric           218943 non-null  float64
 45  LivingArea.1                  218951 non-null  float64
 46  ListingId                     219239 non-null  object
 47  BathroomsTotalInteger         219207 non-null  float64
 48  City                          219069 non-null  object
 49  BuyerAgencyCompensation       56939 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             26257 non-null   float64
 52  BedroomsTotal                 219181 non-null  float64
 53  ContractStatusChangeDate      215610 non-null  datetime64[ns]
 54  Longitude.1                   219239 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         3860 non-null    object
 57  PurchaseContractDate          93126 non-null   datetime64[ns]
 58  ListingContractDate           219239 non-null  datetime64[ns]
 59  BelowGradeFinishedArea        1250 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    219239 non-null  float64
 62  ListPrice.1                   219239 non-null  float64
 63  StateOrProvince               219239 non-null  object
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          25574 non-null   object
 66  FireplaceYN                   218956 non-null  object
 67  Stories                       187059 non-null  float64
 68  HighSchool                    33939 non-null   object
 69  Levels                        202447 non-null  object
 70  ListAgentLastName.1           219227 non-null  object
 71  CloseDate.1                   42143 non-null   object
 72  LotSizeDimensions             14470 non-null   object
 73  LotSizeArea                   203686 non-null  float64
 74  MainLevelBedrooms             130891 non-null  float64
 75  NewConstructionYN             199549 non-null  object
 76  GarageSpaces                  203124 non-null  float64
 77  HighSchoolDistrict            157356 non-null  object
 78  PostalCode                    219237 non-null  object
 79  BuyerOfficeName.1             39451 non-null   object
 80  AssociationFee                174379 non-null  float64
 81  LotSizeSquareFeet             203614 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             218977 non-null  object
 84  Year                          219239 non-null  int64
 85  Month                         219239 non-null  int64
 86  year_month                    219239 non-null  object
 87  rate_30yr_fixed               219239 non-null  float64
 88  list_after_close_flag         219239 non-null  bool
 89  purchase_after_close_flag     219239 non-null  bool
 90  negative_timeline_flag        219239 non-null  bool
 91  correct_coord                 219239 non-null  bool
dtypes: bool(4), datetime64[ns](4), float64(34), int64(6), object(44)
memory usage: 149.7+ MB
None

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year,Month,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_timeline_flag,correct_coord
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,2220 Avenue Of The Stars 2704,2024,1,2024-01,6.6425,False,False,False,True
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,NaN,16 Palisades,2024,1,2024-01,6.6425,False,False,False,True
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,1615 Waverly Road,2024,1,2024-01,6.6425,False,False,False,True
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,NaN,2250 Indian Creek Road,2024,1,2024-01,6.6425,False,False,False,True
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,NaN,317 E. Bayfront,2024,1,2024-01,6.6425,False,False,False,True

In [86]:
# Find the difference in rows after checking for date and coordinates

sold_r_change = len(enriched_sold)-len(enriched_sold_v3)

listing_r_change = len(enriched_listing)-len(enriched_listing_v3)

print(f'After checking for correct timeline and coordinates, {sold_r_change} rows are removed for Sold data')
print(f'After checking for correct timeline and coordinates, {listing_r_change} rows are removed for Listing data')

After checking for correct timeline and coordinates, 19250 rows are removed for Sold data
After checking for correct timeline and coordinates, 78119 rows are removed for Listing data

In [87]:
enriched_sold_v3.to_csv('enriched_sold_v3.csv',index=True,encoding='utf-8-sig')
enriched_listing_v3.to_csv('enriched_listing_v3.csv',index=True,encoding='utf-8-sig')